// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.2
// source: sisyphus/v1/blob.proto

package sisyphusv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BlobService_Put_FullMethodName            = "/sisyphus.v1.BlobService/Put"
	BlobService_Get_FullMethodName            = "/sisyphus.v1.BlobService/Get"
	BlobService_Stat_FullMethodName           = "/sisyphus.v1.BlobService/Stat"
	BlobService_Locate_FullMethodName         = "/sisyphus.v1.BlobService/Locate"
	BlobService_Pin_FullMethodName            = "/sisyphus.v1.BlobService/Pin"
	BlobService_Unpin_FullMethodName          = "/sisyphus.v1.BlobService/Unpin"
	BlobService_ListPins_FullMethodName       = "/sisyphus.v1.BlobService/ListPins"
	BlobService_CollectGarbage_FullMethodName = "/sisyphus.v1.BlobService/CollectGarbage"
)

// BlobServiceClient is the client API for BlobService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BlobService moves content-addressed artifacts to and from a node's store.
// Blobs are named by the CID that `ipfs add --cid-version=1` gives the same
// bytes.
type BlobServiceClient interface {
	// Put stores the concatenation of every message's data as one blob.
	Put(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PutBlobRequest, PutBlobResponse], error)
	// Get streams a blob's bytes in order. Receivers should check that what
	// they received hashes to the CID they asked for.
	Get(ctx context.Context, in *GetBlobRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetBlobResponse], error)
	Stat(ctx context.Context, in *StatBlobRequest, opts ...grpc.CallOption) (*StatBlobResponse, error)
	// Locate names other workers of the pool believed to hold a blob and
	// willing to serve it, so that a worker can fetch it from one of them
	// rather than from the coordinator. The answer is a hint: a worker listed
	// may have dropped the blob since.
	Locate(ctx context.Context, in *LocateBlobRequest, opts ...grpc.CallOption) (*LocateBlobResponse, error)
	// A node keeps a blob for as long as something pins it. Pin and Unpin act
	// on the pin held on behalf of the node's user; jobs hold their own.
	Pin(ctx context.Context, in *PinBlobRequest, opts ...grpc.CallOption) (*PinBlobResponse, error)
	Unpin(ctx context.Context, in *UnpinBlobRequest, opts ...grpc.CallOption) (*UnpinBlobResponse, error)
	ListPins(ctx context.Context, in *ListPinsRequest, opts ...grpc.CallOption) (*ListPinsResponse, error)
	// CollectGarbage drops pins that have expired and deletes every block no
	// remaining pin reaches.
	CollectGarbage(ctx context.Context, in *CollectGarbageRequest, opts ...grpc.CallOption) (*CollectGarbageResponse, error)
}

type blobServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBlobServiceClient(cc grpc.ClientConnInterface) BlobServiceClient {
	return &blobServiceClient{cc}
}

func (c *blobServiceClient) Put(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PutBlobRequest, PutBlobResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BlobService_ServiceDesc.Streams[0], BlobService_Put_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PutBlobRequest, PutBlobResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlobService_PutClient = grpc.ClientStreamingClient[PutBlobRequest, PutBlobResponse]

func (c *blobServiceClient) Get(ctx context.Context, in *GetBlobRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetBlobResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BlobService_ServiceDesc.Streams[1], BlobService_Get_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetBlobRequest, GetBlobResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlobService_GetClient = grpc.ServerStreamingClient[GetBlobResponse]

func (c *blobServiceClient) Stat(ctx context.Context, in *StatBlobRequest, opts ...grpc.CallOption) (*StatBlobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatBlobResponse)
	err := c.cc.Invoke(ctx, BlobService_Stat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blobServiceClient) Locate(ctx context.Context, in *LocateBlobRequest, opts ...grpc.CallOption) (*LocateBlobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LocateBlobResponse)
	err := c.cc.Invoke(ctx, BlobService_Locate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blobServiceClient) Pin(ctx context.Context, in *PinBlobRequest, opts ...grpc.CallOption) (*PinBlobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PinBlobResponse)
	err := c.cc.Invoke(ctx, BlobService_Pin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blobServiceClient) Unpin(ctx context.Context, in *UnpinBlobRequest, opts ...grpc.CallOption) (*UnpinBlobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnpinBlobResponse)
	err := c.cc.Invoke(ctx, BlobService_Unpin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blobServiceClient) ListPins(ctx context.Context, in *ListPinsRequest, opts ...grpc.CallOption) (*ListPinsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPinsResponse)
	err := c.cc.Invoke(ctx, BlobService_ListPins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blobServiceClient) CollectGarbage(ctx context.Context, in *CollectGarbageRequest, opts ...grpc.CallOption) (*CollectGarbageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CollectGarbageResponse)
	err := c.cc.Invoke(ctx, BlobService_CollectGarbage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlobServiceServer is the server API for BlobService service.
// All implementations must embed UnimplementedBlobServiceServer
// for forward compatibility.
//
// BlobService moves content-addressed artifacts to and from a node's store.
// Blobs are named by the CID that `ipfs add --cid-version=1` gives the same
// bytes.
type BlobServiceServer interface {
	// Put stores the concatenation of every message's data as one blob.
	Put(grpc.ClientStreamingServer[PutBlobRequest, PutBlobResponse]) error
	// Get streams a blob's bytes in order. Receivers should check that what
	// they received hashes to the CID they asked for.
	Get(*GetBlobRequest, grpc.ServerStreamingServer[GetBlobResponse]) error
	Stat(context.Context, *StatBlobRequest) (*StatBlobResponse, error)
	// Locate names other workers of the pool believed to hold a blob and
	// willing to serve it, so that a worker can fetch it from one of them
	// rather than from the coordinator. The answer is a hint: a worker listed
	// may have dropped the blob since.
	Locate(context.Context, *LocateBlobRequest) (*LocateBlobResponse, error)
	// A node keeps a blob for as long as something pins it. Pin and Unpin act
	// on the pin held on behalf of the node's user; jobs hold their own.
	Pin(context.Context, *PinBlobRequest) (*PinBlobResponse, error)
	Unpin(context.Context, *UnpinBlobRequest) (*UnpinBlobResponse, error)
	ListPins(context.Context, *ListPinsRequest) (*ListPinsResponse, error)
	// CollectGarbage drops pins that have expired and deletes every block no
	// remaining pin reaches.
	CollectGarbage(context.Context, *CollectGarbageRequest) (*CollectGarbageResponse, error)
	mustEmbedUnimplementedBlobServiceServer()
}

// UnimplementedBlobServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlobServiceServer struct{}

func (UnimplementedBlobServiceServer) Put(grpc.ClientStreamingServer[PutBlobRequest, PutBlobResponse]) error {
	return status.Error(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedBlobServiceServer) Get(*GetBlobRequest, grpc.ServerStreamingServer[GetBlobResponse]) error {
	return status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedBlobServiceServer) Stat(context.Context, *StatBlobRequest) (*StatBlobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stat not implemented")
}
func (UnimplementedBlobServiceServer) Locate(context.Context, *LocateBlobRequest) (*LocateBlobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Locate not implemented")
}
func (UnimplementedBlobServiceServer) Pin(context.Context, *PinBlobRequest) (*PinBlobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Pin not implemented")
}
func (UnimplementedBlobServiceServer) Unpin(context.Context, *UnpinBlobRequest) (*UnpinBlobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Unpin not implemented")
}
func (UnimplementedBlobServiceServer) ListPins(context.Context, *ListPinsRequest) (*ListPinsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPins not implemented")
}
func (UnimplementedBlobServiceServer) CollectGarbage(context.Context, *CollectGarbageRequest) (*CollectGarbageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CollectGarbage not implemented")
}
func (UnimplementedBlobServiceServer) mustEmbedUnimplementedBlobServiceServer() {}
func (UnimplementedBlobServiceServer) testEmbeddedByValue()                     {}

// UnsafeBlobServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlobServiceServer will
// result in compilation errors.
type UnsafeBlobServiceServer interface {
	mustEmbedUnimplementedBlobServiceServer()
}

func RegisterBlobServiceServer(s grpc.ServiceRegistrar, srv BlobServiceServer) {
	// If the following call panics, it indicates UnimplementedBlobServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BlobService_ServiceDesc, srv)
}

func _BlobService_Put_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BlobServiceServer).Put(&grpc.GenericServerStream[PutBlobRequest, PutBlobResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlobService_PutServer = grpc.ClientStreamingServer[PutBlobRequest, PutBlobResponse]

func _BlobService_Get_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetBlobRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BlobServiceServer).Get(m, &grpc.GenericServerStream[GetBlobRequest, GetBlobResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlobService_GetServer = grpc.ServerStreamingServer[GetBlobResponse]

func _BlobService_Stat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatBlobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlobServiceServer).Stat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlobService_Stat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlobServiceServer).Stat(ctx, req.(*StatBlobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlobService_Locate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocateBlobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlobServiceServer).Locate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlobService_Locate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlobServiceServer).Locate(ctx, req.(*LocateBlobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlobService_Pin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PinBlobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlobServiceServer).Pin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlobService_Pin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlobServiceServer).Pin(ctx, req.(*PinBlobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlobService_Unpin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnpinBlobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlobServiceServer).Unpin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlobService_Unpin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlobServiceServer).Unpin(ctx, req.(*UnpinBlobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlobService_ListPins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPinsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlobServiceServer).ListPins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlobService_ListPins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlobServiceServer).ListPins(ctx, req.(*ListPinsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlobService_CollectGarbage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectGarbageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlobServiceServer).CollectGarbage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlobService_CollectGarbage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlobServiceServer).CollectGarbage(ctx, req.(*CollectGarbageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BlobService_ServiceDesc is the grpc.ServiceDesc for BlobService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlobService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sisyphus.v1.BlobService",
	HandlerType: (*BlobServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Stat",
			Handler:    _BlobService_Stat_Handler,
		},
		{
			MethodName: "Locate",
			Handler:    _BlobService_Locate_Handler,
		},
		{
			MethodName: "Pin",
			Handler:    _BlobService_Pin_Handler,
		},
		{
			MethodName: "Unpin",
			Handler:    _BlobService_Unpin_Handler,
		},
		{
			MethodName: "ListPins",
			Handler:    _BlobService_ListPins_Handler,
		},
		{
			MethodName: "CollectGarbage",
			Handler:    _BlobService_CollectGarbage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Put",
			Handler:       _BlobService_Put_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Get",
			Handler:       _BlobService_Get_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sisyphus/v1/blob.proto",
}
