// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: sisyphus/v1/blob.proto

package sisyphusv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PutBlobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutBlobRequest) Reset() {
	*x = PutBlobRequest{}
	mi := &file_sisyphus_v1_blob_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutBlobRequest) ProtoMessage() {}

func (x *PutBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_blob_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutBlobRequest.ProtoReflect.Descriptor instead.
func (*PutBlobRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_blob_proto_rawDescGZIP(), []int{0}
}

func (x *PutBlobRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PutBlobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           string                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Size          uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutBlobResponse) Reset() {
	*x = PutBlobResponse{}
	mi := &file_sisyphus_v1_blob_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutBlobResponse) ProtoMessage() {}

func (x *PutBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_blob_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutBlobResponse.ProtoReflect.Descriptor instead.
func (*PutBlobResponse) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_blob_proto_rawDescGZIP(), []int{1}
}

func (x *PutBlobResponse) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *PutBlobResponse) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GetBlobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           string                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlobRequest) Reset() {
	*x = GetBlobRequest{}
	mi := &file_sisyphus_v1_blob_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlobRequest) ProtoMessage() {}

func (x *GetBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_blob_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlobRequest.ProtoReflect.Descriptor instead.
func (*GetBlobRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_blob_proto_rawDescGZIP(), []int{2}
}

func (x *GetBlobRequest) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

type GetBlobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlobResponse) Reset() {
	*x = GetBlobResponse{}
	mi := &file_sisyphus_v1_blob_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlobResponse) ProtoMessage() {}

func (x *GetBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_blob_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlobResponse.ProtoReflect.Descriptor instead.
func (*GetBlobResponse) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_blob_proto_rawDescGZIP(), []int{3}
}

func (x *GetBlobResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type StatBlobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           string                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatBlobRequest) Reset() {
	*x = StatBlobRequest{}
	mi := &file_sisyphus_v1_blob_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatBlobRequest) ProtoMessage() {}

func (x *StatBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_blob_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatBlobRequest.ProtoReflect.Descriptor instead.
func (*StatBlobRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_blob_proto_rawDescGZIP(), []int{4}
}

func (x *StatBlobRequest) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

type StatBlobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          uint64                 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatBlobResponse) Reset() {
	*x = StatBlobResponse{}
	mi := &file_sisyphus_v1_blob_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatBlobResponse) ProtoMessage() {}

func (x *StatBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_blob_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatBlobResponse.ProtoReflect.Descriptor instead.
func (*StatBlobResponse) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_blob_proto_rawDescGZIP(), []int{5}
}

func (x *StatBlobResponse) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_sisyphus_v1_blob_proto protoreflect.FileDescriptor

const file_sisyphus_v1_blob_proto_rawDesc = "" +
	"\n" +
	"\x16sisyphus/v1/blob.proto\x12\vsisyphus.v1\"$\n" +
	"\x0ePutBlobRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"7\n" +
	"\x0fPutBlobResponse\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\tR\x03cid\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\"\"\n" +
	"\x0eGetBlobRequest\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\tR\x03cid\"%\n" +
	"\x0fGetBlobResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"#\n" +
	"\x0fStatBlobRequest\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\tR\x03cid\"&\n" +
	"\x10StatBlobResponse\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x04R\x04size2\xda\x01\n" +
	"\vBlobService\x12B\n" +
	"\x03Put\x12\x1b.sisyphus.v1.PutBlobRequest\x1a\x1c.sisyphus.v1.PutBlobResponse(\x01\x12B\n" +
	"\x03Get\x12\x1b.sisyphus.v1.GetBlobRequest\x1a\x1c.sisyphus.v1.GetBlobResponse0\x01\x12C\n" +
	"\x04Stat\x12\x1c.sisyphus.v1.StatBlobRequest\x1a\x1d.sisyphus.v1.StatBlobResponseBEZCgithub.com/excho0/Sisyphus/packages/protocol/sisyphus/v1;sisyphusv1b\x06proto3"

var (
	file_sisyphus_v1_blob_proto_rawDescOnce sync.Once
	file_sisyphus_v1_blob_proto_rawDescData []byte
)

func file_sisyphus_v1_blob_proto_rawDescGZIP() []byte {
	file_sisyphus_v1_blob_proto_rawDescOnce.Do(func() {
		file_sisyphus_v1_blob_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sisyphus_v1_blob_proto_rawDesc), len(file_sisyphus_v1_blob_proto_rawDesc)))
	})
	return file_sisyphus_v1_blob_proto_rawDescData
}

var file_sisyphus_v1_blob_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_sisyphus_v1_blob_proto_goTypes = []any{
	(*PutBlobRequest)(nil),   // 0: sisyphus.v1.PutBlobRequest
	(*PutBlobResponse)(nil),  // 1: sisyphus.v1.PutBlobResponse
	(*GetBlobRequest)(nil),   // 2: sisyphus.v1.GetBlobRequest
	(*GetBlobResponse)(nil),  // 3: sisyphus.v1.GetBlobResponse
	(*StatBlobRequest)(nil),  // 4: sisyphus.v1.StatBlobRequest
	(*StatBlobResponse)(nil), // 5: sisyphus.v1.StatBlobResponse
}
var file_sisyphus_v1_blob_proto_depIdxs = []int32{
	0, // 0: sisyphus.v1.BlobService.Put:input_type -> sisyphus.v1.PutBlobRequest
	2, // 1: sisyphus.v1.BlobService.Get:input_type -> sisyphus.v1.GetBlobRequest
	4, // 2: sisyphus.v1.BlobService.Stat:input_type -> sisyphus.v1.StatBlobRequest
	1, // 3: sisyphus.v1.BlobService.Put:output_type -> sisyphus.v1.PutBlobResponse
	3, // 4: sisyphus.v1.BlobService.Get:output_type -> sisyphus.v1.GetBlobResponse
	5, // 5: sisyphus.v1.BlobService.Stat:output_type -> sisyphus.v1.StatBlobResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sisyphus_v1_blob_proto_init() }
func file_sisyphus_v1_blob_proto_init() {
	if File_sisyphus_v1_blob_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sisyphus_v1_blob_proto_rawDesc), len(file_sisyphus_v1_blob_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sisyphus_v1_blob_proto_goTypes,
		DependencyIndexes: file_sisyphus_v1_blob_proto_depIdxs,
		MessageInfos:      file_sisyphus_v1_blob_proto_msgTypes,
	}.Build()
	File_sisyphus_v1_blob_proto = out.File
	file_sisyphus_v1_blob_proto_goTypes = nil
	file_sisyphus_v1_blob_proto_depIdxs = nil
}
