// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: sisyphus/v1/blob.proto

package sisyphusv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PutBlobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutBlobRequest) Reset() {
	*x = PutBlobRequest{}
	mi := &file_sisyphus_v1_blob_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutBlobRequest) ProtoMessage() {}

func (x *PutBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_blob_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutBlobRequest.ProtoReflect.Descriptor instead.
func (*PutBlobRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_blob_proto_rawDescGZIP(), []int{0}
}

func (x *PutBlobRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PutBlobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           string                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Size          uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutBlobResponse) Reset() {
	*x = PutBlobResponse{}
	mi := &file_sisyphus_v1_blob_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutBlobResponse) ProtoMessage() {}

func (x *PutBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_blob_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutBlobResponse.ProtoReflect.Descriptor instead.
func (*PutBlobResponse) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_blob_proto_rawDescGZIP(), []int{1}
}

func (x *PutBlobResponse) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *PutBlobResponse) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GetBlobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           string                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlobRequest) Reset() {
	*x = GetBlobRequest{}
	mi := &file_sisyphus_v1_blob_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlobRequest) ProtoMessage() {}

func (x *GetBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_blob_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlobRequest.ProtoReflect.Descriptor instead.
func (*GetBlobRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_blob_proto_rawDescGZIP(), []int{2}
}

func (x *GetBlobRequest) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

type GetBlobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlobResponse) Reset() {
	*x = GetBlobResponse{}
	mi := &file_sisyphus_v1_blob_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlobResponse) ProtoMessage() {}

func (x *GetBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_blob_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlobResponse.ProtoReflect.Descriptor instead.
func (*GetBlobResponse) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_blob_proto_rawDescGZIP(), []int{3}
}

func (x *GetBlobResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type StatBlobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           string                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatBlobRequest) Reset() {
	*x = StatBlobRequest{}
	mi := &file_sisyphus_v1_blob_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatBlobRequest) ProtoMessage() {}

func (x *StatBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_blob_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatBlobRequest.ProtoReflect.Descriptor instead.
func (*StatBlobRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_blob_proto_rawDescGZIP(), []int{4}
}

func (x *StatBlobRequest) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

type StatBlobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          uint64                 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatBlobResponse) Reset() {
	*x = StatBlobResponse{}
	mi := &file_sisyphus_v1_blob_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatBlobResponse) ProtoMessage() {}

func (x *StatBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_blob_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatBlobResponse.ProtoReflect.Descriptor instead.
func (*StatBlobResponse) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_blob_proto_rawDescGZIP(), []int{5}
}

func (x *StatBlobResponse) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type LocateBlobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           string                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocateBlobRequest) Reset() {
	*x = LocateBlobRequest{}
	mi := &file_sisyphus_v1_blob_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocateBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocateBlobRequest) ProtoMessage() {}

func (x *LocateBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_blob_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocateBlobRequest.ProtoReflect.Descriptor instead.
func (*LocateBlobRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_blob_proto_rawDescGZIP(), []int{6}
}

func (x *LocateBlobRequest) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

type LocateBlobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Holders       []*BlobHolder          `protobuf:"bytes,1,rep,name=holders,proto3" json:"holders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocateBlobResponse) Reset() {
	*x = LocateBlobResponse{}
	mi := &file_sisyphus_v1_blob_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocateBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocateBlobResponse) ProtoMessage() {}

func (x *LocateBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_blob_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocateBlobResponse.ProtoReflect.Descriptor instead.
func (*LocateBlobResponse) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_blob_proto_rawDescGZIP(), []int{7}
}

func (x *LocateBlobResponse) GetHolders() []*BlobHolder {
	if x != nil {
		return x.Holders
	}
	return nil
}

type BlobHolder struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	NodeId string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// host:port of the holder's blob service.
	Address       string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobHolder) Reset() {
	*x = BlobHolder{}
	mi := &file_sisyphus_v1_blob_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobHolder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobHolder) ProtoMessage() {}

func (x *BlobHolder) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_blob_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobHolder.ProtoReflect.Descriptor instead.
func (*BlobHolder) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_blob_proto_rawDescGZIP(), []int{8}
}

func (x *BlobHolder) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *BlobHolder) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type PinBlobRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Cid   string                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	// How long to keep the blob. Zero means until it is unpinned.
	TtlSeconds    uint64 `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinBlobRequest) Reset() {
	*x = PinBlobRequest{}
	mi := &file_sisyphus_v1_blob_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinBlobRequest) ProtoMessage() {}

func (x *PinBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_blob_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinBlobRequest.ProtoReflect.Descriptor instead.
func (*PinBlobRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_blob_proto_rawDescGZIP(), []int{9}
}

func (x *PinBlobRequest) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *PinBlobRequest) GetTtlSeconds() uint64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type PinBlobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinBlobResponse) Reset() {
	*x = PinBlobResponse{}
	mi := &file_sisyphus_v1_blob_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinBlobResponse) ProtoMessage() {}

func (x *PinBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_blob_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinBlobResponse.ProtoReflect.Descriptor instead.
func (*PinBlobResponse) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_blob_proto_rawDescGZIP(), []int{10}
}

type UnpinBlobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           string                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnpinBlobRequest) Reset() {
	*x = UnpinBlobRequest{}
	mi := &file_sisyphus_v1_blob_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnpinBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnpinBlobRequest) ProtoMessage() {}

func (x *UnpinBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_blob_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnpinBlobRequest.ProtoReflect.Descriptor instead.
func (*UnpinBlobRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_blob_proto_rawDescGZIP(), []int{11}
}

func (x *UnpinBlobRequest) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

type UnpinBlobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnpinBlobResponse) Reset() {
	*x = UnpinBlobResponse{}
	mi := &file_sisyphus_v1_blob_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnpinBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnpinBlobResponse) ProtoMessage() {}

func (x *UnpinBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_blob_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnpinBlobResponse.ProtoReflect.Descriptor instead.
func (*UnpinBlobResponse) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_blob_proto_rawDescGZIP(), []int{12}
}

type ListPinsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPinsRequest) Reset() {
	*x = ListPinsRequest{}
	mi := &file_sisyphus_v1_blob_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPinsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPinsRequest) ProtoMessage() {}

func (x *ListPinsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_blob_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPinsRequest.ProtoReflect.Descriptor instead.
func (*ListPinsRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_blob_proto_rawDescGZIP(), []int{13}
}

type ListPinsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pins          []*Pin                 `protobuf:"bytes,1,rep,name=pins,proto3" json:"pins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPinsResponse) Reset() {
	*x = ListPinsResponse{}
	mi := &file_sisyphus_v1_blob_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPinsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPinsResponse) ProtoMessage() {}

func (x *ListPinsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_blob_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPinsResponse.ProtoReflect.Descriptor instead.
func (*ListPinsResponse) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_blob_proto_rawDescGZIP(), []int{14}
}

func (x *ListPinsResponse) GetPins() []*Pin {
	if x != nil {
		return x.Pins
	}
	return nil
}

type Pin struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Cid   string                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	// Who holds the pin: "user", "job:<id>", or "recent" for the short pin
	// every newly stored blob gets.
	Owner string `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	// Unset for a pin that holds until released.
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pin) Reset() {
	*x = Pin{}
	mi := &file_sisyphus_v1_blob_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pin) ProtoMessage() {}

func (x *Pin) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_blob_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pin.ProtoReflect.Descriptor instead.
func (*Pin) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_blob_proto_rawDescGZIP(), []int{15}
}

func (x *Pin) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *Pin) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Pin) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type CollectGarbageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectGarbageRequest) Reset() {
	*x = CollectGarbageRequest{}
	mi := &file_sisyphus_v1_blob_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectGarbageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectGarbageRequest) ProtoMessage() {}

func (x *CollectGarbageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_blob_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectGarbageRequest.ProtoReflect.Descriptor instead.
func (*CollectGarbageRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_blob_proto_rawDescGZIP(), []int{16}
}

type CollectGarbageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpiredPins   uint32                 `protobuf:"varint,1,opt,name=expired_pins,json=expiredPins,proto3" json:"expired_pins,omitempty"`
	BlocksRemoved uint64                 `protobuf:"varint,2,opt,name=blocks_removed,json=blocksRemoved,proto3" json:"blocks_removed,omitempty"`
	BytesFreed    uint64                 `protobuf:"varint,3,opt,name=bytes_freed,json=bytesFreed,proto3" json:"bytes_freed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectGarbageResponse) Reset() {
	*x = CollectGarbageResponse{}
	mi := &file_sisyphus_v1_blob_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectGarbageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectGarbageResponse) ProtoMessage() {}

func (x *CollectGarbageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_blob_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectGarbageResponse.ProtoReflect.Descriptor instead.
func (*CollectGarbageResponse) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_blob_proto_rawDescGZIP(), []int{17}
}

func (x *CollectGarbageResponse) GetExpiredPins() uint32 {
	if x != nil {
		return x.ExpiredPins
	}
	return 0
}

func (x *CollectGarbageResponse) GetBlocksRemoved() uint64 {
	if x != nil {
		return x.BlocksRemoved
	}
	return 0
}

func (x *CollectGarbageResponse) GetBytesFreed() uint64 {
	if x != nil {
		return x.BytesFreed
	}
	return 0
}

var File_sisyphus_v1_blob_proto protoreflect.FileDescriptor

const file_sisyphus_v1_blob_proto_rawDesc = "" +
	"\n" +
	"\x16sisyphus/v1/blob.proto\x12\vsisyphus.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"$\n" +
	"\x0ePutBlobRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"7\n" +
	"\x0fPutBlobResponse\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\tR\x03cid\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\"\"\n" +
	"\x0eGetBlobRequest\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\tR\x03cid\"%\n" +
	"\x0fGetBlobResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"#\n" +
	"\x0fStatBlobRequest\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\tR\x03cid\"&\n" +
	"\x10StatBlobResponse\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x04R\x04size\"%\n" +
	"\x11LocateBlobRequest\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\tR\x03cid\"G\n" +
	"\x12LocateBlobResponse\x121\n" +
	"\aholders\x18\x01 \x03(\v2\x17.sisyphus.v1.BlobHolderR\aholders\"?\n" +
	"\n" +
	"BlobHolder\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"C\n" +
	"\x0ePinBlobRequest\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\tR\x03cid\x12\x1f\n" +
	"\vttl_seconds\x18\x02 \x01(\x04R\n" +
	"ttlSeconds\"\x11\n" +
	"\x0fPinBlobResponse\"$\n" +
	"\x10UnpinBlobRequest\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\tR\x03cid\"\x13\n" +
	"\x11UnpinBlobResponse\"\x11\n" +
	"\x0fListPinsRequest\"8\n" +
	"\x10ListPinsResponse\x12$\n" +
	"\x04pins\x18\x01 \x03(\v2\x10.sisyphus.v1.PinR\x04pins\"h\n" +
	"\x03Pin\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\tR\x03cid\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\x17\n" +
	"\x15CollectGarbageRequest\"\x83\x01\n" +
	"\x16CollectGarbageResponse\x12!\n" +
	"\fexpired_pins\x18\x01 \x01(\rR\vexpiredPins\x12%\n" +
	"\x0eblocks_removed\x18\x02 \x01(\x04R\rblocksRemoved\x12\x1f\n" +
	"\vbytes_freed\x18\x03 \x01(\x04R\n" +
	"bytesFreed2\xd3\x04\n" +
	"\vBlobService\x12B\n" +
	"\x03Put\x12\x1b.sisyphus.v1.PutBlobRequest\x1a\x1c.sisyphus.v1.PutBlobResponse(\x01\x12B\n" +
	"\x03Get\x12\x1b.sisyphus.v1.GetBlobRequest\x1a\x1c.sisyphus.v1.GetBlobResponse0\x01\x12C\n" +
	"\x04Stat\x12\x1c.sisyphus.v1.StatBlobRequest\x1a\x1d.sisyphus.v1.StatBlobResponse\x12I\n" +
	"\x06Locate\x12\x1e.sisyphus.v1.LocateBlobRequest\x1a\x1f.sisyphus.v1.LocateBlobResponse\x12@\n" +
	"\x03Pin\x12\x1b.sisyphus.v1.PinBlobRequest\x1a\x1c.sisyphus.v1.PinBlobResponse\x12F\n" +
	"\x05Unpin\x12\x1d.sisyphus.v1.UnpinBlobRequest\x1a\x1e.sisyphus.v1.UnpinBlobResponse\x12G\n" +
	"\bListPins\x12\x1c.sisyphus.v1.ListPinsRequest\x1a\x1d.sisyphus.v1.ListPinsResponse\x12Y\n" +
	"\x0eCollectGarbage\x12\".sisyphus.v1.CollectGarbageRequest\x1a#.sisyphus.v1.CollectGarbageResponseBOZMgithub.com/sisyphus-network/Sisyphus/packages/protocol/sisyphus/v1;sisyphusv1b\x06proto3"

var (
	file_sisyphus_v1_blob_proto_rawDescOnce sync.Once
	file_sisyphus_v1_blob_proto_rawDescData []byte
)

func file_sisyphus_v1_blob_proto_rawDescGZIP() []byte {
	file_sisyphus_v1_blob_proto_rawDescOnce.Do(func() {
		file_sisyphus_v1_blob_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sisyphus_v1_blob_proto_rawDesc), len(file_sisyphus_v1_blob_proto_rawDesc)))
	})
	return file_sisyphus_v1_blob_proto_rawDescData
}

var file_sisyphus_v1_blob_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_sisyphus_v1_blob_proto_goTypes = []any{
	(*PutBlobRequest)(nil),         // 0: sisyphus.v1.PutBlobRequest
	(*PutBlobResponse)(nil),        // 1: sisyphus.v1.PutBlobResponse
	(*GetBlobRequest)(nil),         // 2: sisyphus.v1.GetBlobRequest
	(*GetBlobResponse)(nil),        // 3: sisyphus.v1.GetBlobResponse
	(*StatBlobRequest)(nil),        // 4: sisyphus.v1.StatBlobRequest
	(*StatBlobResponse)(nil),       // 5: sisyphus.v1.StatBlobResponse
	(*LocateBlobRequest)(nil),      // 6: sisyphus.v1.LocateBlobRequest
	(*LocateBlobResponse)(nil),     // 7: sisyphus.v1.LocateBlobResponse
	(*BlobHolder)(nil),             // 8: sisyphus.v1.BlobHolder
	(*PinBlobRequest)(nil),         // 9: sisyphus.v1.PinBlobRequest
	(*PinBlobResponse)(nil),        // 10: sisyphus.v1.PinBlobResponse
	(*UnpinBlobRequest)(nil),       // 11: sisyphus.v1.UnpinBlobRequest
	(*UnpinBlobResponse)(nil),      // 12: sisyphus.v1.UnpinBlobResponse
	(*ListPinsRequest)(nil),        // 13: sisyphus.v1.ListPinsRequest
	(*ListPinsResponse)(nil),       // 14: sisyphus.v1.ListPinsResponse
	(*Pin)(nil),                    // 15: sisyphus.v1.Pin
	(*CollectGarbageRequest)(nil),  // 16: sisyphus.v1.CollectGarbageRequest
	(*CollectGarbageResponse)(nil), // 17: sisyphus.v1.CollectGarbageResponse
	(*timestamppb.Timestamp)(nil),  // 18: google.protobuf.Timestamp
}
var file_sisyphus_v1_blob_proto_depIdxs = []int32{
	8,  // 0: sisyphus.v1.LocateBlobResponse.holders:type_name -> sisyphus.v1.BlobHolder
	15, // 1: sisyphus.v1.ListPinsResponse.pins:type_name -> sisyphus.v1.Pin
	18, // 2: sisyphus.v1.Pin.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 3: sisyphus.v1.BlobService.Put:input_type -> sisyphus.v1.PutBlobRequest
	2,  // 4: sisyphus.v1.BlobService.Get:input_type -> sisyphus.v1.GetBlobRequest
	4,  // 5: sisyphus.v1.BlobService.Stat:input_type -> sisyphus.v1.StatBlobRequest
	6,  // 6: sisyphus.v1.BlobService.Locate:input_type -> sisyphus.v1.LocateBlobRequest
	9,  // 7: sisyphus.v1.BlobService.Pin:input_type -> sisyphus.v1.PinBlobRequest
	11, // 8: sisyphus.v1.BlobService.Unpin:input_type -> sisyphus.v1.UnpinBlobRequest
	13, // 9: sisyphus.v1.BlobService.ListPins:input_type -> sisyphus.v1.ListPinsRequest
	16, // 10: sisyphus.v1.BlobService.CollectGarbage:input_type -> sisyphus.v1.CollectGarbageRequest
	1,  // 11: sisyphus.v1.BlobService.Put:output_type -> sisyphus.v1.PutBlobResponse
	3,  // 12: sisyphus.v1.BlobService.Get:output_type -> sisyphus.v1.GetBlobResponse
	5,  // 13: sisyphus.v1.BlobService.Stat:output_type -> sisyphus.v1.StatBlobResponse
	7,  // 14: sisyphus.v1.BlobService.Locate:output_type -> sisyphus.v1.LocateBlobResponse
	10, // 15: sisyphus.v1.BlobService.Pin:output_type -> sisyphus.v1.PinBlobResponse
	12, // 16: sisyphus.v1.BlobService.Unpin:output_type -> sisyphus.v1.UnpinBlobResponse
	14, // 17: sisyphus.v1.BlobService.ListPins:output_type -> sisyphus.v1.ListPinsResponse
	17, // 18: sisyphus.v1.BlobService.CollectGarbage:output_type -> sisyphus.v1.CollectGarbageResponse
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_sisyphus_v1_blob_proto_init() }
func file_sisyphus_v1_blob_proto_init() {
	if File_sisyphus_v1_blob_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sisyphus_v1_blob_proto_rawDesc), len(file_sisyphus_v1_blob_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sisyphus_v1_blob_proto_goTypes,
		DependencyIndexes: file_sisyphus_v1_blob_proto_depIdxs,
		MessageInfos:      file_sisyphus_v1_blob_proto_msgTypes,
	}.Build()
	File_sisyphus_v1_blob_proto = out.File
	file_sisyphus_v1_blob_proto_goTypes = nil
	file_sisyphus_v1_blob_proto_depIdxs = nil
}
