// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: sisyphus/v1/coordinator.proto

package sisyphusv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*WorkerMessage_Hello
	//	*WorkerMessage_Heartbeat
	//	*WorkerMessage_TaskResult
	//	*WorkerMessage_TaskUpdate
	Kind          isWorkerMessage_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMessage) Reset() {
	*x = WorkerMessage{}
	mi := &file_sisyphus_v1_coordinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMessage) ProtoMessage() {}

func (x *WorkerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_coordinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMessage.ProtoReflect.Descriptor instead.
func (*WorkerMessage) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_coordinator_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerMessage) GetKind() isWorkerMessage_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *WorkerMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Kind.(*WorkerMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *WorkerMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Kind.(*WorkerMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *WorkerMessage) GetTaskResult() *TaskResult {
	if x != nil {
		if x, ok := x.Kind.(*WorkerMessage_TaskResult); ok {
			return x.TaskResult
		}
	}
	return nil
}

func (x *WorkerMessage) GetTaskUpdate() *TaskUpdate {
	if x != nil {
		if x, ok := x.Kind.(*WorkerMessage_TaskUpdate); ok {
			return x.TaskUpdate
		}
	}
	return nil
}

type isWorkerMessage_Kind interface {
	isWorkerMessage_Kind()
}

type WorkerMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type WorkerMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type WorkerMessage_TaskResult struct {
	TaskResult *TaskResult `protobuf:"bytes,3,opt,name=task_result,json=taskResult,proto3,oneof"`
}

type WorkerMessage_TaskUpdate struct {
	TaskUpdate *TaskUpdate `protobuf:"bytes,4,opt,name=task_update,json=taskUpdate,proto3,oneof"`
}

func (*WorkerMessage_Hello) isWorkerMessage_Kind() {}

func (*WorkerMessage_Heartbeat) isWorkerMessage_Kind() {}

func (*WorkerMessage_TaskResult) isWorkerMessage_Kind() {}

func (*WorkerMessage_TaskUpdate) isWorkerMessage_Kind() {}

// TaskUpdate is news of a task still running: how far along it is, and
// what it has logged since the last one.
type TaskUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Attempt       uint32                 `protobuf:"varint,2,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Progress      float64                `protobuf:"fixed64,3,opt,name=progress,proto3" json:"progress,omitempty"`
	Log           []string               `protobuf:"bytes,4,rep,name=log,proto3" json:"log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskUpdate) Reset() {
	*x = TaskUpdate{}
	mi := &file_sisyphus_v1_coordinator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskUpdate) ProtoMessage() {}

func (x *TaskUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_coordinator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskUpdate.ProtoReflect.Descriptor instead.
func (*TaskUpdate) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_coordinator_proto_rawDescGZIP(), []int{1}
}

func (x *TaskUpdate) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskUpdate) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *TaskUpdate) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *TaskUpdate) GetLog() []string {
	if x != nil {
		return x.Log
	}
	return nil
}

type Hello struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Capabilities *NodeCapabilities      `protobuf:"bytes,2,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	// A label for people to recognise the node by. It need not be unique.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Where other workers of the pool can fetch blobs from this one, as
	// host:port, or empty if it does not serve them.
	ServeAddress string `protobuf:"bytes,4,opt,name=serve_address,json=serveAddress,proto3" json:"serve_address,omitempty"`
	// Where this node's libp2p host can be reached, if it relays between the
	// pool's members: multiaddresses ending in /p2p/ and its ID. Empty for a
	// node that does not relay.
	RelayAddresses []string `protobuf:"bytes,5,rep,name=relay_addresses,json=relayAddresses,proto3" json:"relay_addresses,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_sisyphus_v1_coordinator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_coordinator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_coordinator_proto_rawDescGZIP(), []int{2}
}

func (x *Hello) GetCapabilities() *NodeCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Hello) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Hello) GetServeAddress() string {
	if x != nil {
		return x.ServeAddress
	}
	return ""
}

func (x *Hello) GetRelayAddresses() []string {
	if x != nil {
		return x.RelayAddresses
	}
	return nil
}

type Heartbeat struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	RunningTasks uint32                 `protobuf:"varint,1,opt,name=running_tasks,json=runningTasks,proto3" json:"running_tasks,omitempty"`
	// What the node has relayed between other members since it started: how
	// many times it joined two of them, and how many bytes passed.
	RelayedConnections uint64 `protobuf:"varint,2,opt,name=relayed_connections,json=relayedConnections,proto3" json:"relayed_connections,omitempty"`
	RelayedBytes       uint64 `protobuf:"varint,3,opt,name=relayed_bytes,json=relayedBytes,proto3" json:"relayed_bytes,omitempty"`
	// Set when the worker's labels are not what it last said they were: a
	// model fetched or removed since. Absent, they are as they were.
	Labels        *Labels `protobuf:"bytes,4,opt,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_sisyphus_v1_coordinator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_coordinator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_coordinator_proto_rawDescGZIP(), []int{3}
}

func (x *Heartbeat) GetRunningTasks() uint32 {
	if x != nil {
		return x.RunningTasks
	}
	return 0
}

func (x *Heartbeat) GetRelayedConnections() uint64 {
	if x != nil {
		return x.RelayedConnections
	}
	return 0
}

func (x *Heartbeat) GetRelayedBytes() uint64 {
	if x != nil {
		return x.RelayedBytes
	}
	return 0
}

func (x *Heartbeat) GetLabels() *Labels {
	if x != nil {
		return x.Labels
	}
	return nil
}

type Labels struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Labels        []string               `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Labels) Reset() {
	*x = Labels{}
	mi := &file_sisyphus_v1_coordinator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Labels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Labels) ProtoMessage() {}

func (x *Labels) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_coordinator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Labels.ProtoReflect.Descriptor instead.
func (*Labels) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_coordinator_proto_rawDescGZIP(), []int{4}
}

func (x *Labels) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type TaskResult struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	TaskId string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// Echoes TaskAssignment.attempt so the coordinator can drop stale results.
	Attempt uint32 `protobuf:"varint,2,opt,name=attempt,proto3" json:"attempt,omitempty"`
	// Types that are valid to be assigned to Outcome:
	//
	//	*TaskResult_Output
	//	*TaskResult_Error
	Outcome isTaskResult_Outcome `protobuf_oneof:"outcome"`
	// CIDs of the stored blobs the task opened and stored. The coordinator
	// uses them to keep a job's data for as long as the job needs it.
	ReadBlobs     []string `protobuf:"bytes,5,rep,name=read_blobs,json=readBlobs,proto3" json:"read_blobs,omitempty"`
	WrittenBlobs  []string `protobuf:"bytes,6,rep,name=written_blobs,json=writtenBlobs,proto3" json:"written_blobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_sisyphus_v1_coordinator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_coordinator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_coordinator_proto_rawDescGZIP(), []int{5}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *TaskResult) GetOutcome() isTaskResult_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *TaskResult) GetOutput() []byte {
	if x != nil {
		if x, ok := x.Outcome.(*TaskResult_Output); ok {
			return x.Output
		}
	}
	return nil
}

func (x *TaskResult) GetError() string {
	if x != nil {
		if x, ok := x.Outcome.(*TaskResult_Error); ok {
			return x.Error
		}
	}
	return ""
}

func (x *TaskResult) GetReadBlobs() []string {
	if x != nil {
		return x.ReadBlobs
	}
	return nil
}

func (x *TaskResult) GetWrittenBlobs() []string {
	if x != nil {
		return x.WrittenBlobs
	}
	return nil
}

type isTaskResult_Outcome interface {
	isTaskResult_Outcome()
}

type TaskResult_Output struct {
	Output []byte `protobuf:"bytes,3,opt,name=output,proto3,oneof"`
}

type TaskResult_Error struct {
	Error string `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*TaskResult_Output) isTaskResult_Outcome() {}

func (*TaskResult_Error) isTaskResult_Outcome() {}

type CoordinatorMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*CoordinatorMessage_Welcome
	//	*CoordinatorMessage_Assignment
	//	*CoordinatorMessage_SwarmUpdate
	//	*CoordinatorMessage_Cancel
	Kind          isCoordinatorMessage_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorMessage) Reset() {
	*x = CoordinatorMessage{}
	mi := &file_sisyphus_v1_coordinator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorMessage) ProtoMessage() {}

func (x *CoordinatorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_coordinator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorMessage.ProtoReflect.Descriptor instead.
func (*CoordinatorMessage) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_coordinator_proto_rawDescGZIP(), []int{6}
}

func (x *CoordinatorMessage) GetKind() isCoordinatorMessage_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *CoordinatorMessage) GetWelcome() *Welcome {
	if x != nil {
		if x, ok := x.Kind.(*CoordinatorMessage_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *CoordinatorMessage) GetAssignment() *TaskAssignment {
	if x != nil {
		if x, ok := x.Kind.(*CoordinatorMessage_Assignment); ok {
			return x.Assignment
		}
	}
	return nil
}

func (x *CoordinatorMessage) GetSwarmUpdate() *SwarmUpdate {
	if x != nil {
		if x, ok := x.Kind.(*CoordinatorMessage_SwarmUpdate); ok {
			return x.SwarmUpdate
		}
	}
	return nil
}

func (x *CoordinatorMessage) GetCancel() *TaskCancel {
	if x != nil {
		if x, ok := x.Kind.(*CoordinatorMessage_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

type isCoordinatorMessage_Kind interface {
	isCoordinatorMessage_Kind()
}

type CoordinatorMessage_Welcome struct {
	Welcome *Welcome `protobuf:"bytes,1,opt,name=welcome,proto3,oneof"`
}

type CoordinatorMessage_Assignment struct {
	Assignment *TaskAssignment `protobuf:"bytes,2,opt,name=assignment,proto3,oneof"`
}

type CoordinatorMessage_SwarmUpdate struct {
	SwarmUpdate *SwarmUpdate `protobuf:"bytes,3,opt,name=swarm_update,json=swarmUpdate,proto3,oneof"`
}

type CoordinatorMessage_Cancel struct {
	Cancel *TaskCancel `protobuf:"bytes,4,opt,name=cancel,proto3,oneof"`
}

func (*CoordinatorMessage_Welcome) isCoordinatorMessage_Kind() {}

func (*CoordinatorMessage_Assignment) isCoordinatorMessage_Kind() {}

func (*CoordinatorMessage_SwarmUpdate) isCoordinatorMessage_Kind() {}

func (*CoordinatorMessage_Cancel) isCoordinatorMessage_Kind() {}

// TaskCancel tells a worker to stop a task it was given. Nothing is expected
// back: whatever the task goes on to report is ignored.
type TaskCancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Attempt       uint32                 `protobuf:"varint,2,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskCancel) Reset() {
	*x = TaskCancel{}
	mi := &file_sisyphus_v1_coordinator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskCancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCancel) ProtoMessage() {}

func (x *TaskCancel) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_coordinator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCancel.ProtoReflect.Descriptor instead.
func (*TaskCancel) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_coordinator_proto_rawDescGZIP(), []int{7}
}

func (x *TaskCancel) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskCancel) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

type Welcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CoordinatorId string                 `protobuf:"bytes,1,opt,name=coordinator_id,json=coordinatorId,proto3" json:"coordinator_id,omitempty"`
	// Identifies the key of the pool's private IPFS network without giving it
	// away; empty if the pool has no such network. A worker whose own Kubo is
	// on a different key should ask PoolService.Swarm for the current one.
	SwarmFingerprint string `protobuf:"bytes,2,opt,name=swarm_fingerprint,json=swarmFingerprint,proto3" json:"swarm_fingerprint,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_sisyphus_v1_coordinator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_coordinator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_coordinator_proto_rawDescGZIP(), []int{8}
}

func (x *Welcome) GetCoordinatorId() string {
	if x != nil {
		return x.CoordinatorId
	}
	return ""
}

func (x *Welcome) GetSwarmFingerprint() string {
	if x != nil {
		return x.SwarmFingerprint
	}
	return ""
}

// SwarmUpdate tells a connected worker that the key of the pool's private
// IPFS network has changed, as it does when a member is removed.
type SwarmUpdate struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SwarmFingerprint string                 `protobuf:"bytes,1,opt,name=swarm_fingerprint,json=swarmFingerprint,proto3" json:"swarm_fingerprint,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SwarmUpdate) Reset() {
	*x = SwarmUpdate{}
	mi := &file_sisyphus_v1_coordinator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwarmUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwarmUpdate) ProtoMessage() {}

func (x *SwarmUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_coordinator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwarmUpdate.ProtoReflect.Descriptor instead.
func (*SwarmUpdate) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_coordinator_proto_rawDescGZIP(), []int{9}
}

func (x *SwarmUpdate) GetSwarmFingerprint() string {
	if x != nil {
		return x.SwarmFingerprint
	}
	return ""
}

type TaskAssignment struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TaskId   string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	JobId    string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Attempt  uint32                 `protobuf:"varint,3,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Workload string                 `protobuf:"bytes,4,opt,name=workload,proto3" json:"workload,omitempty"`
	Payload  []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	// A sealing key whole. It was once the key of every private job. It is
	// now given only with keys, and only when the job names an input sealed
	// before keys were derived, which nothing less opens.
	Key []byte `protobuf:"bytes,6,opt,name=key,proto3" json:"key,omitempty"`
	// For a private job: the keys its tasks may use, each derived from the
	// submitter's sealing key. The first is the job's own, which what a task
	// stores is sealed with; the rest open the sealed inputs the job names.
	Keys          []*SealingKey `protobuf:"bytes,7,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskAssignment) Reset() {
	*x = TaskAssignment{}
	mi := &file_sisyphus_v1_coordinator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAssignment) ProtoMessage() {}

func (x *TaskAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_coordinator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAssignment.ProtoReflect.Descriptor instead.
func (*TaskAssignment) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_coordinator_proto_rawDescGZIP(), []int{10}
}

func (x *TaskAssignment) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskAssignment) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *TaskAssignment) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *TaskAssignment) GetWorkload() string {
	if x != nil {
		return x.Workload
	}
	return ""
}

func (x *TaskAssignment) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TaskAssignment) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *TaskAssignment) GetKeys() []*SealingKey {
	if x != nil {
		return x.Keys
	}
	return nil
}

// SealingKey is one key derived from a sealing key, and its ID.
type SealingKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SealingKey) Reset() {
	*x = SealingKey{}
	mi := &file_sisyphus_v1_coordinator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SealingKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SealingKey) ProtoMessage() {}

func (x *SealingKey) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_coordinator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SealingKey.ProtoReflect.Descriptor instead.
func (*SealingKey) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_coordinator_proto_rawDescGZIP(), []int{11}
}

func (x *SealingKey) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *SealingKey) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

var File_sisyphus_v1_coordinator_proto protoreflect.FileDescriptor

const file_sisyphus_v1_coordinator_proto_rawDesc = "" +
	"\n" +
	"\x1dsisyphus/v1/coordinator.proto\x12\vsisyphus.v1\x1a\x17sisyphus/v1/types.proto\"\xf3\x01\n" +
	"\rWorkerMessage\x12*\n" +
	"\x05hello\x18\x01 \x01(\v2\x12.sisyphus.v1.HelloH\x00R\x05hello\x126\n" +
	"\theartbeat\x18\x02 \x01(\v2\x16.sisyphus.v1.HeartbeatH\x00R\theartbeat\x12:\n" +
	"\vtask_result\x18\x03 \x01(\v2\x17.sisyphus.v1.TaskResultH\x00R\n" +
	"taskResult\x12:\n" +
	"\vtask_update\x18\x04 \x01(\v2\x17.sisyphus.v1.TaskUpdateH\x00R\n" +
	"taskUpdateB\x06\n" +
	"\x04kind\"m\n" +
	"\n" +
	"TaskUpdate\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\aattempt\x18\x02 \x01(\rR\aattempt\x12\x1a\n" +
	"\bprogress\x18\x03 \x01(\x01R\bprogress\x12\x10\n" +
	"\x03log\x18\x04 \x03(\tR\x03log\"\xb2\x01\n" +
	"\x05Hello\x12A\n" +
	"\fcapabilities\x18\x02 \x01(\v2\x1d.sisyphus.v1.NodeCapabilitiesR\fcapabilities\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12#\n" +
	"\rserve_address\x18\x04 \x01(\tR\fserveAddress\x12'\n" +
	"\x0frelay_addresses\x18\x05 \x03(\tR\x0erelayAddressesJ\x04\b\x01\x10\x02\"\xb3\x01\n" +
	"\tHeartbeat\x12#\n" +
	"\rrunning_tasks\x18\x01 \x01(\rR\frunningTasks\x12/\n" +
	"\x13relayed_connections\x18\x02 \x01(\x04R\x12relayedConnections\x12#\n" +
	"\rrelayed_bytes\x18\x03 \x01(\x04R\frelayedBytes\x12+\n" +
	"\x06labels\x18\x04 \x01(\v2\x13.sisyphus.v1.LabelsR\x06labels\" \n" +
	"\x06Labels\x12\x16\n" +
	"\x06labels\x18\x01 \x03(\tR\x06labels\"\xc0\x01\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\aattempt\x18\x02 \x01(\rR\aattempt\x12\x18\n" +
	"\x06output\x18\x03 \x01(\fH\x00R\x06output\x12\x16\n" +
	"\x05error\x18\x04 \x01(\tH\x00R\x05error\x12\x1d\n" +
	"\n" +
	"read_blobs\x18\x05 \x03(\tR\treadBlobs\x12#\n" +
	"\rwritten_blobs\x18\x06 \x03(\tR\fwrittenBlobsB\t\n" +
	"\aoutcome\"\xff\x01\n" +
	"\x12CoordinatorMessage\x120\n" +
	"\awelcome\x18\x01 \x01(\v2\x14.sisyphus.v1.WelcomeH\x00R\awelcome\x12=\n" +
	"\n" +
	"assignment\x18\x02 \x01(\v2\x1b.sisyphus.v1.TaskAssignmentH\x00R\n" +
	"assignment\x12=\n" +
	"\fswarm_update\x18\x03 \x01(\v2\x18.sisyphus.v1.SwarmUpdateH\x00R\vswarmUpdate\x121\n" +
	"\x06cancel\x18\x04 \x01(\v2\x17.sisyphus.v1.TaskCancelH\x00R\x06cancelB\x06\n" +
	"\x04kind\"?\n" +
	"\n" +
	"TaskCancel\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\aattempt\x18\x02 \x01(\rR\aattempt\"]\n" +
	"\aWelcome\x12%\n" +
	"\x0ecoordinator_id\x18\x01 \x01(\tR\rcoordinatorId\x12+\n" +
	"\x11swarm_fingerprint\x18\x02 \x01(\tR\x10swarmFingerprint\":\n" +
	"\vSwarmUpdate\x12+\n" +
	"\x11swarm_fingerprint\x18\x01 \x01(\tR\x10swarmFingerprint\"\xcf\x01\n" +
	"\x0eTaskAssignment\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x18\n" +
	"\aattempt\x18\x03 \x01(\rR\aattempt\x12\x1a\n" +
	"\bworkload\x18\x04 \x01(\tR\bworkload\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12\x10\n" +
	"\x03key\x18\x06 \x01(\fR\x03key\x12+\n" +
	"\x04keys\x18\a \x03(\v2\x17.sisyphus.v1.SealingKeyR\x04keys\".\n" +
	"\n" +
	"SealingKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key2`\n" +
	"\x12CoordinatorService\x12J\n" +
	"\aConnect\x12\x1a.sisyphus.v1.WorkerMessage\x1a\x1f.sisyphus.v1.CoordinatorMessage(\x010\x01BOZMgithub.com/sisyphus-network/Sisyphus/packages/protocol/sisyphus/v1;sisyphusv1b\x06proto3"

var (
	file_sisyphus_v1_coordinator_proto_rawDescOnce sync.Once
	file_sisyphus_v1_coordinator_proto_rawDescData []byte
)

func file_sisyphus_v1_coordinator_proto_rawDescGZIP() []byte {
	file_sisyphus_v1_coordinator_proto_rawDescOnce.Do(func() {
		file_sisyphus_v1_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sisyphus_v1_coordinator_proto_rawDesc), len(file_sisyphus_v1_coordinator_proto_rawDesc)))
	})
	return file_sisyphus_v1_coordinator_proto_rawDescData
}

var file_sisyphus_v1_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_sisyphus_v1_coordinator_proto_goTypes = []any{
	(*WorkerMessage)(nil),      // 0: sisyphus.v1.WorkerMessage
	(*TaskUpdate)(nil),         // 1: sisyphus.v1.TaskUpdate
	(*Hello)(nil),              // 2: sisyphus.v1.Hello
	(*Heartbeat)(nil),          // 3: sisyphus.v1.Heartbeat
	(*Labels)(nil),             // 4: sisyphus.v1.Labels
	(*TaskResult)(nil),         // 5: sisyphus.v1.TaskResult
	(*CoordinatorMessage)(nil), // 6: sisyphus.v1.CoordinatorMessage
	(*TaskCancel)(nil),         // 7: sisyphus.v1.TaskCancel
	(*Welcome)(nil),            // 8: sisyphus.v1.Welcome
	(*SwarmUpdate)(nil),        // 9: sisyphus.v1.SwarmUpdate
	(*TaskAssignment)(nil),     // 10: sisyphus.v1.TaskAssignment
	(*SealingKey)(nil),         // 11: sisyphus.v1.SealingKey
	(*NodeCapabilities)(nil),   // 12: sisyphus.v1.NodeCapabilities
}
var file_sisyphus_v1_coordinator_proto_depIdxs = []int32{
	2,  // 0: sisyphus.v1.WorkerMessage.hello:type_name -> sisyphus.v1.Hello
	3,  // 1: sisyphus.v1.WorkerMessage.heartbeat:type_name -> sisyphus.v1.Heartbeat
	5,  // 2: sisyphus.v1.WorkerMessage.task_result:type_name -> sisyphus.v1.TaskResult
	1,  // 3: sisyphus.v1.WorkerMessage.task_update:type_name -> sisyphus.v1.TaskUpdate
	12, // 4: sisyphus.v1.Hello.capabilities:type_name -> sisyphus.v1.NodeCapabilities
	4,  // 5: sisyphus.v1.Heartbeat.labels:type_name -> sisyphus.v1.Labels
	8,  // 6: sisyphus.v1.CoordinatorMessage.welcome:type_name -> sisyphus.v1.Welcome
	10, // 7: sisyphus.v1.CoordinatorMessage.assignment:type_name -> sisyphus.v1.TaskAssignment
	9,  // 8: sisyphus.v1.CoordinatorMessage.swarm_update:type_name -> sisyphus.v1.SwarmUpdate
	7,  // 9: sisyphus.v1.CoordinatorMessage.cancel:type_name -> sisyphus.v1.TaskCancel
	11, // 10: sisyphus.v1.TaskAssignment.keys:type_name -> sisyphus.v1.SealingKey
	0,  // 11: sisyphus.v1.CoordinatorService.Connect:input_type -> sisyphus.v1.WorkerMessage
	6,  // 12: sisyphus.v1.CoordinatorService.Connect:output_type -> sisyphus.v1.CoordinatorMessage
	12, // [12:13] is the sub-list for method output_type
	11, // [11:12] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_sisyphus_v1_coordinator_proto_init() }
func file_sisyphus_v1_coordinator_proto_init() {
	if File_sisyphus_v1_coordinator_proto != nil {
		return
	}
	file_sisyphus_v1_types_proto_init()
	file_sisyphus_v1_coordinator_proto_msgTypes[0].OneofWrappers = []any{
		(*WorkerMessage_Hello)(nil),
		(*WorkerMessage_Heartbeat)(nil),
		(*WorkerMessage_TaskResult)(nil),
		(*WorkerMessage_TaskUpdate)(nil),
	}
	file_sisyphus_v1_coordinator_proto_msgTypes[5].OneofWrappers = []any{
		(*TaskResult_Output)(nil),
		(*TaskResult_Error)(nil),
	}
	file_sisyphus_v1_coordinator_proto_msgTypes[6].OneofWrappers = []any{
		(*CoordinatorMessage_Welcome)(nil),
		(*CoordinatorMessage_Assignment)(nil),
		(*CoordinatorMessage_SwarmUpdate)(nil),
		(*CoordinatorMessage_Cancel)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sisyphus_v1_coordinator_proto_rawDesc), len(file_sisyphus_v1_coordinator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sisyphus_v1_coordinator_proto_goTypes,
		DependencyIndexes: file_sisyphus_v1_coordinator_proto_depIdxs,
		MessageInfos:      file_sisyphus_v1_coordinator_proto_msgTypes,
	}.Build()
	File_sisyphus_v1_coordinator_proto = out.File
	file_sisyphus_v1_coordinator_proto_goTypes = nil
	file_sisyphus_v1_coordinator_proto_depIdxs = nil
}
