// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.2
// source: sisyphus/v1/name.proto

package sisyphusv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NameService_Publish_FullMethodName = "/sisyphus.v1.NameService/Publish"
	NameService_Resolve_FullMethodName = "/sisyphus.v1.NameService/Resolve"
)

// NameServiceClient is the client API for NameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NameService keeps what nodes have published under their names. A name is
// a node's ID, and stands for the content its node last pointed it at, in a
// record signed with the node's key. The records are IPNS records.
type NameServiceClient interface {
	// Publish hands this node the caller's latest record, which it keeps and
	// from then on gives to whoever resolves the caller's name. A node may
	// publish only under its own name. A record older than the one held is
	// refused.
	Publish(ctx context.Context, in *PublishNameRequest, opts ...grpc.CallOption) (*PublishNameResponse, error)
	// Resolve returns the latest record this node holds for a name: its own,
	// or that of a node it has admitted. The record is returned as it was
	// signed, expired or not, and it is for the caller to check it.
	Resolve(ctx context.Context, in *ResolveNameRequest, opts ...grpc.CallOption) (*ResolveNameResponse, error)
}

type nameServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNameServiceClient(cc grpc.ClientConnInterface) NameServiceClient {
	return &nameServiceClient{cc}
}

func (c *nameServiceClient) Publish(ctx context.Context, in *PublishNameRequest, opts ...grpc.CallOption) (*PublishNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishNameResponse)
	err := c.cc.Invoke(ctx, NameService_Publish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nameServiceClient) Resolve(ctx context.Context, in *ResolveNameRequest, opts ...grpc.CallOption) (*ResolveNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveNameResponse)
	err := c.cc.Invoke(ctx, NameService_Resolve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NameServiceServer is the server API for NameService service.
// All implementations must embed UnimplementedNameServiceServer
// for forward compatibility.
//
// NameService keeps what nodes have published under their names. A name is
// a node's ID, and stands for the content its node last pointed it at, in a
// record signed with the node's key. The records are IPNS records.
type NameServiceServer interface {
	// Publish hands this node the caller's latest record, which it keeps and
	// from then on gives to whoever resolves the caller's name. A node may
	// publish only under its own name. A record older than the one held is
	// refused.
	Publish(context.Context, *PublishNameRequest) (*PublishNameResponse, error)
	// Resolve returns the latest record this node holds for a name: its own,
	// or that of a node it has admitted. The record is returned as it was
	// signed, expired or not, and it is for the caller to check it.
	Resolve(context.Context, *ResolveNameRequest) (*ResolveNameResponse, error)
	mustEmbedUnimplementedNameServiceServer()
}

// UnimplementedNameServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNameServiceServer struct{}

func (UnimplementedNameServiceServer) Publish(context.Context, *PublishNameRequest) (*PublishNameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedNameServiceServer) Resolve(context.Context, *ResolveNameRequest) (*ResolveNameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Resolve not implemented")
}
func (UnimplementedNameServiceServer) mustEmbedUnimplementedNameServiceServer() {}
func (UnimplementedNameServiceServer) testEmbeddedByValue()                     {}

// UnsafeNameServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NameServiceServer will
// result in compilation errors.
type UnsafeNameServiceServer interface {
	mustEmbedUnimplementedNameServiceServer()
}

func RegisterNameServiceServer(s grpc.ServiceRegistrar, srv NameServiceServer) {
	// If the following call panics, it indicates UnimplementedNameServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NameService_ServiceDesc, srv)
}

func _NameService_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameServiceServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NameService_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameServiceServer).Publish(ctx, req.(*PublishNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NameService_Resolve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameServiceServer).Resolve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NameService_Resolve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameServiceServer).Resolve(ctx, req.(*ResolveNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NameService_ServiceDesc is the grpc.ServiceDesc for NameService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NameService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sisyphus.v1.NameService",
	HandlerType: (*NameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _NameService_Publish_Handler,
		},
		{
			MethodName: "Resolve",
			Handler:    _NameService_Resolve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sisyphus/v1/name.proto",
}
