// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: sisyphus/v1/node.proto

package sisyphusv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *JobSpec               `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobRequest) Reset() {
	*x = SubmitJobRequest{}
	mi := &file_sisyphus_v1_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobRequest) ProtoMessage() {}

func (x *SubmitJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobRequest.ProtoReflect.Descriptor instead.
func (*SubmitJobRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_node_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitJobRequest) GetSpec() *JobSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type SubmitJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobResponse) Reset() {
	*x = SubmitJobResponse{}
	mi := &file_sisyphus_v1_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobResponse) ProtoMessage() {}

func (x *SubmitJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobResponse.ProtoReflect.Descriptor instead.
func (*SubmitJobResponse) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_node_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitJobResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type GetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_sisyphus_v1_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_node_proto_rawDescGZIP(), []int{2}
}

func (x *GetJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobResponse) Reset() {
	*x = GetJobResponse{}
	mi := &file_sisyphus_v1_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobResponse) ProtoMessage() {}

func (x *GetJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobResponse.ProtoReflect.Descriptor instead.
func (*GetJobResponse) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_node_proto_rawDescGZIP(), []int{3}
}

func (x *GetJobResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type WatchJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchJobRequest) Reset() {
	*x = WatchJobRequest{}
	mi := &file_sisyphus_v1_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchJobRequest) ProtoMessage() {}

func (x *WatchJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchJobRequest.ProtoReflect.Descriptor instead.
func (*WatchJobRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_node_proto_rawDescGZIP(), []int{4}
}

func (x *WatchJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type WatchJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchJobResponse) Reset() {
	*x = WatchJobResponse{}
	mi := &file_sisyphus_v1_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchJobResponse) ProtoMessage() {}

func (x *WatchJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchJobResponse.ProtoReflect.Descriptor instead.
func (*WatchJobResponse) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_node_proto_rawDescGZIP(), []int{5}
}

func (x *WatchJobResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_sisyphus_v1_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_node_proto_rawDescGZIP(), []int{6}
}

type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeInfo            `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_sisyphus_v1_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_node_proto_rawDescGZIP(), []int{7}
}

func (x *ListNodesResponse) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_sisyphus_v1_node_proto protoreflect.FileDescriptor

const file_sisyphus_v1_node_proto_rawDesc = "" +
	"\n" +
	"\x16sisyphus/v1/node.proto\x12\vsisyphus.v1\x1a\x17sisyphus/v1/types.proto\"<\n" +
	"\x10SubmitJobRequest\x12(\n" +
	"\x04spec\x18\x01 \x01(\v2\x14.sisyphus.v1.JobSpecR\x04spec\"7\n" +
	"\x11SubmitJobResponse\x12\"\n" +
	"\x03job\x18\x01 \x01(\v2\x10.sisyphus.v1.JobR\x03job\"&\n" +
	"\rGetJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"4\n" +
	"\x0eGetJobResponse\x12\"\n" +
	"\x03job\x18\x01 \x01(\v2\x10.sisyphus.v1.JobR\x03job\"(\n" +
	"\x0fWatchJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"6\n" +
	"\x10WatchJobResponse\x12\"\n" +
	"\x03job\x18\x01 \x01(\v2\x10.sisyphus.v1.JobR\x03job\"\x12\n" +
	"\x10ListNodesRequest\"@\n" +
	"\x11ListNodesResponse\x12+\n" +
	"\x05nodes\x18\x01 \x03(\v2\x15.sisyphus.v1.NodeInfoR\x05nodes2\xb3\x02\n" +
	"\vNodeService\x12J\n" +
	"\tSubmitJob\x12\x1d.sisyphus.v1.SubmitJobRequest\x1a\x1e.sisyphus.v1.SubmitJobResponse\x12A\n" +
	"\x06GetJob\x12\x1a.sisyphus.v1.GetJobRequest\x1a\x1b.sisyphus.v1.GetJobResponse\x12I\n" +
	"\bWatchJob\x12\x1c.sisyphus.v1.WatchJobRequest\x1a\x1d.sisyphus.v1.WatchJobResponse0\x01\x12J\n" +
	"\tListNodes\x12\x1d.sisyphus.v1.ListNodesRequest\x1a\x1e.sisyphus.v1.ListNodesResponseBEZCgithub.com/excho0/Sisyphus/packages/protocol/sisyphus/v1;sisyphusv1b\x06proto3"

var (
	file_sisyphus_v1_node_proto_rawDescOnce sync.Once
	file_sisyphus_v1_node_proto_rawDescData []byte
)

func file_sisyphus_v1_node_proto_rawDescGZIP() []byte {
	file_sisyphus_v1_node_proto_rawDescOnce.Do(func() {
		file_sisyphus_v1_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sisyphus_v1_node_proto_rawDesc), len(file_sisyphus_v1_node_proto_rawDesc)))
	})
	return file_sisyphus_v1_node_proto_rawDescData
}

var file_sisyphus_v1_node_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_sisyphus_v1_node_proto_goTypes = []any{
	(*SubmitJobRequest)(nil),  // 0: sisyphus.v1.SubmitJobRequest
	(*SubmitJobResponse)(nil), // 1: sisyphus.v1.SubmitJobResponse
	(*GetJobRequest)(nil),     // 2: sisyphus.v1.GetJobRequest
	(*GetJobResponse)(nil),    // 3: sisyphus.v1.GetJobResponse
	(*WatchJobRequest)(nil),   // 4: sisyphus.v1.WatchJobRequest
	(*WatchJobResponse)(nil),  // 5: sisyphus.v1.WatchJobResponse
	(*ListNodesRequest)(nil),  // 6: sisyphus.v1.ListNodesRequest
	(*ListNodesResponse)(nil), // 7: sisyphus.v1.ListNodesResponse
	(*JobSpec)(nil),           // 8: sisyphus.v1.JobSpec
	(*Job)(nil),               // 9: sisyphus.v1.Job
	(*NodeInfo)(nil),          // 10: sisyphus.v1.NodeInfo
}
var file_sisyphus_v1_node_proto_depIdxs = []int32{
	8,  // 0: sisyphus.v1.SubmitJobRequest.spec:type_name -> sisyphus.v1.JobSpec
	9,  // 1: sisyphus.v1.SubmitJobResponse.job:type_name -> sisyphus.v1.Job
	9,  // 2: sisyphus.v1.GetJobResponse.job:type_name -> sisyphus.v1.Job
	9,  // 3: sisyphus.v1.WatchJobResponse.job:type_name -> sisyphus.v1.Job
	10, // 4: sisyphus.v1.ListNodesResponse.nodes:type_name -> sisyphus.v1.NodeInfo
	0,  // 5: sisyphus.v1.NodeService.SubmitJob:input_type -> sisyphus.v1.SubmitJobRequest
	2,  // 6: sisyphus.v1.NodeService.GetJob:input_type -> sisyphus.v1.GetJobRequest
	4,  // 7: sisyphus.v1.NodeService.WatchJob:input_type -> sisyphus.v1.WatchJobRequest
	6,  // 8: sisyphus.v1.NodeService.ListNodes:input_type -> sisyphus.v1.ListNodesRequest
	1,  // 9: sisyphus.v1.NodeService.SubmitJob:output_type -> sisyphus.v1.SubmitJobResponse
	3,  // 10: sisyphus.v1.NodeService.GetJob:output_type -> sisyphus.v1.GetJobResponse
	5,  // 11: sisyphus.v1.NodeService.WatchJob:output_type -> sisyphus.v1.WatchJobResponse
	7,  // 12: sisyphus.v1.NodeService.ListNodes:output_type -> sisyphus.v1.ListNodesResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_sisyphus_v1_node_proto_init() }
func file_sisyphus_v1_node_proto_init() {
	if File_sisyphus_v1_node_proto != nil {
		return
	}
	file_sisyphus_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sisyphus_v1_node_proto_rawDesc), len(file_sisyphus_v1_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sisyphus_v1_node_proto_goTypes,
		DependencyIndexes: file_sisyphus_v1_node_proto_depIdxs,
		MessageInfos:      file_sisyphus_v1_node_proto_msgTypes,
	}.Build()
	File_sisyphus_v1_node_proto = out.File
	file_sisyphus_v1_node_proto_goTypes = nil
	file_sisyphus_v1_node_proto_depIdxs = nil
}
