// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: sisyphus/v1/pool.proto

package sisyphusv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_ROLE_UNSPECIFIED Role = 0
	// May take tasks and move the blobs they need.
	Role_ROLE_WORKER Role = 1
	// May submit and inspect jobs and manage stored data.
	Role_ROLE_CLIENT Role = 2
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_WORKER",
		2: "ROLE_CLIENT",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"ROLE_WORKER":      1,
		"ROLE_CLIENT":      2,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_sisyphus_v1_pool_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_sisyphus_v1_pool_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_sisyphus_v1_pool_proto_rawDescGZIP(), []int{0}
}

type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_sisyphus_v1_pool_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_pool_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_pool_proto_rawDescGZIP(), []int{0}
}

func (x *JoinRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type JoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          Role                   `protobuf:"varint,1,opt,name=role,proto3,enum=sisyphus.v1.Role" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_sisyphus_v1_pool_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_pool_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_pool_proto_rawDescGZIP(), []int{1}
}

func (x *JoinResponse) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

type IsMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsMemberRequest) Reset() {
	*x = IsMemberRequest{}
	mi := &file_sisyphus_v1_pool_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsMemberRequest) ProtoMessage() {}

func (x *IsMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_pool_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsMemberRequest.ProtoReflect.Descriptor instead.
func (*IsMemberRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_pool_proto_rawDescGZIP(), []int{2}
}

func (x *IsMemberRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type IsMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        bool                   `protobuf:"varint,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsMemberResponse) Reset() {
	*x = IsMemberResponse{}
	mi := &file_sisyphus_v1_pool_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsMemberResponse) ProtoMessage() {}

func (x *IsMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_pool_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsMemberResponse.ProtoReflect.Descriptor instead.
func (*IsMemberResponse) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_pool_proto_rawDescGZIP(), []int{3}
}

func (x *IsMemberResponse) GetMember() bool {
	if x != nil {
		return x.Member
	}
	return false
}

type RelaysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelaysRequest) Reset() {
	*x = RelaysRequest{}
	mi := &file_sisyphus_v1_pool_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelaysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelaysRequest) ProtoMessage() {}

func (x *RelaysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_pool_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelaysRequest.ProtoReflect.Descriptor instead.
func (*RelaysRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_pool_proto_rawDescGZIP(), []int{4}
}

type RelaysResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Multiaddresses, each ending in /p2p/ and the relay's ID.
	Addresses     []string `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelaysResponse) Reset() {
	*x = RelaysResponse{}
	mi := &file_sisyphus_v1_pool_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelaysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelaysResponse) ProtoMessage() {}

func (x *RelaysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_pool_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelaysResponse.ProtoReflect.Descriptor instead.
func (*RelaysResponse) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_pool_proto_rawDescGZIP(), []int{5}
}

func (x *RelaysResponse) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type SwarmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwarmRequest) Reset() {
	*x = SwarmRequest{}
	mi := &file_sisyphus_v1_pool_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwarmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwarmRequest) ProtoMessage() {}

func (x *SwarmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_pool_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwarmRequest.ProtoReflect.Descriptor instead.
func (*SwarmRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_pool_proto_rawDescGZIP(), []int{6}
}

type SwarmResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The contents of the swarm.key file that every member's Kubo daemon
	// needs. Whoever holds it can join the network, so it is given only to
	// admitted nodes and only over their encrypted connection.
	SwarmKey string `protobuf:"bytes,1,opt,name=swarm_key,json=swarmKey,proto3" json:"swarm_key,omitempty"`
	// Addresses of the Kubo daemons on the network, each ending in
	// /p2p/<peer ID>. Those of this node's own daemon are absent if it accepts
	// no connections from outside; it is then reached through
	// TunnelService.Open.
	Addresses     []string `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwarmResponse) Reset() {
	*x = SwarmResponse{}
	mi := &file_sisyphus_v1_pool_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwarmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwarmResponse) ProtoMessage() {}

func (x *SwarmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_pool_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwarmResponse.ProtoReflect.Descriptor instead.
func (*SwarmResponse) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_pool_proto_rawDescGZIP(), []int{7}
}

func (x *SwarmResponse) GetSwarmKey() string {
	if x != nil {
		return x.SwarmKey
	}
	return ""
}

func (x *SwarmResponse) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type InviteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Role  Role                   `protobuf:"varint,1,opt,name=role,proto3,enum=sisyphus.v1.Role" json:"role,omitempty"`
	// How long the invitation can be used for. Zero means one hour.
	TtlSeconds    uint64 `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteRequest) Reset() {
	*x = InviteRequest{}
	mi := &file_sisyphus_v1_pool_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteRequest) ProtoMessage() {}

func (x *InviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_pool_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteRequest.ProtoReflect.Descriptor instead.
func (*InviteRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_pool_proto_rawDescGZIP(), []int{8}
}

func (x *InviteRequest) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

func (x *InviteRequest) GetTtlSeconds() uint64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type InviteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The invitation to hand to the joining node: this node's ID and the
	// token, as "<node ID>:<token>". The ID lets the joiner be sure it is
	// talking to the node that invited it.
	Invitation    string                 `protobuf:"bytes,1,opt,name=invitation,proto3" json:"invitation,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteResponse) Reset() {
	*x = InviteResponse{}
	mi := &file_sisyphus_v1_pool_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteResponse) ProtoMessage() {}

func (x *InviteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_pool_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteResponse.ProtoReflect.Descriptor instead.
func (*InviteResponse) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_pool_proto_rawDescGZIP(), []int{9}
}

func (x *InviteResponse) GetInvitation() string {
	if x != nil {
		return x.Invitation
	}
	return ""
}

func (x *InviteResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type ListMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersRequest) Reset() {
	*x = ListMembersRequest{}
	mi := &file_sisyphus_v1_pool_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersRequest) ProtoMessage() {}

func (x *ListMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_pool_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersRequest.ProtoReflect.Descriptor instead.
func (*ListMembersRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_pool_proto_rawDescGZIP(), []int{10}
}

type ListMembersResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Members []*Member              `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	// The IDs of the nodes this one is willing to take tasks from.
	WorksFor      []string `protobuf:"bytes,2,rep,name=works_for,json=worksFor,proto3" json:"works_for,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersResponse) Reset() {
	*x = ListMembersResponse{}
	mi := &file_sisyphus_v1_pool_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersResponse) ProtoMessage() {}

func (x *ListMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_pool_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersResponse.ProtoReflect.Descriptor instead.
func (*ListMembersResponse) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_pool_proto_rawDescGZIP(), []int{11}
}

func (x *ListMembersResponse) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *ListMembersResponse) GetWorksFor() []string {
	if x != nil {
		return x.WorksFor
	}
	return nil
}

type SetWorkForRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Willing       bool                   `protobuf:"varint,2,opt,name=willing,proto3" json:"willing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetWorkForRequest) Reset() {
	*x = SetWorkForRequest{}
	mi := &file_sisyphus_v1_pool_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetWorkForRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetWorkForRequest) ProtoMessage() {}

func (x *SetWorkForRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_pool_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetWorkForRequest.ProtoReflect.Descriptor instead.
func (*SetWorkForRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_pool_proto_rawDescGZIP(), []int{12}
}

func (x *SetWorkForRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SetWorkForRequest) GetWilling() bool {
	if x != nil {
		return x.Willing
	}
	return false
}

type SetWorkForResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetWorkForResponse) Reset() {
	*x = SetWorkForResponse{}
	mi := &file_sisyphus_v1_pool_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetWorkForResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetWorkForResponse) ProtoMessage() {}

func (x *SetWorkForResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_pool_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetWorkForResponse.ProtoReflect.Descriptor instead.
func (*SetWorkForResponse) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_pool_proto_rawDescGZIP(), []int{13}
}

type Member struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Role          Role                   `protobuf:"varint,2,opt,name=role,proto3,enum=sisyphus.v1.Role" json:"role,omitempty"`
	JoinedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_sisyphus_v1_pool_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_pool_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_pool_proto_rawDescGZIP(), []int{14}
}

func (x *Member) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Member) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

func (x *Member) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

type RemoveMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberRequest) Reset() {
	*x = RemoveMemberRequest{}
	mi := &file_sisyphus_v1_pool_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberRequest) ProtoMessage() {}

func (x *RemoveMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_pool_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveMemberRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_pool_proto_rawDescGZIP(), []int{15}
}

func (x *RemoveMemberRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type RemoveMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberResponse) Reset() {
	*x = RemoveMemberResponse{}
	mi := &file_sisyphus_v1_pool_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberResponse) ProtoMessage() {}

func (x *RemoveMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_pool_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberResponse.ProtoReflect.Descriptor instead.
func (*RemoveMemberResponse) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_pool_proto_rawDescGZIP(), []int{16}
}

type RekeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RekeyRequest) Reset() {
	*x = RekeyRequest{}
	mi := &file_sisyphus_v1_pool_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RekeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RekeyRequest) ProtoMessage() {}

func (x *RekeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_pool_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RekeyRequest.ProtoReflect.Descriptor instead.
func (*RekeyRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_pool_proto_rawDescGZIP(), []int{17}
}

type RekeyResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SwarmFingerprint string                 `protobuf:"bytes,1,opt,name=swarm_fingerprint,json=swarmFingerprint,proto3" json:"swarm_fingerprint,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RekeyResponse) Reset() {
	*x = RekeyResponse{}
	mi := &file_sisyphus_v1_pool_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RekeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RekeyResponse) ProtoMessage() {}

func (x *RekeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_pool_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RekeyResponse.ProtoReflect.Descriptor instead.
func (*RekeyResponse) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_pool_proto_rawDescGZIP(), []int{18}
}

func (x *RekeyResponse) GetSwarmFingerprint() string {
	if x != nil {
		return x.SwarmFingerprint
	}
	return ""
}

var File_sisyphus_v1_pool_proto protoreflect.FileDescriptor

const file_sisyphus_v1_pool_proto_rawDesc = "" +
	"\n" +
	"\x16sisyphus/v1/pool.proto\x12\vsisyphus.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"#\n" +
	"\vJoinRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"5\n" +
	"\fJoinResponse\x12%\n" +
	"\x04role\x18\x01 \x01(\x0e2\x11.sisyphus.v1.RoleR\x04role\"*\n" +
	"\x0fIsMemberRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"*\n" +
	"\x10IsMemberResponse\x12\x16\n" +
	"\x06member\x18\x01 \x01(\bR\x06member\"\x0f\n" +
	"\rRelaysRequest\".\n" +
	"\x0eRelaysResponse\x12\x1c\n" +
	"\taddresses\x18\x01 \x03(\tR\taddresses\"\x0e\n" +
	"\fSwarmRequest\"J\n" +
	"\rSwarmResponse\x12\x1b\n" +
	"\tswarm_key\x18\x01 \x01(\tR\bswarmKey\x12\x1c\n" +
	"\taddresses\x18\x02 \x03(\tR\taddresses\"W\n" +
	"\rInviteRequest\x12%\n" +
	"\x04role\x18\x01 \x01(\x0e2\x11.sisyphus.v1.RoleR\x04role\x12\x1f\n" +
	"\vttl_seconds\x18\x02 \x01(\x04R\n" +
	"ttlSeconds\"k\n" +
	"\x0eInviteResponse\x12\x1e\n" +
	"\n" +
	"invitation\x18\x01 \x01(\tR\n" +
	"invitation\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\x14\n" +
	"\x12ListMembersRequest\"a\n" +
	"\x13ListMembersResponse\x12-\n" +
	"\amembers\x18\x01 \x03(\v2\x13.sisyphus.v1.MemberR\amembers\x12\x1b\n" +
	"\tworks_for\x18\x02 \x03(\tR\bworksFor\"F\n" +
	"\x11SetWorkForRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\awilling\x18\x02 \x01(\bR\awilling\"\x14\n" +
	"\x12SetWorkForResponse\"\x81\x01\n" +
	"\x06Member\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12%\n" +
	"\x04role\x18\x02 \x01(\x0e2\x11.sisyphus.v1.RoleR\x04role\x127\n" +
	"\tjoined_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\".\n" +
	"\x13RemoveMemberRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"\x16\n" +
	"\x14RemoveMemberResponse\"\x0e\n" +
	"\fRekeyRequest\"<\n" +
	"\rRekeyResponse\x12+\n" +
	"\x11swarm_fingerprint\x18\x01 \x01(\tR\x10swarmFingerprint*>\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vROLE_WORKER\x10\x01\x12\x0f\n" +
	"\vROLE_CLIENT\x10\x022\x8f\x05\n" +
	"\vPoolService\x12;\n" +
	"\x04Join\x12\x18.sisyphus.v1.JoinRequest\x1a\x19.sisyphus.v1.JoinResponse\x12>\n" +
	"\x05Swarm\x12\x19.sisyphus.v1.SwarmRequest\x1a\x1a.sisyphus.v1.SwarmResponse\x12G\n" +
	"\bIsMember\x12\x1c.sisyphus.v1.IsMemberRequest\x1a\x1d.sisyphus.v1.IsMemberResponse\x12A\n" +
	"\x06Relays\x12\x1a.sisyphus.v1.RelaysRequest\x1a\x1b.sisyphus.v1.RelaysResponse\x12A\n" +
	"\x06Invite\x12\x1a.sisyphus.v1.InviteRequest\x1a\x1b.sisyphus.v1.InviteResponse\x12P\n" +
	"\vListMembers\x12\x1f.sisyphus.v1.ListMembersRequest\x1a .sisyphus.v1.ListMembersResponse\x12S\n" +
	"\fRemoveMember\x12 .sisyphus.v1.RemoveMemberRequest\x1a!.sisyphus.v1.RemoveMemberResponse\x12M\n" +
	"\n" +
	"SetWorkFor\x12\x1e.sisyphus.v1.SetWorkForRequest\x1a\x1f.sisyphus.v1.SetWorkForResponse\x12>\n" +
	"\x05Rekey\x12\x19.sisyphus.v1.RekeyRequest\x1a\x1a.sisyphus.v1.RekeyResponseBOZMgithub.com/sisyphus-network/Sisyphus/packages/protocol/sisyphus/v1;sisyphusv1b\x06proto3"

var (
	file_sisyphus_v1_pool_proto_rawDescOnce sync.Once
	file_sisyphus_v1_pool_proto_rawDescData []byte
)

func file_sisyphus_v1_pool_proto_rawDescGZIP() []byte {
	file_sisyphus_v1_pool_proto_rawDescOnce.Do(func() {
		file_sisyphus_v1_pool_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sisyphus_v1_pool_proto_rawDesc), len(file_sisyphus_v1_pool_proto_rawDesc)))
	})
	return file_sisyphus_v1_pool_proto_rawDescData
}

var file_sisyphus_v1_pool_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sisyphus_v1_pool_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_sisyphus_v1_pool_proto_goTypes = []any{
	(Role)(0),                     // 0: sisyphus.v1.Role
	(*JoinRequest)(nil),           // 1: sisyphus.v1.JoinRequest
	(*JoinResponse)(nil),          // 2: sisyphus.v1.JoinResponse
	(*IsMemberRequest)(nil),       // 3: sisyphus.v1.IsMemberRequest
	(*IsMemberResponse)(nil),      // 4: sisyphus.v1.IsMemberResponse
	(*RelaysRequest)(nil),         // 5: sisyphus.v1.RelaysRequest
	(*RelaysResponse)(nil),        // 6: sisyphus.v1.RelaysResponse
	(*SwarmRequest)(nil),          // 7: sisyphus.v1.SwarmRequest
	(*SwarmResponse)(nil),         // 8: sisyphus.v1.SwarmResponse
	(*InviteRequest)(nil),         // 9: sisyphus.v1.InviteRequest
	(*InviteResponse)(nil),        // 10: sisyphus.v1.InviteResponse
	(*ListMembersRequest)(nil),    // 11: sisyphus.v1.ListMembersRequest
	(*ListMembersResponse)(nil),   // 12: sisyphus.v1.ListMembersResponse
	(*SetWorkForRequest)(nil),     // 13: sisyphus.v1.SetWorkForRequest
	(*SetWorkForResponse)(nil),    // 14: sisyphus.v1.SetWorkForResponse
	(*Member)(nil),                // 15: sisyphus.v1.Member
	(*RemoveMemberRequest)(nil),   // 16: sisyphus.v1.RemoveMemberRequest
	(*RemoveMemberResponse)(nil),  // 17: sisyphus.v1.RemoveMemberResponse
	(*RekeyRequest)(nil),          // 18: sisyphus.v1.RekeyRequest
	(*RekeyResponse)(nil),         // 19: sisyphus.v1.RekeyResponse
	(*timestamppb.Timestamp)(nil), // 20: google.protobuf.Timestamp
}
var file_sisyphus_v1_pool_proto_depIdxs = []int32{
	0,  // 0: sisyphus.v1.JoinResponse.role:type_name -> sisyphus.v1.Role
	0,  // 1: sisyphus.v1.InviteRequest.role:type_name -> sisyphus.v1.Role
	20, // 2: sisyphus.v1.InviteResponse.expires_at:type_name -> google.protobuf.Timestamp
	15, // 3: sisyphus.v1.ListMembersResponse.members:type_name -> sisyphus.v1.Member
	0,  // 4: sisyphus.v1.Member.role:type_name -> sisyphus.v1.Role
	20, // 5: sisyphus.v1.Member.joined_at:type_name -> google.protobuf.Timestamp
	1,  // 6: sisyphus.v1.PoolService.Join:input_type -> sisyphus.v1.JoinRequest
	7,  // 7: sisyphus.v1.PoolService.Swarm:input_type -> sisyphus.v1.SwarmRequest
	3,  // 8: sisyphus.v1.PoolService.IsMember:input_type -> sisyphus.v1.IsMemberRequest
	5,  // 9: sisyphus.v1.PoolService.Relays:input_type -> sisyphus.v1.RelaysRequest
	9,  // 10: sisyphus.v1.PoolService.Invite:input_type -> sisyphus.v1.InviteRequest
	11, // 11: sisyphus.v1.PoolService.ListMembers:input_type -> sisyphus.v1.ListMembersRequest
	16, // 12: sisyphus.v1.PoolService.RemoveMember:input_type -> sisyphus.v1.RemoveMemberRequest
	13, // 13: sisyphus.v1.PoolService.SetWorkFor:input_type -> sisyphus.v1.SetWorkForRequest
	18, // 14: sisyphus.v1.PoolService.Rekey:input_type -> sisyphus.v1.RekeyRequest
	2,  // 15: sisyphus.v1.PoolService.Join:output_type -> sisyphus.v1.JoinResponse
	8,  // 16: sisyphus.v1.PoolService.Swarm:output_type -> sisyphus.v1.SwarmResponse
	4,  // 17: sisyphus.v1.PoolService.IsMember:output_type -> sisyphus.v1.IsMemberResponse
	6,  // 18: sisyphus.v1.PoolService.Relays:output_type -> sisyphus.v1.RelaysResponse
	10, // 19: sisyphus.v1.PoolService.Invite:output_type -> sisyphus.v1.InviteResponse
	12, // 20: sisyphus.v1.PoolService.ListMembers:output_type -> sisyphus.v1.ListMembersResponse
	17, // 21: sisyphus.v1.PoolService.RemoveMember:output_type -> sisyphus.v1.RemoveMemberResponse
	14, // 22: sisyphus.v1.PoolService.SetWorkFor:output_type -> sisyphus.v1.SetWorkForResponse
	19, // 23: sisyphus.v1.PoolService.Rekey:output_type -> sisyphus.v1.RekeyResponse
	15, // [15:24] is the sub-list for method output_type
	6,  // [6:15] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_sisyphus_v1_pool_proto_init() }
func file_sisyphus_v1_pool_proto_init() {
	if File_sisyphus_v1_pool_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sisyphus_v1_pool_proto_rawDesc), len(file_sisyphus_v1_pool_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sisyphus_v1_pool_proto_goTypes,
		DependencyIndexes: file_sisyphus_v1_pool_proto_depIdxs,
		EnumInfos:         file_sisyphus_v1_pool_proto_enumTypes,
		MessageInfos:      file_sisyphus_v1_pool_proto_msgTypes,
	}.Build()
	File_sisyphus_v1_pool_proto = out.File
	file_sisyphus_v1_pool_proto_goTypes = nil
	file_sisyphus_v1_pool_proto_depIdxs = nil
}
