// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.2
// source: sisyphus/v1/tunnel.proto

package sisyphusv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TunnelService_Open_FullMethodName = "/sisyphus.v1.TunnelService/Open"
)

// TunnelServiceClient is the client API for TunnelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TunnelService carries connections to services that a node keeps to
// itself, inside the one connection its members already have with it. It is
// how a node behind a firewall or NAT reaches what would otherwise need a
// port of its own opened on the node it is talking to.
type TunnelServiceClient interface {
	// Open carries one connection: bytes sent are written to the service and
	// what the service writes is sent back, until either end closes. The
	// first message names the service and may carry bytes as well.
	Open(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TunnelData, TunnelData], error)
}

type tunnelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTunnelServiceClient(cc grpc.ClientConnInterface) TunnelServiceClient {
	return &tunnelServiceClient{cc}
}

func (c *tunnelServiceClient) Open(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TunnelData, TunnelData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TunnelService_ServiceDesc.Streams[0], TunnelService_Open_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TunnelData, TunnelData]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TunnelService_OpenClient = grpc.BidiStreamingClient[TunnelData, TunnelData]

// TunnelServiceServer is the server API for TunnelService service.
// All implementations must embed UnimplementedTunnelServiceServer
// for forward compatibility.
//
// TunnelService carries connections to services that a node keeps to
// itself, inside the one connection its members already have with it. It is
// how a node behind a firewall or NAT reaches what would otherwise need a
// port of its own opened on the node it is talking to.
type TunnelServiceServer interface {
	// Open carries one connection: bytes sent are written to the service and
	// what the service writes is sent back, until either end closes. The
	// first message names the service and may carry bytes as well.
	Open(grpc.BidiStreamingServer[TunnelData, TunnelData]) error
	mustEmbedUnimplementedTunnelServiceServer()
}

// UnimplementedTunnelServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTunnelServiceServer struct{}

func (UnimplementedTunnelServiceServer) Open(grpc.BidiStreamingServer[TunnelData, TunnelData]) error {
	return status.Error(codes.Unimplemented, "method Open not implemented")
}
func (UnimplementedTunnelServiceServer) mustEmbedUnimplementedTunnelServiceServer() {}
func (UnimplementedTunnelServiceServer) testEmbeddedByValue()                       {}

// UnsafeTunnelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TunnelServiceServer will
// result in compilation errors.
type UnsafeTunnelServiceServer interface {
	mustEmbedUnimplementedTunnelServiceServer()
}

func RegisterTunnelServiceServer(s grpc.ServiceRegistrar, srv TunnelServiceServer) {
	// If the following call panics, it indicates UnimplementedTunnelServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TunnelService_ServiceDesc, srv)
}

func _TunnelService_Open_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TunnelServiceServer).Open(&grpc.GenericServerStream[TunnelData, TunnelData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TunnelService_OpenServer = grpc.BidiStreamingServer[TunnelData, TunnelData]

// TunnelService_ServiceDesc is the grpc.ServiceDesc for TunnelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TunnelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sisyphus.v1.TunnelService",
	HandlerType: (*TunnelServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Open",
			Handler:       _TunnelService_Open_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "sisyphus/v1/tunnel.proto",
}
