// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: sisyphus/v1/types.proto

package sisyphusv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScheduleMode int32

const (
	ScheduleMode_SCHEDULE_MODE_UNSPECIFIED ScheduleMode = 0
	// Split the workload into tasks and spread them across workers.
	ScheduleMode_SCHEDULE_MODE_DISTRIBUTED ScheduleMode = 1
	// Send the whole workload to one worker as a single task.
	ScheduleMode_SCHEDULE_MODE_FULL_WORKER ScheduleMode = 2
)

// Enum value maps for ScheduleMode.
var (
	ScheduleMode_name = map[int32]string{
		0: "SCHEDULE_MODE_UNSPECIFIED",
		1: "SCHEDULE_MODE_DISTRIBUTED",
		2: "SCHEDULE_MODE_FULL_WORKER",
	}
	ScheduleMode_value = map[string]int32{
		"SCHEDULE_MODE_UNSPECIFIED": 0,
		"SCHEDULE_MODE_DISTRIBUTED": 1,
		"SCHEDULE_MODE_FULL_WORKER": 2,
	}
)

func (x ScheduleMode) Enum() *ScheduleMode {
	p := new(ScheduleMode)
	*p = x
	return p
}

func (x ScheduleMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScheduleMode) Descriptor() protoreflect.EnumDescriptor {
	return file_sisyphus_v1_types_proto_enumTypes[0].Descriptor()
}

func (ScheduleMode) Type() protoreflect.EnumType {
	return &file_sisyphus_v1_types_proto_enumTypes[0]
}

func (x ScheduleMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScheduleMode.Descriptor instead.
func (ScheduleMode) EnumDescriptor() ([]byte, []int) {
	return file_sisyphus_v1_types_proto_rawDescGZIP(), []int{0}
}

type JobState int32

const (
	JobState_JOB_STATE_UNSPECIFIED JobState = 0
	JobState_JOB_STATE_PENDING     JobState = 1
	JobState_JOB_STATE_RUNNING     JobState = 2
	JobState_JOB_STATE_SUCCEEDED   JobState = 3
	JobState_JOB_STATE_FAILED      JobState = 4
)

// Enum value maps for JobState.
var (
	JobState_name = map[int32]string{
		0: "JOB_STATE_UNSPECIFIED",
		1: "JOB_STATE_PENDING",
		2: "JOB_STATE_RUNNING",
		3: "JOB_STATE_SUCCEEDED",
		4: "JOB_STATE_FAILED",
	}
	JobState_value = map[string]int32{
		"JOB_STATE_UNSPECIFIED": 0,
		"JOB_STATE_PENDING":     1,
		"JOB_STATE_RUNNING":     2,
		"JOB_STATE_SUCCEEDED":   3,
		"JOB_STATE_FAILED":      4,
	}
)

func (x JobState) Enum() *JobState {
	p := new(JobState)
	*p = x
	return p
}

func (x JobState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobState) Descriptor() protoreflect.EnumDescriptor {
	return file_sisyphus_v1_types_proto_enumTypes[1].Descriptor()
}

func (JobState) Type() protoreflect.EnumType {
	return &file_sisyphus_v1_types_proto_enumTypes[1]
}

func (x JobState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobState.Descriptor instead.
func (JobState) EnumDescriptor() ([]byte, []int) {
	return file_sisyphus_v1_types_proto_rawDescGZIP(), []int{1}
}

type TaskState int32

const (
	TaskState_TASK_STATE_UNSPECIFIED TaskState = 0
	TaskState_TASK_STATE_PENDING     TaskState = 1
	TaskState_TASK_STATE_RUNNING     TaskState = 2
	TaskState_TASK_STATE_SUCCEEDED   TaskState = 3
	TaskState_TASK_STATE_FAILED      TaskState = 4
)

// Enum value maps for TaskState.
var (
	TaskState_name = map[int32]string{
		0: "TASK_STATE_UNSPECIFIED",
		1: "TASK_STATE_PENDING",
		2: "TASK_STATE_RUNNING",
		3: "TASK_STATE_SUCCEEDED",
		4: "TASK_STATE_FAILED",
	}
	TaskState_value = map[string]int32{
		"TASK_STATE_UNSPECIFIED": 0,
		"TASK_STATE_PENDING":     1,
		"TASK_STATE_RUNNING":     2,
		"TASK_STATE_SUCCEEDED":   3,
		"TASK_STATE_FAILED":      4,
	}
)

func (x TaskState) Enum() *TaskState {
	p := new(TaskState)
	*p = x
	return p
}

func (x TaskState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskState) Descriptor() protoreflect.EnumDescriptor {
	return file_sisyphus_v1_types_proto_enumTypes[2].Descriptor()
}

func (TaskState) Type() protoreflect.EnumType {
	return &file_sisyphus_v1_types_proto_enumTypes[2]
}

func (x TaskState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskState.Descriptor instead.
func (TaskState) EnumDescriptor() ([]byte, []int) {
	return file_sisyphus_v1_types_proto_rawDescGZIP(), []int{2}
}

// What a node offers to a pool.
type NodeCapabilities struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Hostname    string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os          string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Arch        string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	CpuCores    uint32                 `protobuf:"varint,4,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemoryBytes uint64                 `protobuf:"varint,5,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	// How many tasks the owner allows this node to run at once.
	TaskSlots uint32 `protobuf:"varint,6,opt,name=task_slots,json=taskSlots,proto3" json:"task_slots,omitempty"`
	// Names of the workloads this node can execute.
	Workloads     []string `protobuf:"bytes,7,rep,name=workloads,proto3" json:"workloads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeCapabilities) Reset() {
	*x = NodeCapabilities{}
	mi := &file_sisyphus_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeCapabilities) ProtoMessage() {}

func (x *NodeCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeCapabilities.ProtoReflect.Descriptor instead.
func (*NodeCapabilities) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *NodeCapabilities) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *NodeCapabilities) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *NodeCapabilities) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *NodeCapabilities) GetCpuCores() uint32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *NodeCapabilities) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *NodeCapabilities) GetTaskSlots() uint32 {
	if x != nil {
		return x.TaskSlots
	}
	return 0
}

func (x *NodeCapabilities) GetWorkloads() []string {
	if x != nil {
		return x.Workloads
	}
	return nil
}

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Capabilities  *NodeCapabilities      `protobuf:"bytes,2,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	RunningTasks  uint32                 `protobuf:"varint,3,opt,name=running_tasks,json=runningTasks,proto3" json:"running_tasks,omitempty"`
	ConnectedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	LastSeenAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_sisyphus_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *NodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInfo) GetCapabilities() *NodeCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *NodeInfo) GetRunningTasks() uint32 {
	if x != nil {
		return x.RunningTasks
	}
	return 0
}

func (x *NodeInfo) GetConnectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConnectedAt
	}
	return nil
}

func (x *NodeInfo) GetLastSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenAt
	}
	return nil
}

type JobSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of a workload known to the coordinator and its workers.
	Workload string `protobuf:"bytes,1,opt,name=workload,proto3" json:"workload,omitempty"`
	// Workload-defined parameters. Built-in workloads use JSON.
	Params []byte       `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	Mode   ScheduleMode `protobuf:"varint,3,opt,name=mode,proto3,enum=sisyphus.v1.ScheduleMode" json:"mode,omitempty"`
	// Distributed mode only: how many tasks to split into. Zero means one
	// task per worker slot connected at submission time.
	MaxTasks      uint32 `protobuf:"varint,4,opt,name=max_tasks,json=maxTasks,proto3" json:"max_tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobSpec) Reset() {
	*x = JobSpec{}
	mi := &file_sisyphus_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSpec) ProtoMessage() {}

func (x *JobSpec) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSpec.ProtoReflect.Descriptor instead.
func (*JobSpec) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *JobSpec) GetWorkload() string {
	if x != nil {
		return x.Workload
	}
	return ""
}

func (x *JobSpec) GetParams() []byte {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *JobSpec) GetMode() ScheduleMode {
	if x != nil {
		return x.Mode
	}
	return ScheduleMode_SCHEDULE_MODE_UNSPECIFIED
}

func (x *JobSpec) GetMaxTasks() uint32 {
	if x != nil {
		return x.MaxTasks
	}
	return 0
}

type Task struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	TaskId string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Index  uint32                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	State  TaskState              `protobuf:"varint,3,opt,name=state,proto3,enum=sisyphus.v1.TaskState" json:"state,omitempty"`
	// Number of times this task has been handed to a worker.
	Attempt uint32 `protobuf:"varint,4,opt,name=attempt,proto3" json:"attempt,omitempty"`
	// Node currently or most recently running the task.
	NodeId string `protobuf:"bytes,5,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Reason for the most recent failed attempt, if any.
	Error         string `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_sisyphus_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *Task) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Task) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Task) GetState() TaskState {
	if x != nil {
		return x.State
	}
	return TaskState_TASK_STATE_UNSPECIFIED
}

func (x *Task) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *Task) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Task) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Job struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	JobId string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Spec  *JobSpec               `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	State JobState               `protobuf:"varint,3,opt,name=state,proto3,enum=sisyphus.v1.JobState" json:"state,omitempty"`
	Tasks []*Task                `protobuf:"bytes,4,rep,name=tasks,proto3" json:"tasks,omitempty"`
	// Aggregated result, set once the job has succeeded.
	Result        []byte                 `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_sisyphus_v1_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_v1_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_sisyphus_v1_types_proto_rawDescGZIP(), []int{4}
}

func (x *Job) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Job) GetSpec() *JobSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Job) GetState() JobState {
	if x != nil {
		return x.State
	}
	return JobState_JOB_STATE_UNSPECIFIED
}

func (x *Job) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *Job) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Job) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Job) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Job) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

var File_sisyphus_v1_types_proto protoreflect.FileDescriptor

const file_sisyphus_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x17sisyphus/v1/types.proto\x12\vsisyphus.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcf\x01\n" +
	"\x10NodeCapabilities\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12\x1b\n" +
	"\tcpu_cores\x18\x04 \x01(\rR\bcpuCores\x12!\n" +
	"\fmemory_bytes\x18\x05 \x01(\x04R\vmemoryBytes\x12\x1d\n" +
	"\n" +
	"task_slots\x18\x06 \x01(\rR\ttaskSlots\x12\x1c\n" +
	"\tworkloads\x18\a \x03(\tR\tworkloads\"\x88\x02\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12A\n" +
	"\fcapabilities\x18\x02 \x01(\v2\x1d.sisyphus.v1.NodeCapabilitiesR\fcapabilities\x12#\n" +
	"\rrunning_tasks\x18\x03 \x01(\rR\frunningTasks\x12=\n" +
	"\fconnected_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vconnectedAt\x12<\n" +
	"\flast_seen_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSeenAt\"\x89\x01\n" +
	"\aJobSpec\x12\x1a\n" +
	"\bworkload\x18\x01 \x01(\tR\bworkload\x12\x16\n" +
	"\x06params\x18\x02 \x01(\fR\x06params\x12-\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x19.sisyphus.v1.ScheduleModeR\x04mode\x12\x1b\n" +
	"\tmax_tasks\x18\x04 \x01(\rR\bmaxTasks\"\xac\x01\n" +
	"\x04Task\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05index\x18\x02 \x01(\rR\x05index\x12,\n" +
	"\x05state\x18\x03 \x01(\x0e2\x16.sisyphus.v1.TaskStateR\x05state\x12\x18\n" +
	"\aattempt\x18\x04 \x01(\rR\aattempt\x12\x17\n" +
	"\anode_id\x18\x05 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"\xc2\x02\n" +
	"\x03Job\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12(\n" +
	"\x04spec\x18\x02 \x01(\v2\x14.sisyphus.v1.JobSpecR\x04spec\x12+\n" +
	"\x05state\x18\x03 \x01(\x0e2\x15.sisyphus.v1.JobStateR\x05state\x12'\n" +
	"\x05tasks\x18\x04 \x03(\v2\x11.sisyphus.v1.TaskR\x05tasks\x12\x16\n" +
	"\x06result\x18\x05 \x01(\fR\x06result\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12;\n" +
	"\vfinished_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt*k\n" +
	"\fScheduleMode\x12\x1d\n" +
	"\x19SCHEDULE_MODE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19SCHEDULE_MODE_DISTRIBUTED\x10\x01\x12\x1d\n" +
	"\x19SCHEDULE_MODE_FULL_WORKER\x10\x02*\x82\x01\n" +
	"\bJobState\x12\x19\n" +
	"\x15JOB_STATE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11JOB_STATE_PENDING\x10\x01\x12\x15\n" +
	"\x11JOB_STATE_RUNNING\x10\x02\x12\x17\n" +
	"\x13JOB_STATE_SUCCEEDED\x10\x03\x12\x14\n" +
	"\x10JOB_STATE_FAILED\x10\x04*\x88\x01\n" +
	"\tTaskState\x12\x1a\n" +
	"\x16TASK_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TASK_STATE_PENDING\x10\x01\x12\x16\n" +
	"\x12TASK_STATE_RUNNING\x10\x02\x12\x18\n" +
	"\x14TASK_STATE_SUCCEEDED\x10\x03\x12\x15\n" +
	"\x11TASK_STATE_FAILED\x10\x04BEZCgithub.com/excho0/Sisyphus/packages/protocol/sisyphus/v1;sisyphusv1b\x06proto3"

var (
	file_sisyphus_v1_types_proto_rawDescOnce sync.Once
	file_sisyphus_v1_types_proto_rawDescData []byte
)

func file_sisyphus_v1_types_proto_rawDescGZIP() []byte {
	file_sisyphus_v1_types_proto_rawDescOnce.Do(func() {
		file_sisyphus_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sisyphus_v1_types_proto_rawDesc), len(file_sisyphus_v1_types_proto_rawDesc)))
	})
	return file_sisyphus_v1_types_proto_rawDescData
}

var file_sisyphus_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_sisyphus_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_sisyphus_v1_types_proto_goTypes = []any{
	(ScheduleMode)(0),             // 0: sisyphus.v1.ScheduleMode
	(JobState)(0),                 // 1: sisyphus.v1.JobState
	(TaskState)(0),                // 2: sisyphus.v1.TaskState
	(*NodeCapabilities)(nil),      // 3: sisyphus.v1.NodeCapabilities
	(*NodeInfo)(nil),              // 4: sisyphus.v1.NodeInfo
	(*JobSpec)(nil),               // 5: sisyphus.v1.JobSpec
	(*Task)(nil),                  // 6: sisyphus.v1.Task
	(*Job)(nil),                   // 7: sisyphus.v1.Job
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_sisyphus_v1_types_proto_depIdxs = []int32{
	3,  // 0: sisyphus.v1.NodeInfo.capabilities:type_name -> sisyphus.v1.NodeCapabilities
	8,  // 1: sisyphus.v1.NodeInfo.connected_at:type_name -> google.protobuf.Timestamp
	8,  // 2: sisyphus.v1.NodeInfo.last_seen_at:type_name -> google.protobuf.Timestamp
	0,  // 3: sisyphus.v1.JobSpec.mode:type_name -> sisyphus.v1.ScheduleMode
	2,  // 4: sisyphus.v1.Task.state:type_name -> sisyphus.v1.TaskState
	5,  // 5: sisyphus.v1.Job.spec:type_name -> sisyphus.v1.JobSpec
	1,  // 6: sisyphus.v1.Job.state:type_name -> sisyphus.v1.JobState
	6,  // 7: sisyphus.v1.Job.tasks:type_name -> sisyphus.v1.Task
	8,  // 8: sisyphus.v1.Job.created_at:type_name -> google.protobuf.Timestamp
	8,  // 9: sisyphus.v1.Job.finished_at:type_name -> google.protobuf.Timestamp
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_sisyphus_v1_types_proto_init() }
func file_sisyphus_v1_types_proto_init() {
	if File_sisyphus_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sisyphus_v1_types_proto_rawDesc), len(file_sisyphus_v1_types_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sisyphus_v1_types_proto_goTypes,
		DependencyIndexes: file_sisyphus_v1_types_proto_depIdxs,
		EnumInfos:         file_sisyphus_v1_types_proto_enumTypes,
		MessageInfos:      file_sisyphus_v1_types_proto_msgTypes,
	}.Build()
	File_sisyphus_v1_types_proto = out.File
	file_sisyphus_v1_types_proto_goTypes = nil
	file_sisyphus_v1_types_proto_depIdxs = nil
}
