// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: sisyphus/node/v1/node.proto

package nodev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeService_GetNodeInfo_FullMethodName               = "/sisyphus.node.v1.NodeService/GetNodeInfo"
	NodeService_ListPeers_FullMethodName                 = "/sisyphus.node.v1.NodeService/ListPeers"
	NodeService_WatchPeers_FullMethodName                = "/sisyphus.node.v1.NodeService/WatchPeers"
	NodeService_GetBootstrapPeers_FullMethodName         = "/sisyphus.node.v1.NodeService/GetBootstrapPeers"
	NodeService_SetBootstrapPeers_FullMethodName         = "/sisyphus.node.v1.NodeService/SetBootstrapPeers"
	NodeService_ConnectPeer_FullMethodName               = "/sisyphus.node.v1.NodeService/ConnectPeer"
	NodeService_SetPeerComputeTrust_FullMethodName       = "/sisyphus.node.v1.NodeService/SetPeerComputeTrust"
	NodeService_SetPeerComputePermissions_FullMethodName = "/sisyphus.node.v1.NodeService/SetPeerComputePermissions"
	NodeService_ListWorkers_FullMethodName               = "/sisyphus.node.v1.NodeService/ListWorkers"
	NodeService_SubmitJob_FullMethodName                 = "/sisyphus.node.v1.NodeService/SubmitJob"
	NodeService_GetJob_FullMethodName                    = "/sisyphus.node.v1.NodeService/GetJob"
	NodeService_ListJobs_FullMethodName                  = "/sisyphus.node.v1.NodeService/ListJobs"
	NodeService_WatchJobs_FullMethodName                 = "/sisyphus.node.v1.NodeService/WatchJobs"
	NodeService_CancelJob_FullMethodName                 = "/sisyphus.node.v1.NodeService/CancelJob"
	NodeService_WatchJobEvents_FullMethodName            = "/sisyphus.node.v1.NodeService/WatchJobEvents"
	NodeService_GetModelConfig_FullMethodName            = "/sisyphus.node.v1.NodeService/GetModelConfig"
	NodeService_SetModelConfig_FullMethodName            = "/sisyphus.node.v1.NodeService/SetModelConfig"
	NodeService_ListModels_FullMethodName                = "/sisyphus.node.v1.NodeService/ListModels"
	NodeService_Ask_FullMethodName                       = "/sisyphus.node.v1.NodeService/Ask"
	NodeService_ListChats_FullMethodName                 = "/sisyphus.node.v1.NodeService/ListChats"
	NodeService_GetChat_FullMethodName                   = "/sisyphus.node.v1.NodeService/GetChat"
	NodeService_DeleteChat_FullMethodName                = "/sisyphus.node.v1.NodeService/DeleteChat"
	NodeService_StoreFile_FullMethodName                 = "/sisyphus.node.v1.NodeService/StoreFile"
	NodeService_FetchFile_FullMethodName                 = "/sisyphus.node.v1.NodeService/FetchFile"
	NodeService_ListFiles_FullMethodName                 = "/sisyphus.node.v1.NodeService/ListFiles"
	NodeService_RemoveFile_FullMethodName                = "/sisyphus.node.v1.NodeService/RemoveFile"
	NodeService_CreateInvitation_FullMethodName          = "/sisyphus.node.v1.NodeService/CreateInvitation"
	NodeService_ListMembers_FullMethodName               = "/sisyphus.node.v1.NodeService/ListMembers"
	NodeService_RemoveMember_FullMethodName              = "/sisyphus.node.v1.NodeService/RemoveMember"
	NodeService_JoinPool_FullMethodName                  = "/sisyphus.node.v1.NodeService/JoinPool"
)

// NodeServiceClient is the client API for NodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeServiceClient interface {
	GetNodeInfo(ctx context.Context, in *GetNodeInfoRequest, opts ...grpc.CallOption) (*GetNodeInfoResponse, error)
	ListPeers(ctx context.Context, in *ListPeersRequest, opts ...grpc.CallOption) (*ListPeersResponse, error)
	WatchPeers(ctx context.Context, in *WatchPeersRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListPeersResponse], error)
	GetBootstrapPeers(ctx context.Context, in *GetBootstrapPeersRequest, opts ...grpc.CallOption) (*GetBootstrapPeersResponse, error)
	SetBootstrapPeers(ctx context.Context, in *SetBootstrapPeersRequest, opts ...grpc.CallOption) (*SetBootstrapPeersResponse, error)
	ConnectPeer(ctx context.Context, in *ConnectPeerRequest, opts ...grpc.CallOption) (*ConnectPeerResponse, error)
	// SetPeerComputeTrust sets both sides of trust in a peer at once: whether
	// this node gives it work and whether this node takes work from it.
	SetPeerComputeTrust(ctx context.Context, in *SetPeerComputeTrustRequest, opts ...grpc.CallOption) (*SetPeerComputeTrustResponse, error)
	// SetPeerComputePermissions sets the two sides separately.
	SetPeerComputePermissions(ctx context.Context, in *SetPeerComputePermissionsRequest, opts ...grpc.CallOption) (*SetPeerComputePermissionsResponse, error)
	// ListWorkers lists the nodes connected to this one as its workers.
	ListWorkers(ctx context.Context, in *ListWorkersRequest, opts ...grpc.CallOption) (*ListWorkersResponse, error)
	// SubmitJob gives the pool a job and returns it as it stands at once.
	SubmitJob(ctx context.Context, in *SubmitJobRequest, opts ...grpc.CallOption) (*SubmitJobResponse, error)
	GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error)
	// ListJobs lists the jobs this node has on record, newest first.
	ListJobs(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error)
	// WatchJobs sends that list at once and again, in full, whenever any job
	// changes, with a revision that counts up from one.
	WatchJobs(ctx context.Context, in *WatchJobsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListJobsResponse], error)
	// CancelJob stops a job that has not finished.
	CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*CancelJobResponse, error)
	// WatchJobEvents sends what has happened to a job, from the event after
	// the one named, and goes on as more happens until the job has finished:
	// the steps of its life and the lines its tasks log.
	WatchJobEvents(ctx context.Context, in *WatchJobEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobEvent], error)
	// GetModelConfig says which model the node plans with. It never returns
	// the service's key, only whether one is set.
	GetModelConfig(ctx context.Context, in *GetModelConfigRequest, opts ...grpc.CallOption) (*ModelConfig, error)
	SetModelConfig(ctx context.Context, in *SetModelConfigRequest, opts ...grpc.CallOption) (*ModelConfig, error)
	// ListModels asks the configured service which models it offers.
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
	// Ask puts a question to the planner, in a new conversation or an
	// existing one, and sends what it does as it does it: what the model
	// says, each job it runs, and at the end the event "done".
	Ask(ctx context.Context, in *AskRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AskEvent], error)
	// ListChats lists the conversations on record, newest first.
	ListChats(ctx context.Context, in *ListChatsRequest, opts ...grpc.CallOption) (*ListChatsResponse, error)
	GetChat(ctx context.Context, in *GetChatRequest, opts ...grpc.CallOption) (*GetChatResponse, error)
	DeleteChat(ctx context.Context, in *DeleteChatRequest, opts ...grpc.CallOption) (*DeleteChatResponse, error)
	// StoreFile puts a file in the pool's store and keeps it there until it
	// is removed. The first message names it; every message may carry data.
	// The answer has its CID, which is what a job is given as its input.
	StoreFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StoreFileRequest, File], error)
	// FetchFile sends what is stored under a CID: a file stored here, or
	// something a job produced.
	FetchFile(ctx context.Context, in *FetchFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FetchFileResponse], error)
	// ListFiles lists the files stored through StoreFile, newest first.
	ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error)
	// RemoveFile stops keeping a file. Its content goes when the store is
	// next cleared of what nothing holds.
	RemoveFile(ctx context.Context, in *RemoveFileRequest, opts ...grpc.CallOption) (*RemoveFileResponse, error)
	// CreateInvitation makes an invitation for another machine to join the
	// pool with: as a worker, or as a client that may only submit jobs. It
	// works once.
	CreateInvitation(ctx context.Context, in *CreateInvitationRequest, opts ...grpc.CallOption) (*CreateInvitationResponse, error)
	// ListMembers lists the nodes admitted to the pool.
	ListMembers(ctx context.Context, in *ListMembersRequest, opts ...grpc.CallOption) (*ListMembersResponse, error)
	// RemoveMember takes a node out of the pool and disconnects it.
	RemoveMember(ctx context.Context, in *RemoveMemberRequest, opts ...grpc.CallOption) (*RemoveMemberResponse, error)
	// JoinPool has this node join another node's pool with an invitation
	// from it, and start working for it, beside whatever else it is doing.
	// It is what a node started with --join does, without the restart.
	JoinPool(ctx context.Context, in *JoinPoolRequest, opts ...grpc.CallOption) (*JoinPoolResponse, error)
}

type nodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeServiceClient(cc grpc.ClientConnInterface) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) GetNodeInfo(ctx context.Context, in *GetNodeInfoRequest, opts ...grpc.CallOption) (*GetNodeInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeInfoResponse)
	err := c.cc.Invoke(ctx, NodeService_GetNodeInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) ListPeers(ctx context.Context, in *ListPeersRequest, opts ...grpc.CallOption) (*ListPeersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPeersResponse)
	err := c.cc.Invoke(ctx, NodeService_ListPeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) WatchPeers(ctx context.Context, in *WatchPeersRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListPeersResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[0], NodeService_WatchPeers_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchPeersRequest, ListPeersResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_WatchPeersClient = grpc.ServerStreamingClient[ListPeersResponse]

func (c *nodeServiceClient) GetBootstrapPeers(ctx context.Context, in *GetBootstrapPeersRequest, opts ...grpc.CallOption) (*GetBootstrapPeersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBootstrapPeersResponse)
	err := c.cc.Invoke(ctx, NodeService_GetBootstrapPeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) SetBootstrapPeers(ctx context.Context, in *SetBootstrapPeersRequest, opts ...grpc.CallOption) (*SetBootstrapPeersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetBootstrapPeersResponse)
	err := c.cc.Invoke(ctx, NodeService_SetBootstrapPeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) ConnectPeer(ctx context.Context, in *ConnectPeerRequest, opts ...grpc.CallOption) (*ConnectPeerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectPeerResponse)
	err := c.cc.Invoke(ctx, NodeService_ConnectPeer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) SetPeerComputeTrust(ctx context.Context, in *SetPeerComputeTrustRequest, opts ...grpc.CallOption) (*SetPeerComputeTrustResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPeerComputeTrustResponse)
	err := c.cc.Invoke(ctx, NodeService_SetPeerComputeTrust_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) SetPeerComputePermissions(ctx context.Context, in *SetPeerComputePermissionsRequest, opts ...grpc.CallOption) (*SetPeerComputePermissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPeerComputePermissionsResponse)
	err := c.cc.Invoke(ctx, NodeService_SetPeerComputePermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) ListWorkers(ctx context.Context, in *ListWorkersRequest, opts ...grpc.CallOption) (*ListWorkersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkersResponse)
	err := c.cc.Invoke(ctx, NodeService_ListWorkers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) SubmitJob(ctx context.Context, in *SubmitJobRequest, opts ...grpc.CallOption) (*SubmitJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitJobResponse)
	err := c.cc.Invoke(ctx, NodeService_SubmitJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobResponse)
	err := c.cc.Invoke(ctx, NodeService_GetJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) ListJobs(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListJobsResponse)
	err := c.cc.Invoke(ctx, NodeService_ListJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) WatchJobs(ctx context.Context, in *WatchJobsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListJobsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[1], NodeService_WatchJobs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchJobsRequest, ListJobsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_WatchJobsClient = grpc.ServerStreamingClient[ListJobsResponse]

func (c *nodeServiceClient) CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*CancelJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelJobResponse)
	err := c.cc.Invoke(ctx, NodeService_CancelJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) WatchJobEvents(ctx context.Context, in *WatchJobEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[2], NodeService_WatchJobEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchJobEventsRequest, JobEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_WatchJobEventsClient = grpc.ServerStreamingClient[JobEvent]

func (c *nodeServiceClient) GetModelConfig(ctx context.Context, in *GetModelConfigRequest, opts ...grpc.CallOption) (*ModelConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelConfig)
	err := c.cc.Invoke(ctx, NodeService_GetModelConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) SetModelConfig(ctx context.Context, in *SetModelConfigRequest, opts ...grpc.CallOption) (*ModelConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelConfig)
	err := c.cc.Invoke(ctx, NodeService_SetModelConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, NodeService_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) Ask(ctx context.Context, in *AskRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AskEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[3], NodeService_Ask_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AskRequest, AskEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_AskClient = grpc.ServerStreamingClient[AskEvent]

func (c *nodeServiceClient) ListChats(ctx context.Context, in *ListChatsRequest, opts ...grpc.CallOption) (*ListChatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChatsResponse)
	err := c.cc.Invoke(ctx, NodeService_ListChats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetChat(ctx context.Context, in *GetChatRequest, opts ...grpc.CallOption) (*GetChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChatResponse)
	err := c.cc.Invoke(ctx, NodeService_GetChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) DeleteChat(ctx context.Context, in *DeleteChatRequest, opts ...grpc.CallOption) (*DeleteChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteChatResponse)
	err := c.cc.Invoke(ctx, NodeService_DeleteChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) StoreFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StoreFileRequest, File], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[4], NodeService_StoreFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StoreFileRequest, File]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_StoreFileClient = grpc.ClientStreamingClient[StoreFileRequest, File]

func (c *nodeServiceClient) FetchFile(ctx context.Context, in *FetchFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FetchFileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[5], NodeService_FetchFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FetchFileRequest, FetchFileResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_FetchFileClient = grpc.ServerStreamingClient[FetchFileResponse]

func (c *nodeServiceClient) ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFilesResponse)
	err := c.cc.Invoke(ctx, NodeService_ListFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) RemoveFile(ctx context.Context, in *RemoveFileRequest, opts ...grpc.CallOption) (*RemoveFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveFileResponse)
	err := c.cc.Invoke(ctx, NodeService_RemoveFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) CreateInvitation(ctx context.Context, in *CreateInvitationRequest, opts ...grpc.CallOption) (*CreateInvitationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateInvitationResponse)
	err := c.cc.Invoke(ctx, NodeService_CreateInvitation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) ListMembers(ctx context.Context, in *ListMembersRequest, opts ...grpc.CallOption) (*ListMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMembersResponse)
	err := c.cc.Invoke(ctx, NodeService_ListMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) RemoveMember(ctx context.Context, in *RemoveMemberRequest, opts ...grpc.CallOption) (*RemoveMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveMemberResponse)
	err := c.cc.Invoke(ctx, NodeService_RemoveMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) JoinPool(ctx context.Context, in *JoinPoolRequest, opts ...grpc.CallOption) (*JoinPoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinPoolResponse)
	err := c.cc.Invoke(ctx, NodeService_JoinPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServiceServer is the server API for NodeService service.
// All implementations must embed UnimplementedNodeServiceServer
// for forward compatibility.
type NodeServiceServer interface {
	GetNodeInfo(context.Context, *GetNodeInfoRequest) (*GetNodeInfoResponse, error)
	ListPeers(context.Context, *ListPeersRequest) (*ListPeersResponse, error)
	WatchPeers(*WatchPeersRequest, grpc.ServerStreamingServer[ListPeersResponse]) error
	GetBootstrapPeers(context.Context, *GetBootstrapPeersRequest) (*GetBootstrapPeersResponse, error)
	SetBootstrapPeers(context.Context, *SetBootstrapPeersRequest) (*SetBootstrapPeersResponse, error)
	ConnectPeer(context.Context, *ConnectPeerRequest) (*ConnectPeerResponse, error)
	// SetPeerComputeTrust sets both sides of trust in a peer at once: whether
	// this node gives it work and whether this node takes work from it.
	SetPeerComputeTrust(context.Context, *SetPeerComputeTrustRequest) (*SetPeerComputeTrustResponse, error)
	// SetPeerComputePermissions sets the two sides separately.
	SetPeerComputePermissions(context.Context, *SetPeerComputePermissionsRequest) (*SetPeerComputePermissionsResponse, error)
	// ListWorkers lists the nodes connected to this one as its workers.
	ListWorkers(context.Context, *ListWorkersRequest) (*ListWorkersResponse, error)
	// SubmitJob gives the pool a job and returns it as it stands at once.
	SubmitJob(context.Context, *SubmitJobRequest) (*SubmitJobResponse, error)
	GetJob(context.Context, *GetJobRequest) (*GetJobResponse, error)
	// ListJobs lists the jobs this node has on record, newest first.
	ListJobs(context.Context, *ListJobsRequest) (*ListJobsResponse, error)
	// WatchJobs sends that list at once and again, in full, whenever any job
	// changes, with a revision that counts up from one.
	WatchJobs(*WatchJobsRequest, grpc.ServerStreamingServer[ListJobsResponse]) error
	// CancelJob stops a job that has not finished.
	CancelJob(context.Context, *CancelJobRequest) (*CancelJobResponse, error)
	// WatchJobEvents sends what has happened to a job, from the event after
	// the one named, and goes on as more happens until the job has finished:
	// the steps of its life and the lines its tasks log.
	WatchJobEvents(*WatchJobEventsRequest, grpc.ServerStreamingServer[JobEvent]) error
	// GetModelConfig says which model the node plans with. It never returns
	// the service's key, only whether one is set.
	GetModelConfig(context.Context, *GetModelConfigRequest) (*ModelConfig, error)
	SetModelConfig(context.Context, *SetModelConfigRequest) (*ModelConfig, error)
	// ListModels asks the configured service which models it offers.
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	// Ask puts a question to the planner, in a new conversation or an
	// existing one, and sends what it does as it does it: what the model
	// says, each job it runs, and at the end the event "done".
	Ask(*AskRequest, grpc.ServerStreamingServer[AskEvent]) error
	// ListChats lists the conversations on record, newest first.
	ListChats(context.Context, *ListChatsRequest) (*ListChatsResponse, error)
	GetChat(context.Context, *GetChatRequest) (*GetChatResponse, error)
	DeleteChat(context.Context, *DeleteChatRequest) (*DeleteChatResponse, error)
	// StoreFile puts a file in the pool's store and keeps it there until it
	// is removed. The first message names it; every message may carry data.
	// The answer has its CID, which is what a job is given as its input.
	StoreFile(grpc.ClientStreamingServer[StoreFileRequest, File]) error
	// FetchFile sends what is stored under a CID: a file stored here, or
	// something a job produced.
	FetchFile(*FetchFileRequest, grpc.ServerStreamingServer[FetchFileResponse]) error
	// ListFiles lists the files stored through StoreFile, newest first.
	ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error)
	// RemoveFile stops keeping a file. Its content goes when the store is
	// next cleared of what nothing holds.
	RemoveFile(context.Context, *RemoveFileRequest) (*RemoveFileResponse, error)
	// CreateInvitation makes an invitation for another machine to join the
	// pool with: as a worker, or as a client that may only submit jobs. It
	// works once.
	CreateInvitation(context.Context, *CreateInvitationRequest) (*CreateInvitationResponse, error)
	// ListMembers lists the nodes admitted to the pool.
	ListMembers(context.Context, *ListMembersRequest) (*ListMembersResponse, error)
	// RemoveMember takes a node out of the pool and disconnects it.
	RemoveMember(context.Context, *RemoveMemberRequest) (*RemoveMemberResponse, error)
	// JoinPool has this node join another node's pool with an invitation
	// from it, and start working for it, beside whatever else it is doing.
	// It is what a node started with --join does, without the restart.
	JoinPool(context.Context, *JoinPoolRequest) (*JoinPoolResponse, error)
	mustEmbedUnimplementedNodeServiceServer()
}

// UnimplementedNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeServiceServer struct{}

func (UnimplementedNodeServiceServer) GetNodeInfo(context.Context, *GetNodeInfoRequest) (*GetNodeInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodeInfo not implemented")
}
func (UnimplementedNodeServiceServer) ListPeers(context.Context, *ListPeersRequest) (*ListPeersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPeers not implemented")
}
func (UnimplementedNodeServiceServer) WatchPeers(*WatchPeersRequest, grpc.ServerStreamingServer[ListPeersResponse]) error {
	return status.Error(codes.Unimplemented, "method WatchPeers not implemented")
}
func (UnimplementedNodeServiceServer) GetBootstrapPeers(context.Context, *GetBootstrapPeersRequest) (*GetBootstrapPeersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBootstrapPeers not implemented")
}
func (UnimplementedNodeServiceServer) SetBootstrapPeers(context.Context, *SetBootstrapPeersRequest) (*SetBootstrapPeersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetBootstrapPeers not implemented")
}
func (UnimplementedNodeServiceServer) ConnectPeer(context.Context, *ConnectPeerRequest) (*ConnectPeerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConnectPeer not implemented")
}
func (UnimplementedNodeServiceServer) SetPeerComputeTrust(context.Context, *SetPeerComputeTrustRequest) (*SetPeerComputeTrustResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPeerComputeTrust not implemented")
}
func (UnimplementedNodeServiceServer) SetPeerComputePermissions(context.Context, *SetPeerComputePermissionsRequest) (*SetPeerComputePermissionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPeerComputePermissions not implemented")
}
func (UnimplementedNodeServiceServer) ListWorkers(context.Context, *ListWorkersRequest) (*ListWorkersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWorkers not implemented")
}
func (UnimplementedNodeServiceServer) SubmitJob(context.Context, *SubmitJobRequest) (*SubmitJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitJob not implemented")
}
func (UnimplementedNodeServiceServer) GetJob(context.Context, *GetJobRequest) (*GetJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJob not implemented")
}
func (UnimplementedNodeServiceServer) ListJobs(context.Context, *ListJobsRequest) (*ListJobsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListJobs not implemented")
}
func (UnimplementedNodeServiceServer) WatchJobs(*WatchJobsRequest, grpc.ServerStreamingServer[ListJobsResponse]) error {
	return status.Error(codes.Unimplemented, "method WatchJobs not implemented")
}
func (UnimplementedNodeServiceServer) CancelJob(context.Context, *CancelJobRequest) (*CancelJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelJob not implemented")
}
func (UnimplementedNodeServiceServer) WatchJobEvents(*WatchJobEventsRequest, grpc.ServerStreamingServer[JobEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchJobEvents not implemented")
}
func (UnimplementedNodeServiceServer) GetModelConfig(context.Context, *GetModelConfigRequest) (*ModelConfig, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModelConfig not implemented")
}
func (UnimplementedNodeServiceServer) SetModelConfig(context.Context, *SetModelConfigRequest) (*ModelConfig, error) {
	return nil, status.Error(codes.Unimplemented, "method SetModelConfig not implemented")
}
func (UnimplementedNodeServiceServer) ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedNodeServiceServer) Ask(*AskRequest, grpc.ServerStreamingServer[AskEvent]) error {
	return status.Error(codes.Unimplemented, "method Ask not implemented")
}
func (UnimplementedNodeServiceServer) ListChats(context.Context, *ListChatsRequest) (*ListChatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListChats not implemented")
}
func (UnimplementedNodeServiceServer) GetChat(context.Context, *GetChatRequest) (*GetChatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChat not implemented")
}
func (UnimplementedNodeServiceServer) DeleteChat(context.Context, *DeleteChatRequest) (*DeleteChatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteChat not implemented")
}
func (UnimplementedNodeServiceServer) StoreFile(grpc.ClientStreamingServer[StoreFileRequest, File]) error {
	return status.Error(codes.Unimplemented, "method StoreFile not implemented")
}
func (UnimplementedNodeServiceServer) FetchFile(*FetchFileRequest, grpc.ServerStreamingServer[FetchFileResponse]) error {
	return status.Error(codes.Unimplemented, "method FetchFile not implemented")
}
func (UnimplementedNodeServiceServer) ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFiles not implemented")
}
func (UnimplementedNodeServiceServer) RemoveFile(context.Context, *RemoveFileRequest) (*RemoveFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveFile not implemented")
}
func (UnimplementedNodeServiceServer) CreateInvitation(context.Context, *CreateInvitationRequest) (*CreateInvitationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateInvitation not implemented")
}
func (UnimplementedNodeServiceServer) ListMembers(context.Context, *ListMembersRequest) (*ListMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMembers not implemented")
}
func (UnimplementedNodeServiceServer) RemoveMember(context.Context, *RemoveMemberRequest) (*RemoveMemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveMember not implemented")
}
func (UnimplementedNodeServiceServer) JoinPool(context.Context, *JoinPoolRequest) (*JoinPoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinPool not implemented")
}
func (UnimplementedNodeServiceServer) mustEmbedUnimplementedNodeServiceServer() {}
func (UnimplementedNodeServiceServer) testEmbeddedByValue()                     {}

// UnsafeNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServiceServer will
// result in compilation errors.
type UnsafeNodeServiceServer interface {
	mustEmbedUnimplementedNodeServiceServer()
}

func RegisterNodeServiceServer(s grpc.ServiceRegistrar, srv NodeServiceServer) {
	// If the following call panics, it indicates UnimplementedNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeService_ServiceDesc, srv)
}

func _NodeService_GetNodeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetNodeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetNodeInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetNodeInfo(ctx, req.(*GetNodeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_ListPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPeersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ListPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_ListPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ListPeers(ctx, req.(*ListPeersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_WatchPeers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchPeersRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeServiceServer).WatchPeers(m, &grpc.GenericServerStream[WatchPeersRequest, ListPeersResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_WatchPeersServer = grpc.ServerStreamingServer[ListPeersResponse]

func _NodeService_GetBootstrapPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBootstrapPeersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetBootstrapPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetBootstrapPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetBootstrapPeers(ctx, req.(*GetBootstrapPeersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_SetBootstrapPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetBootstrapPeersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).SetBootstrapPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_SetBootstrapPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).SetBootstrapPeers(ctx, req.(*SetBootstrapPeersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_ConnectPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ConnectPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_ConnectPeer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ConnectPeer(ctx, req.(*ConnectPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_SetPeerComputeTrust_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPeerComputeTrustRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).SetPeerComputeTrust(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_SetPeerComputeTrust_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).SetPeerComputeTrust(ctx, req.(*SetPeerComputeTrustRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_SetPeerComputePermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPeerComputePermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).SetPeerComputePermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_SetPeerComputePermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).SetPeerComputePermissions(ctx, req.(*SetPeerComputePermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_ListWorkers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ListWorkers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_ListWorkers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ListWorkers(ctx, req.(*ListWorkersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_SubmitJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).SubmitJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_SubmitJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).SubmitJob(ctx, req.(*SubmitJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetJob(ctx, req.(*GetJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_ListJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ListJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_ListJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ListJobs(ctx, req.(*ListJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_WatchJobs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchJobsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeServiceServer).WatchJobs(m, &grpc.GenericServerStream[WatchJobsRequest, ListJobsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_WatchJobsServer = grpc.ServerStreamingServer[ListJobsResponse]

func _NodeService_CancelJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).CancelJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_CancelJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).CancelJob(ctx, req.(*CancelJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_WatchJobEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchJobEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeServiceServer).WatchJobEvents(m, &grpc.GenericServerStream[WatchJobEventsRequest, JobEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_WatchJobEventsServer = grpc.ServerStreamingServer[JobEvent]

func _NodeService_GetModelConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetModelConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetModelConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetModelConfig(ctx, req.(*GetModelConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_SetModelConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetModelConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).SetModelConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_SetModelConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).SetModelConfig(ctx, req.(*SetModelConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_Ask_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AskRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeServiceServer).Ask(m, &grpc.GenericServerStream[AskRequest, AskEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_AskServer = grpc.ServerStreamingServer[AskEvent]

func _NodeService_ListChats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ListChats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_ListChats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ListChats(ctx, req.(*ListChatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetChat(ctx, req.(*GetChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_DeleteChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).DeleteChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_DeleteChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).DeleteChat(ctx, req.(*DeleteChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_StoreFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeServiceServer).StoreFile(&grpc.GenericServerStream[StoreFileRequest, File]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_StoreFileServer = grpc.ClientStreamingServer[StoreFileRequest, File]

func _NodeService_FetchFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FetchFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeServiceServer).FetchFile(m, &grpc.GenericServerStream[FetchFileRequest, FetchFileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_FetchFileServer = grpc.ServerStreamingServer[FetchFileResponse]

func _NodeService_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_ListFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ListFiles(ctx, req.(*ListFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_RemoveFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).RemoveFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_RemoveFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).RemoveFile(ctx, req.(*RemoveFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_CreateInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInvitationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).CreateInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_CreateInvitation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).CreateInvitation(ctx, req.(*CreateInvitationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_ListMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ListMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_ListMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ListMembers(ctx, req.(*ListMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_RemoveMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).RemoveMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_RemoveMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).RemoveMember(ctx, req.(*RemoveMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_JoinPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).JoinPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_JoinPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).JoinPool(ctx, req.(*JoinPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeService_ServiceDesc is the grpc.ServiceDesc for NodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sisyphus.node.v1.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNodeInfo",
			Handler:    _NodeService_GetNodeInfo_Handler,
		},
		{
			MethodName: "ListPeers",
			Handler:    _NodeService_ListPeers_Handler,
		},
		{
			MethodName: "GetBootstrapPeers",
			Handler:    _NodeService_GetBootstrapPeers_Handler,
		},
		{
			MethodName: "SetBootstrapPeers",
			Handler:    _NodeService_SetBootstrapPeers_Handler,
		},
		{
			MethodName: "ConnectPeer",
			Handler:    _NodeService_ConnectPeer_Handler,
		},
		{
			MethodName: "SetPeerComputeTrust",
			Handler:    _NodeService_SetPeerComputeTrust_Handler,
		},
		{
			MethodName: "SetPeerComputePermissions",
			Handler:    _NodeService_SetPeerComputePermissions_Handler,
		},
		{
			MethodName: "ListWorkers",
			Handler:    _NodeService_ListWorkers_Handler,
		},
		{
			MethodName: "SubmitJob",
			Handler:    _NodeService_SubmitJob_Handler,
		},
		{
			MethodName: "GetJob",
			Handler:    _NodeService_GetJob_Handler,
		},
		{
			MethodName: "ListJobs",
			Handler:    _NodeService_ListJobs_Handler,
		},
		{
			MethodName: "CancelJob",
			Handler:    _NodeService_CancelJob_Handler,
		},
		{
			MethodName: "GetModelConfig",
			Handler:    _NodeService_GetModelConfig_Handler,
		},
		{
			MethodName: "SetModelConfig",
			Handler:    _NodeService_SetModelConfig_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _NodeService_ListModels_Handler,
		},
		{
			MethodName: "ListChats",
			Handler:    _NodeService_ListChats_Handler,
		},
		{
			MethodName: "GetChat",
			Handler:    _NodeService_GetChat_Handler,
		},
		{
			MethodName: "DeleteChat",
			Handler:    _NodeService_DeleteChat_Handler,
		},
		{
			MethodName: "ListFiles",
			Handler:    _NodeService_ListFiles_Handler,
		},
		{
			MethodName: "RemoveFile",
			Handler:    _NodeService_RemoveFile_Handler,
		},
		{
			MethodName: "CreateInvitation",
			Handler:    _NodeService_CreateInvitation_Handler,
		},
		{
			MethodName: "ListMembers",
			Handler:    _NodeService_ListMembers_Handler,
		},
		{
			MethodName: "RemoveMember",
			Handler:    _NodeService_RemoveMember_Handler,
		},
		{
			MethodName: "JoinPool",
			Handler:    _NodeService_JoinPool_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchPeers",
			Handler:       _NodeService_WatchPeers_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchJobs",
			Handler:       _NodeService_WatchJobs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchJobEvents",
			Handler:       _NodeService_WatchJobEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Ask",
			Handler:       _NodeService_Ask_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StoreFile",
			Handler:       _NodeService_StoreFile_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "FetchFile",
			Handler:       _NodeService_FetchFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sisyphus/node/v1/node.proto",
}
