// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: sisyphus/node/v1/node.proto

package nodev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PeerConnectionState int32

const (
	PeerConnectionState_PEER_CONNECTION_STATE_UNSPECIFIED  PeerConnectionState = 0
	PeerConnectionState_PEER_CONNECTION_STATE_DISCONNECTED PeerConnectionState = 1
	PeerConnectionState_PEER_CONNECTION_STATE_CONNECTED    PeerConnectionState = 2
)

// Enum value maps for PeerConnectionState.
var (
	PeerConnectionState_name = map[int32]string{
		0: "PEER_CONNECTION_STATE_UNSPECIFIED",
		1: "PEER_CONNECTION_STATE_DISCONNECTED",
		2: "PEER_CONNECTION_STATE_CONNECTED",
	}
	PeerConnectionState_value = map[string]int32{
		"PEER_CONNECTION_STATE_UNSPECIFIED":  0,
		"PEER_CONNECTION_STATE_DISCONNECTED": 1,
		"PEER_CONNECTION_STATE_CONNECTED":    2,
	}
)

func (x PeerConnectionState) Enum() *PeerConnectionState {
	p := new(PeerConnectionState)
	*p = x
	return p
}

func (x PeerConnectionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PeerConnectionState) Descriptor() protoreflect.EnumDescriptor {
	return file_sisyphus_node_v1_node_proto_enumTypes[0].Descriptor()
}

func (PeerConnectionState) Type() protoreflect.EnumType {
	return &file_sisyphus_node_v1_node_proto_enumTypes[0]
}

func (x PeerConnectionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PeerConnectionState.Descriptor instead.
func (PeerConnectionState) EnumDescriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{0}
}

type JobState int32

const (
	JobState_JOB_STATE_UNSPECIFIED JobState = 0
	JobState_JOB_STATE_PENDING     JobState = 1
	JobState_JOB_STATE_RUNNING     JobState = 2
	JobState_JOB_STATE_SUCCEEDED   JobState = 3
	JobState_JOB_STATE_FAILED      JobState = 4
	JobState_JOB_STATE_CANCELLED   JobState = 5
)

// Enum value maps for JobState.
var (
	JobState_name = map[int32]string{
		0: "JOB_STATE_UNSPECIFIED",
		1: "JOB_STATE_PENDING",
		2: "JOB_STATE_RUNNING",
		3: "JOB_STATE_SUCCEEDED",
		4: "JOB_STATE_FAILED",
		5: "JOB_STATE_CANCELLED",
	}
	JobState_value = map[string]int32{
		"JOB_STATE_UNSPECIFIED": 0,
		"JOB_STATE_PENDING":     1,
		"JOB_STATE_RUNNING":     2,
		"JOB_STATE_SUCCEEDED":   3,
		"JOB_STATE_FAILED":      4,
		"JOB_STATE_CANCELLED":   5,
	}
)

func (x JobState) Enum() *JobState {
	p := new(JobState)
	*p = x
	return p
}

func (x JobState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobState) Descriptor() protoreflect.EnumDescriptor {
	return file_sisyphus_node_v1_node_proto_enumTypes[1].Descriptor()
}

func (JobState) Type() protoreflect.EnumType {
	return &file_sisyphus_node_v1_node_proto_enumTypes[1]
}

func (x JobState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobState.Descriptor instead.
func (JobState) EnumDescriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{1}
}

type JobMode int32

const (
	JobMode_JOB_MODE_UNSPECIFIED JobMode = 0
	// Split into tasks spread across workers.
	JobMode_JOB_MODE_DISTRIBUTED JobMode = 1
	// Sent whole to one worker.
	JobMode_JOB_MODE_FULL_WORKER JobMode = 2
)

// Enum value maps for JobMode.
var (
	JobMode_name = map[int32]string{
		0: "JOB_MODE_UNSPECIFIED",
		1: "JOB_MODE_DISTRIBUTED",
		2: "JOB_MODE_FULL_WORKER",
	}
	JobMode_value = map[string]int32{
		"JOB_MODE_UNSPECIFIED": 0,
		"JOB_MODE_DISTRIBUTED": 1,
		"JOB_MODE_FULL_WORKER": 2,
	}
)

func (x JobMode) Enum() *JobMode {
	p := new(JobMode)
	*p = x
	return p
}

func (x JobMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobMode) Descriptor() protoreflect.EnumDescriptor {
	return file_sisyphus_node_v1_node_proto_enumTypes[2].Descriptor()
}

func (JobMode) Type() protoreflect.EnumType {
	return &file_sisyphus_node_v1_node_proto_enumTypes[2]
}

func (x JobMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobMode.Descriptor instead.
func (JobMode) EnumDescriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{2}
}

type GetNodeInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeInfoRequest) Reset() {
	*x = GetNodeInfoRequest{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeInfoRequest) ProtoMessage() {}

func (x *GetNodeInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeInfoRequest.ProtoReflect.Descriptor instead.
func (*GetNodeInfoRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{0}
}

type GetNodeInfoResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PeerId          string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	DaemonVersion   string                 `protobuf:"bytes,2,opt,name=daemon_version,json=daemonVersion,proto3" json:"daemon_version,omitempty"`
	ListenAddresses []string               `protobuf:"bytes,3,rep,name=listen_addresses,json=listenAddresses,proto3" json:"listen_addresses,omitempty"`
	CountryCode     string                 `protobuf:"bytes,4,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	// The names of the workloads this node can run or coordinate.
	Workloads     []string `protobuf:"bytes,5,rep,name=workloads,proto3" json:"workloads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeInfoResponse) Reset() {
	*x = GetNodeInfoResponse{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeInfoResponse) ProtoMessage() {}

func (x *GetNodeInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeInfoResponse.ProtoReflect.Descriptor instead.
func (*GetNodeInfoResponse) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{1}
}

func (x *GetNodeInfoResponse) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *GetNodeInfoResponse) GetDaemonVersion() string {
	if x != nil {
		return x.DaemonVersion
	}
	return ""
}

func (x *GetNodeInfoResponse) GetListenAddresses() []string {
	if x != nil {
		return x.ListenAddresses
	}
	return nil
}

func (x *GetNodeInfoResponse) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *GetNodeInfoResponse) GetWorkloads() []string {
	if x != nil {
		return x.Workloads
	}
	return nil
}

type ListPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPeersRequest) Reset() {
	*x = ListPeersRequest{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeersRequest) ProtoMessage() {}

func (x *ListPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeersRequest.ProtoReflect.Descriptor instead.
func (*ListPeersRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{2}
}

type WatchPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchPeersRequest) Reset() {
	*x = WatchPeersRequest{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchPeersRequest) ProtoMessage() {}

func (x *WatchPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchPeersRequest.ProtoReflect.Descriptor instead.
func (*WatchPeersRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{3}
}

type GetBootstrapPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBootstrapPeersRequest) Reset() {
	*x = GetBootstrapPeersRequest{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBootstrapPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBootstrapPeersRequest) ProtoMessage() {}

func (x *GetBootstrapPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBootstrapPeersRequest.ProtoReflect.Descriptor instead.
func (*GetBootstrapPeersRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{4}
}

type GetBootstrapPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*BootstrapPeer       `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBootstrapPeersResponse) Reset() {
	*x = GetBootstrapPeersResponse{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBootstrapPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBootstrapPeersResponse) ProtoMessage() {}

func (x *GetBootstrapPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBootstrapPeersResponse.ProtoReflect.Descriptor instead.
func (*GetBootstrapPeersResponse) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{5}
}

func (x *GetBootstrapPeersResponse) GetPeers() []*BootstrapPeer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type SetBootstrapPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*BootstrapPeer       `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBootstrapPeersRequest) Reset() {
	*x = SetBootstrapPeersRequest{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBootstrapPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBootstrapPeersRequest) ProtoMessage() {}

func (x *SetBootstrapPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBootstrapPeersRequest.ProtoReflect.Descriptor instead.
func (*SetBootstrapPeersRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{6}
}

func (x *SetBootstrapPeersRequest) GetPeers() []*BootstrapPeer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type SetBootstrapPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*BootstrapPeer       `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBootstrapPeersResponse) Reset() {
	*x = SetBootstrapPeersResponse{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBootstrapPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBootstrapPeersResponse) ProtoMessage() {}

func (x *SetBootstrapPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBootstrapPeersResponse.ProtoReflect.Descriptor instead.
func (*SetBootstrapPeersResponse) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{7}
}

func (x *SetBootstrapPeersResponse) GetPeers() []*BootstrapPeer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type ConnectPeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectPeerRequest) Reset() {
	*x = ConnectPeerRequest{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectPeerRequest) ProtoMessage() {}

func (x *ConnectPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectPeerRequest.ProtoReflect.Descriptor instead.
func (*ConnectPeerRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{8}
}

func (x *ConnectPeerRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type ConnectPeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectPeerResponse) Reset() {
	*x = ConnectPeerResponse{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectPeerResponse) ProtoMessage() {}

func (x *ConnectPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectPeerResponse.ProtoReflect.Descriptor instead.
func (*ConnectPeerResponse) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{9}
}

func (x *ConnectPeerResponse) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

type SetPeerComputeTrustRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Trusted       bool                   `protobuf:"varint,2,opt,name=trusted,proto3" json:"trusted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPeerComputeTrustRequest) Reset() {
	*x = SetPeerComputeTrustRequest{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPeerComputeTrustRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPeerComputeTrustRequest) ProtoMessage() {}

func (x *SetPeerComputeTrustRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPeerComputeTrustRequest.ProtoReflect.Descriptor instead.
func (*SetPeerComputeTrustRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{10}
}

func (x *SetPeerComputeTrustRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *SetPeerComputeTrustRequest) GetTrusted() bool {
	if x != nil {
		return x.Trusted
	}
	return false
}

type SetPeerComputeTrustResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trusted       bool                   `protobuf:"varint,1,opt,name=trusted,proto3" json:"trusted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPeerComputeTrustResponse) Reset() {
	*x = SetPeerComputeTrustResponse{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPeerComputeTrustResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPeerComputeTrustResponse) ProtoMessage() {}

func (x *SetPeerComputeTrustResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPeerComputeTrustResponse.ProtoReflect.Descriptor instead.
func (*SetPeerComputeTrustResponse) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{11}
}

func (x *SetPeerComputeTrustResponse) GetTrusted() bool {
	if x != nil {
		return x.Trusted
	}
	return false
}

type SetPeerComputePermissionsRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	PeerId string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	// This node gives the peer work: the peer may work for this node.
	GivesWork bool `protobuf:"varint,2,opt,name=gives_work,json=givesWork,proto3" json:"gives_work,omitempty"`
	// This node takes work from the peer: it will work for the peer.
	TakesWork     bool `protobuf:"varint,3,opt,name=takes_work,json=takesWork,proto3" json:"takes_work,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPeerComputePermissionsRequest) Reset() {
	*x = SetPeerComputePermissionsRequest{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPeerComputePermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPeerComputePermissionsRequest) ProtoMessage() {}

func (x *SetPeerComputePermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPeerComputePermissionsRequest.ProtoReflect.Descriptor instead.
func (*SetPeerComputePermissionsRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{12}
}

func (x *SetPeerComputePermissionsRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *SetPeerComputePermissionsRequest) GetGivesWork() bool {
	if x != nil {
		return x.GivesWork
	}
	return false
}

func (x *SetPeerComputePermissionsRequest) GetTakesWork() bool {
	if x != nil {
		return x.TakesWork
	}
	return false
}

type SetPeerComputePermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GivesWork     bool                   `protobuf:"varint,1,opt,name=gives_work,json=givesWork,proto3" json:"gives_work,omitempty"`
	TakesWork     bool                   `protobuf:"varint,2,opt,name=takes_work,json=takesWork,proto3" json:"takes_work,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPeerComputePermissionsResponse) Reset() {
	*x = SetPeerComputePermissionsResponse{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPeerComputePermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPeerComputePermissionsResponse) ProtoMessage() {}

func (x *SetPeerComputePermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPeerComputePermissionsResponse.ProtoReflect.Descriptor instead.
func (*SetPeerComputePermissionsResponse) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{13}
}

func (x *SetPeerComputePermissionsResponse) GetGivesWork() bool {
	if x != nil {
		return x.GivesWork
	}
	return false
}

func (x *SetPeerComputePermissionsResponse) GetTakesWork() bool {
	if x != nil {
		return x.TakesWork
	}
	return false
}

type BootstrapPeer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapPeer) Reset() {
	*x = BootstrapPeer{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapPeer) ProtoMessage() {}

func (x *BootstrapPeer) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapPeer.ProtoReflect.Descriptor instead.
func (*BootstrapPeer) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{14}
}

func (x *BootstrapPeer) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *BootstrapPeer) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type ListPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*Peer                `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	Revision      uint64                 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPeersResponse) Reset() {
	*x = ListPeersResponse{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeersResponse) ProtoMessage() {}

func (x *ListPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeersResponse.ProtoReflect.Descriptor instead.
func (*ListPeersResponse) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{15}
}

func (x *ListPeersResponse) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *ListPeersResponse) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type Peer struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PeerId            string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	ConnectionState   PeerConnectionState    `protobuf:"varint,2,opt,name=connection_state,json=connectionState,proto3,enum=sisyphus.node.v1.PeerConnectionState" json:"connection_state,omitempty"`
	KnownAddresses    []string               `protobuf:"bytes,3,rep,name=known_addresses,json=knownAddresses,proto3" json:"known_addresses,omitempty"`
	TrustedForCompute bool                   `protobuf:"varint,4,opt,name=trusted_for_compute,json=trustedForCompute,proto3" json:"trusted_for_compute,omitempty"`
	// Trust has two sides, and work flows only when both hold. These say
	// which way it is flowing now: the peer is connected as a worker of this
	// node, and this node is working for the peer.
	WorksForThisNode bool `protobuf:"varint,5,opt,name=works_for_this_node,json=worksForThisNode,proto3" json:"works_for_this_node,omitempty"`
	ThisNodeWorksFor bool `protobuf:"varint,6,opt,name=this_node_works_for,json=thisNodeWorksFor,proto3" json:"this_node_works_for,omitempty"`
	// The two sides of this node's trust in the peer: that it gives the peer
	// work, and that it takes work from the peer. trusted_for_compute is set
	// if either is.
	GivesWork     bool `protobuf:"varint,7,opt,name=gives_work,json=givesWork,proto3" json:"gives_work,omitempty"`
	TakesWork     bool `protobuf:"varint,8,opt,name=takes_work,json=takesWork,proto3" json:"takes_work,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{16}
}

func (x *Peer) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *Peer) GetConnectionState() PeerConnectionState {
	if x != nil {
		return x.ConnectionState
	}
	return PeerConnectionState_PEER_CONNECTION_STATE_UNSPECIFIED
}

func (x *Peer) GetKnownAddresses() []string {
	if x != nil {
		return x.KnownAddresses
	}
	return nil
}

func (x *Peer) GetTrustedForCompute() bool {
	if x != nil {
		return x.TrustedForCompute
	}
	return false
}

func (x *Peer) GetWorksForThisNode() bool {
	if x != nil {
		return x.WorksForThisNode
	}
	return false
}

func (x *Peer) GetThisNodeWorksFor() bool {
	if x != nil {
		return x.ThisNodeWorksFor
	}
	return false
}

func (x *Peer) GetGivesWork() bool {
	if x != nil {
		return x.GivesWork
	}
	return false
}

func (x *Peer) GetTakesWork() bool {
	if x != nil {
		return x.TakesWork
	}
	return false
}

type ListWorkersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkersRequest) Reset() {
	*x = ListWorkersRequest{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkersRequest) ProtoMessage() {}

func (x *ListWorkersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkersRequest.ProtoReflect.Descriptor instead.
func (*ListWorkersRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{17}
}

type ListWorkersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workers       []*Worker              `protobuf:"bytes,1,rep,name=workers,proto3" json:"workers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkersResponse) Reset() {
	*x = ListWorkersResponse{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkersResponse) ProtoMessage() {}

func (x *ListWorkersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkersResponse.ProtoReflect.Descriptor instead.
func (*ListWorkersResponse) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{18}
}

func (x *ListWorkersResponse) GetWorkers() []*Worker {
	if x != nil {
		return x.Workers
	}
	return nil
}

type Worker struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	PeerId string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	// The label the node gave itself.
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Hostname string `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os       string `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	Arch     string `protobuf:"bytes,5,opt,name=arch,proto3" json:"arch,omitempty"`
	CpuCores uint32 `protobuf:"varint,6,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	// How many tasks it runs at once, and how many it is running now.
	TaskSlots    uint32   `protobuf:"varint,7,opt,name=task_slots,json=taskSlots,proto3" json:"task_slots,omitempty"`
	RunningTasks uint32   `protobuf:"varint,8,opt,name=running_tasks,json=runningTasks,proto3" json:"running_tasks,omitempty"`
	Workloads    []string `protobuf:"bytes,9,rep,name=workloads,proto3" json:"workloads,omitempty"`
	// Whether it relays between the pool's other members, and what it says it
	// has carried for them since it started.
	Relays             bool   `protobuf:"varint,10,opt,name=relays,proto3" json:"relays,omitempty"`
	RelayedConnections uint64 `protobuf:"varint,11,opt,name=relayed_connections,json=relayedConnections,proto3" json:"relayed_connections,omitempty"`
	RelayedBytes       uint64 `protobuf:"varint,12,opt,name=relayed_bytes,json=relayedBytes,proto3" json:"relayed_bytes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Worker) Reset() {
	*x = Worker{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Worker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Worker) ProtoMessage() {}

func (x *Worker) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Worker.ProtoReflect.Descriptor instead.
func (*Worker) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{19}
}

func (x *Worker) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *Worker) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Worker) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Worker) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Worker) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *Worker) GetCpuCores() uint32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *Worker) GetTaskSlots() uint32 {
	if x != nil {
		return x.TaskSlots
	}
	return 0
}

func (x *Worker) GetRunningTasks() uint32 {
	if x != nil {
		return x.RunningTasks
	}
	return 0
}

func (x *Worker) GetWorkloads() []string {
	if x != nil {
		return x.Workloads
	}
	return nil
}

func (x *Worker) GetRelays() bool {
	if x != nil {
		return x.Relays
	}
	return false
}

func (x *Worker) GetRelayedConnections() uint64 {
	if x != nil {
		return x.RelayedConnections
	}
	return 0
}

func (x *Worker) GetRelayedBytes() uint64 {
	if x != nil {
		return x.RelayedBytes
	}
	return 0
}

type Job struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	JobId    string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Workload string                 `protobuf:"bytes,2,opt,name=workload,proto3" json:"workload,omitempty"`
	// Workload-defined parameters and result. The built-in workloads use JSON.
	Params []byte     `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	Mode   JobMode    `protobuf:"varint,4,opt,name=mode,proto3,enum=sisyphus.node.v1.JobMode" json:"mode,omitempty"`
	State  JobState   `protobuf:"varint,5,opt,name=state,proto3,enum=sisyphus.node.v1.JobState" json:"state,omitempty"`
	Tasks  []*JobTask `protobuf:"bytes,6,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Result []byte     `protobuf:"bytes,7,opt,name=result,proto3" json:"result,omitempty"`
	Error  string     `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	// Milliseconds since the Unix epoch; zero for a job not yet finished.
	CreatedAtMs  int64 `protobuf:"varint,9,opt,name=created_at_ms,json=createdAtMs,proto3" json:"created_at_ms,omitempty"`
	FinishedAtMs int64 `protobuf:"varint,10,opt,name=finished_at_ms,json=finishedAtMs,proto3" json:"finished_at_ms,omitempty"`
	// CIDs of the stored data the job consumed and of what its result is.
	InputBlobs  []string `protobuf:"bytes,11,rep,name=input_blobs,json=inputBlobs,proto3" json:"input_blobs,omitempty"`
	OutputBlobs []string `protobuf:"bytes,12,rep,name=output_blobs,json=outputBlobs,proto3" json:"output_blobs,omitempty"`
	// From 0 to 1: the mean of its tasks' progress.
	Progress float64 `protobuf:"fixed64,13,opt,name=progress,proto3" json:"progress,omitempty"`
	// If not zero, how long any one attempt at a task may run.
	TaskTimeoutSeconds uint32 `protobuf:"varint,14,opt,name=task_timeout_seconds,json=taskTimeoutSeconds,proto3" json:"task_timeout_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{20}
}

func (x *Job) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Job) GetWorkload() string {
	if x != nil {
		return x.Workload
	}
	return ""
}

func (x *Job) GetParams() []byte {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Job) GetMode() JobMode {
	if x != nil {
		return x.Mode
	}
	return JobMode_JOB_MODE_UNSPECIFIED
}

func (x *Job) GetState() JobState {
	if x != nil {
		return x.State
	}
	return JobState_JOB_STATE_UNSPECIFIED
}

func (x *Job) GetTasks() []*JobTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *Job) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Job) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Job) GetCreatedAtMs() int64 {
	if x != nil {
		return x.CreatedAtMs
	}
	return 0
}

func (x *Job) GetFinishedAtMs() int64 {
	if x != nil {
		return x.FinishedAtMs
	}
	return 0
}

func (x *Job) GetInputBlobs() []string {
	if x != nil {
		return x.InputBlobs
	}
	return nil
}

func (x *Job) GetOutputBlobs() []string {
	if x != nil {
		return x.OutputBlobs
	}
	return nil
}

func (x *Job) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *Job) GetTaskTimeoutSeconds() uint32 {
	if x != nil {
		return x.TaskTimeoutSeconds
	}
	return 0
}

type JobTask struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Index uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	State JobState               `protobuf:"varint,2,opt,name=state,proto3,enum=sisyphus.node.v1.JobState" json:"state,omitempty"`
	// How many times it has been handed to a worker.
	Attempt uint32 `protobuf:"varint,3,opt,name=attempt,proto3" json:"attempt,omitempty"`
	// The worker running it, or that last did.
	PeerId     string `protobuf:"bytes,4,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	WorkerName string `protobuf:"bytes,5,opt,name=worker_name,json=workerName,proto3" json:"worker_name,omitempty"`
	// Why its last failed attempt failed, if one did.
	Error string `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	// From 0 to 1, as far as the task itself says.
	Progress      float64 `protobuf:"fixed64,7,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobTask) Reset() {
	*x = JobTask{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobTask) ProtoMessage() {}

func (x *JobTask) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobTask.ProtoReflect.Descriptor instead.
func (*JobTask) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{21}
}

func (x *JobTask) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *JobTask) GetState() JobState {
	if x != nil {
		return x.State
	}
	return JobState_JOB_STATE_UNSPECIFIED
}

func (x *JobTask) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *JobTask) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *JobTask) GetWorkerName() string {
	if x != nil {
		return x.WorkerName
	}
	return ""
}

func (x *JobTask) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *JobTask) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

type SubmitJobRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Workload string                 `protobuf:"bytes,1,opt,name=workload,proto3" json:"workload,omitempty"`
	Params   []byte                 `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	Mode     JobMode                `protobuf:"varint,3,opt,name=mode,proto3,enum=sisyphus.node.v1.JobMode" json:"mode,omitempty"`
	// Distributed mode only: how many tasks to split into. Zero means one for
	// each worker slot connected now.
	MaxTasks uint32 `protobuf:"varint,4,opt,name=max_tasks,json=maxTasks,proto3" json:"max_tasks,omitempty"`
	// If not zero, stop and retry any attempt at a task that runs longer.
	TaskTimeoutSeconds uint32 `protobuf:"varint,5,opt,name=task_timeout_seconds,json=taskTimeoutSeconds,proto3" json:"task_timeout_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SubmitJobRequest) Reset() {
	*x = SubmitJobRequest{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobRequest) ProtoMessage() {}

func (x *SubmitJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobRequest.ProtoReflect.Descriptor instead.
func (*SubmitJobRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{22}
}

func (x *SubmitJobRequest) GetWorkload() string {
	if x != nil {
		return x.Workload
	}
	return ""
}

func (x *SubmitJobRequest) GetParams() []byte {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *SubmitJobRequest) GetMode() JobMode {
	if x != nil {
		return x.Mode
	}
	return JobMode_JOB_MODE_UNSPECIFIED
}

func (x *SubmitJobRequest) GetMaxTasks() uint32 {
	if x != nil {
		return x.MaxTasks
	}
	return 0
}

func (x *SubmitJobRequest) GetTaskTimeoutSeconds() uint32 {
	if x != nil {
		return x.TaskTimeoutSeconds
	}
	return 0
}

type SubmitJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobResponse) Reset() {
	*x = SubmitJobResponse{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobResponse) ProtoMessage() {}

func (x *SubmitJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobResponse.ProtoReflect.Descriptor instead.
func (*SubmitJobResponse) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{23}
}

func (x *SubmitJobResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type CancelJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobRequest) Reset() {
	*x = CancelJobRequest{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobRequest) ProtoMessage() {}

func (x *CancelJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobRequest.ProtoReflect.Descriptor instead.
func (*CancelJobRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{24}
}

func (x *CancelJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type CancelJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobResponse) Reset() {
	*x = CancelJobResponse{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobResponse) ProtoMessage() {}

func (x *CancelJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobResponse.ProtoReflect.Descriptor instead.
func (*CancelJobResponse) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{25}
}

func (x *CancelJobResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type WatchJobEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	JobId string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Send only events numbered after this one. Zero sends them all.
	AfterSeq      uint64 `protobuf:"varint,2,opt,name=after_seq,json=afterSeq,proto3" json:"after_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchJobEventsRequest) Reset() {
	*x = WatchJobEventsRequest{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchJobEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchJobEventsRequest) ProtoMessage() {}

func (x *WatchJobEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchJobEventsRequest.ProtoReflect.Descriptor instead.
func (*WatchJobEventsRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{26}
}

func (x *WatchJobEventsRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *WatchJobEventsRequest) GetAfterSeq() uint64 {
	if x != nil {
		return x.AfterSeq
	}
	return 0
}

type JobEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Events of a job are numbered from one, in the order they happened.
	Seq uint64 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	// Milliseconds since the Unix epoch.
	AtMs int64 `protobuf:"varint,2,opt,name=at_ms,json=atMs,proto3" json:"at_ms,omitempty"`
	// What happened: submitted, task-started, task-succeeded, task-failed,
	// task-lost, task-timed-out, log, succeeded, failed, cancelled, resumed.
	Kind string `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	// The task concerned, or -1 if the event is about the job as a whole.
	TaskIndex     int32  `protobuf:"varint,4,opt,name=task_index,json=taskIndex,proto3" json:"task_index,omitempty"`
	WorkerName    string `protobuf:"bytes,5,opt,name=worker_name,json=workerName,proto3" json:"worker_name,omitempty"`
	Text          string `protobuf:"bytes,6,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobEvent) Reset() {
	*x = JobEvent{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobEvent) ProtoMessage() {}

func (x *JobEvent) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobEvent.ProtoReflect.Descriptor instead.
func (*JobEvent) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{27}
}

func (x *JobEvent) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *JobEvent) GetAtMs() int64 {
	if x != nil {
		return x.AtMs
	}
	return 0
}

func (x *JobEvent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *JobEvent) GetTaskIndex() int32 {
	if x != nil {
		return x.TaskIndex
	}
	return 0
}

func (x *JobEvent) GetWorkerName() string {
	if x != nil {
		return x.WorkerName
	}
	return ""
}

func (x *JobEvent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type GetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{28}
}

func (x *GetJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobResponse) Reset() {
	*x = GetJobResponse{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobResponse) ProtoMessage() {}

func (x *GetJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobResponse.ProtoReflect.Descriptor instead.
func (*GetJobResponse) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{29}
}

func (x *GetJobResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type ListJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsRequest) Reset() {
	*x = ListJobsRequest{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsRequest) ProtoMessage() {}

func (x *ListJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsRequest.ProtoReflect.Descriptor instead.
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{30}
}

type WatchJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchJobsRequest) Reset() {
	*x = WatchJobsRequest{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchJobsRequest) ProtoMessage() {}

func (x *WatchJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchJobsRequest.ProtoReflect.Descriptor instead.
func (*WatchJobsRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{31}
}

type ListJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*Job                 `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	Revision      uint64                 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsResponse) Reset() {
	*x = ListJobsResponse{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResponse) ProtoMessage() {}

func (x *ListJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResponse.ProtoReflect.Descriptor instead.
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{32}
}

func (x *ListJobsResponse) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *ListJobsResponse) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

var File_sisyphus_node_v1_node_proto protoreflect.FileDescriptor

const file_sisyphus_node_v1_node_proto_rawDesc = "" +
	"\n" +
	"\x1bsisyphus/node/v1/node.proto\x12\x10sisyphus.node.v1\"\x14\n" +
	"\x12GetNodeInfoRequest\"\xc1\x01\n" +
	"\x13GetNodeInfoResponse\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12%\n" +
	"\x0edaemon_version\x18\x02 \x01(\tR\rdaemonVersion\x12)\n" +
	"\x10listen_addresses\x18\x03 \x03(\tR\x0flistenAddresses\x12!\n" +
	"\fcountry_code\x18\x04 \x01(\tR\vcountryCode\x12\x1c\n" +
	"\tworkloads\x18\x05 \x03(\tR\tworkloads\"\x12\n" +
	"\x10ListPeersRequest\"\x13\n" +
	"\x11WatchPeersRequest\"\x1a\n" +
	"\x18GetBootstrapPeersRequest\"R\n" +
	"\x19GetBootstrapPeersResponse\x125\n" +
	"\x05peers\x18\x01 \x03(\v2\x1f.sisyphus.node.v1.BootstrapPeerR\x05peers\"Q\n" +
	"\x18SetBootstrapPeersRequest\x125\n" +
	"\x05peers\x18\x01 \x03(\v2\x1f.sisyphus.node.v1.BootstrapPeerR\x05peers\"R\n" +
	"\x19SetBootstrapPeersResponse\x125\n" +
	"\x05peers\x18\x01 \x03(\v2\x1f.sisyphus.node.v1.BootstrapPeerR\x05peers\".\n" +
	"\x12ConnectPeerRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\".\n" +
	"\x13ConnectPeerResponse\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\"O\n" +
	"\x1aSetPeerComputeTrustRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x18\n" +
	"\atrusted\x18\x02 \x01(\bR\atrusted\"7\n" +
	"\x1bSetPeerComputeTrustResponse\x12\x18\n" +
	"\atrusted\x18\x01 \x01(\bR\atrusted\"y\n" +
	" SetPeerComputePermissionsRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x1d\n" +
	"\n" +
	"gives_work\x18\x02 \x01(\bR\tgivesWork\x12\x1d\n" +
	"\n" +
	"takes_work\x18\x03 \x01(\bR\ttakesWork\"a\n" +
	"!SetPeerComputePermissionsResponse\x12\x1d\n" +
	"\n" +
	"gives_work\x18\x01 \x01(\bR\tgivesWork\x12\x1d\n" +
	"\n" +
	"takes_work\x18\x02 \x01(\bR\ttakesWork\"B\n" +
	"\rBootstrapPeer\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"]\n" +
	"\x11ListPeersResponse\x12,\n" +
	"\x05peers\x18\x01 \x03(\v2\x16.sisyphus.node.v1.PeerR\x05peers\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision\"\xe6\x02\n" +
	"\x04Peer\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12P\n" +
	"\x10connection_state\x18\x02 \x01(\x0e2%.sisyphus.node.v1.PeerConnectionStateR\x0fconnectionState\x12'\n" +
	"\x0fknown_addresses\x18\x03 \x03(\tR\x0eknownAddresses\x12.\n" +
	"\x13trusted_for_compute\x18\x04 \x01(\bR\x11trustedForCompute\x12-\n" +
	"\x13works_for_this_node\x18\x05 \x01(\bR\x10worksForThisNode\x12-\n" +
	"\x13this_node_works_for\x18\x06 \x01(\bR\x10thisNodeWorksFor\x12\x1d\n" +
	"\n" +
	"gives_work\x18\a \x01(\bR\tgivesWork\x12\x1d\n" +
	"\n" +
	"takes_work\x18\b \x01(\bR\ttakesWork\"\x14\n" +
	"\x12ListWorkersRequest\"I\n" +
	"\x13ListWorkersResponse\x122\n" +
	"\aworkers\x18\x01 \x03(\v2\x18.sisyphus.node.v1.WorkerR\aworkers\"\xe2\x02\n" +
	"\x06Worker\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x05 \x01(\tR\x04arch\x12\x1b\n" +
	"\tcpu_cores\x18\x06 \x01(\rR\bcpuCores\x12\x1d\n" +
	"\n" +
	"task_slots\x18\a \x01(\rR\ttaskSlots\x12#\n" +
	"\rrunning_tasks\x18\b \x01(\rR\frunningTasks\x12\x1c\n" +
	"\tworkloads\x18\t \x03(\tR\tworkloads\x12\x16\n" +
	"\x06relays\x18\n" +
	" \x01(\bR\x06relays\x12/\n" +
	"\x13relayed_connections\x18\v \x01(\x04R\x12relayedConnections\x12#\n" +
	"\rrelayed_bytes\x18\f \x01(\x04R\frelayedBytes\"\xec\x03\n" +
	"\x03Job\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1a\n" +
	"\bworkload\x18\x02 \x01(\tR\bworkload\x12\x16\n" +
	"\x06params\x18\x03 \x01(\fR\x06params\x12-\n" +
	"\x04mode\x18\x04 \x01(\x0e2\x19.sisyphus.node.v1.JobModeR\x04mode\x120\n" +
	"\x05state\x18\x05 \x01(\x0e2\x1a.sisyphus.node.v1.JobStateR\x05state\x12/\n" +
	"\x05tasks\x18\x06 \x03(\v2\x19.sisyphus.node.v1.JobTaskR\x05tasks\x12\x16\n" +
	"\x06result\x18\a \x01(\fR\x06result\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x12\"\n" +
	"\rcreated_at_ms\x18\t \x01(\x03R\vcreatedAtMs\x12$\n" +
	"\x0efinished_at_ms\x18\n" +
	" \x01(\x03R\ffinishedAtMs\x12\x1f\n" +
	"\vinput_blobs\x18\v \x03(\tR\n" +
	"inputBlobs\x12!\n" +
	"\foutput_blobs\x18\f \x03(\tR\voutputBlobs\x12\x1a\n" +
	"\bprogress\x18\r \x01(\x01R\bprogress\x120\n" +
	"\x14task_timeout_seconds\x18\x0e \x01(\rR\x12taskTimeoutSeconds\"\xd7\x01\n" +
	"\aJobTask\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x120\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1a.sisyphus.node.v1.JobStateR\x05state\x12\x18\n" +
	"\aattempt\x18\x03 \x01(\rR\aattempt\x12\x17\n" +
	"\apeer_id\x18\x04 \x01(\tR\x06peerId\x12\x1f\n" +
	"\vworker_name\x18\x05 \x01(\tR\n" +
	"workerName\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12\x1a\n" +
	"\bprogress\x18\a \x01(\x01R\bprogress\"\xc4\x01\n" +
	"\x10SubmitJobRequest\x12\x1a\n" +
	"\bworkload\x18\x01 \x01(\tR\bworkload\x12\x16\n" +
	"\x06params\x18\x02 \x01(\fR\x06params\x12-\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x19.sisyphus.node.v1.JobModeR\x04mode\x12\x1b\n" +
	"\tmax_tasks\x18\x04 \x01(\rR\bmaxTasks\x120\n" +
	"\x14task_timeout_seconds\x18\x05 \x01(\rR\x12taskTimeoutSeconds\"<\n" +
	"\x11SubmitJobResponse\x12'\n" +
	"\x03job\x18\x01 \x01(\v2\x15.sisyphus.node.v1.JobR\x03job\")\n" +
	"\x10CancelJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"<\n" +
	"\x11CancelJobResponse\x12'\n" +
	"\x03job\x18\x01 \x01(\v2\x15.sisyphus.node.v1.JobR\x03job\"K\n" +
	"\x15WatchJobEventsRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tafter_seq\x18\x02 \x01(\x04R\bafterSeq\"\x99\x01\n" +
	"\bJobEvent\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x13\n" +
	"\x05at_ms\x18\x02 \x01(\x03R\x04atMs\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x1d\n" +
	"\n" +
	"task_index\x18\x04 \x01(\x05R\ttaskIndex\x12\x1f\n" +
	"\vworker_name\x18\x05 \x01(\tR\n" +
	"workerName\x12\x12\n" +
	"\x04text\x18\x06 \x01(\tR\x04text\"&\n" +
	"\rGetJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"9\n" +
	"\x0eGetJobResponse\x12'\n" +
	"\x03job\x18\x01 \x01(\v2\x15.sisyphus.node.v1.JobR\x03job\"\x11\n" +
	"\x0fListJobsRequest\"\x12\n" +
	"\x10WatchJobsRequest\"Y\n" +
	"\x10ListJobsResponse\x12)\n" +
	"\x04jobs\x18\x01 \x03(\v2\x15.sisyphus.node.v1.JobR\x04jobs\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision*\x89\x01\n" +
	"\x13PeerConnectionState\x12%\n" +
	"!PEER_CONNECTION_STATE_UNSPECIFIED\x10\x00\x12&\n" +
	"\"PEER_CONNECTION_STATE_DISCONNECTED\x10\x01\x12#\n" +
	"\x1fPEER_CONNECTION_STATE_CONNECTED\x10\x02*\x9b\x01\n" +
	"\bJobState\x12\x19\n" +
	"\x15JOB_STATE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11JOB_STATE_PENDING\x10\x01\x12\x15\n" +
	"\x11JOB_STATE_RUNNING\x10\x02\x12\x17\n" +
	"\x13JOB_STATE_SUCCEEDED\x10\x03\x12\x14\n" +
	"\x10JOB_STATE_FAILED\x10\x04\x12\x17\n" +
	"\x13JOB_STATE_CANCELLED\x10\x05*W\n" +
	"\aJobMode\x12\x18\n" +
	"\x14JOB_MODE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14JOB_MODE_DISTRIBUTED\x10\x01\x12\x18\n" +
	"\x14JOB_MODE_FULL_WORKER\x10\x022\xa4\v\n" +
	"\vNodeService\x12Z\n" +
	"\vGetNodeInfo\x12$.sisyphus.node.v1.GetNodeInfoRequest\x1a%.sisyphus.node.v1.GetNodeInfoResponse\x12T\n" +
	"\tListPeers\x12\".sisyphus.node.v1.ListPeersRequest\x1a#.sisyphus.node.v1.ListPeersResponse\x12X\n" +
	"\n" +
	"WatchPeers\x12#.sisyphus.node.v1.WatchPeersRequest\x1a#.sisyphus.node.v1.ListPeersResponse0\x01\x12l\n" +
	"\x11GetBootstrapPeers\x12*.sisyphus.node.v1.GetBootstrapPeersRequest\x1a+.sisyphus.node.v1.GetBootstrapPeersResponse\x12l\n" +
	"\x11SetBootstrapPeers\x12*.sisyphus.node.v1.SetBootstrapPeersRequest\x1a+.sisyphus.node.v1.SetBootstrapPeersResponse\x12Z\n" +
	"\vConnectPeer\x12$.sisyphus.node.v1.ConnectPeerRequest\x1a%.sisyphus.node.v1.ConnectPeerResponse\x12r\n" +
	"\x13SetPeerComputeTrust\x12,.sisyphus.node.v1.SetPeerComputeTrustRequest\x1a-.sisyphus.node.v1.SetPeerComputeTrustResponse\x12\x84\x01\n" +
	"\x19SetPeerComputePermissions\x122.sisyphus.node.v1.SetPeerComputePermissionsRequest\x1a3.sisyphus.node.v1.SetPeerComputePermissionsResponse\x12Z\n" +
	"\vListWorkers\x12$.sisyphus.node.v1.ListWorkersRequest\x1a%.sisyphus.node.v1.ListWorkersResponse\x12T\n" +
	"\tSubmitJob\x12\".sisyphus.node.v1.SubmitJobRequest\x1a#.sisyphus.node.v1.SubmitJobResponse\x12K\n" +
	"\x06GetJob\x12\x1f.sisyphus.node.v1.GetJobRequest\x1a .sisyphus.node.v1.GetJobResponse\x12Q\n" +
	"\bListJobs\x12!.sisyphus.node.v1.ListJobsRequest\x1a\".sisyphus.node.v1.ListJobsResponse\x12U\n" +
	"\tWatchJobs\x12\".sisyphus.node.v1.WatchJobsRequest\x1a\".sisyphus.node.v1.ListJobsResponse0\x01\x12T\n" +
	"\tCancelJob\x12\".sisyphus.node.v1.CancelJobRequest\x1a#.sisyphus.node.v1.CancelJobResponse\x12W\n" +
	"\x0eWatchJobEvents\x12'.sisyphus.node.v1.WatchJobEventsRequest\x1a\x1a.sisyphus.node.v1.JobEvent0\x01BPZNgithub.com/sisyphus-network/Sisyphus/packages/protocol/sisyphus/node/v1;nodev1b\x06proto3"

var (
	file_sisyphus_node_v1_node_proto_rawDescOnce sync.Once
	file_sisyphus_node_v1_node_proto_rawDescData []byte
)

func file_sisyphus_node_v1_node_proto_rawDescGZIP() []byte {
	file_sisyphus_node_v1_node_proto_rawDescOnce.Do(func() {
		file_sisyphus_node_v1_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sisyphus_node_v1_node_proto_rawDesc), len(file_sisyphus_node_v1_node_proto_rawDesc)))
	})
	return file_sisyphus_node_v1_node_proto_rawDescData
}

var file_sisyphus_node_v1_node_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_sisyphus_node_v1_node_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_sisyphus_node_v1_node_proto_goTypes = []any{
	(PeerConnectionState)(0),                  // 0: sisyphus.node.v1.PeerConnectionState
	(JobState)(0),                             // 1: sisyphus.node.v1.JobState
	(JobMode)(0),                              // 2: sisyphus.node.v1.JobMode
	(*GetNodeInfoRequest)(nil),                // 3: sisyphus.node.v1.GetNodeInfoRequest
	(*GetNodeInfoResponse)(nil),               // 4: sisyphus.node.v1.GetNodeInfoResponse
	(*ListPeersRequest)(nil),                  // 5: sisyphus.node.v1.ListPeersRequest
	(*WatchPeersRequest)(nil),                 // 6: sisyphus.node.v1.WatchPeersRequest
	(*GetBootstrapPeersRequest)(nil),          // 7: sisyphus.node.v1.GetBootstrapPeersRequest
	(*GetBootstrapPeersResponse)(nil),         // 8: sisyphus.node.v1.GetBootstrapPeersResponse
	(*SetBootstrapPeersRequest)(nil),          // 9: sisyphus.node.v1.SetBootstrapPeersRequest
	(*SetBootstrapPeersResponse)(nil),         // 10: sisyphus.node.v1.SetBootstrapPeersResponse
	(*ConnectPeerRequest)(nil),                // 11: sisyphus.node.v1.ConnectPeerRequest
	(*ConnectPeerResponse)(nil),               // 12: sisyphus.node.v1.ConnectPeerResponse
	(*SetPeerComputeTrustRequest)(nil),        // 13: sisyphus.node.v1.SetPeerComputeTrustRequest
	(*SetPeerComputeTrustResponse)(nil),       // 14: sisyphus.node.v1.SetPeerComputeTrustResponse
	(*SetPeerComputePermissionsRequest)(nil),  // 15: sisyphus.node.v1.SetPeerComputePermissionsRequest
	(*SetPeerComputePermissionsResponse)(nil), // 16: sisyphus.node.v1.SetPeerComputePermissionsResponse
	(*BootstrapPeer)(nil),                     // 17: sisyphus.node.v1.BootstrapPeer
	(*ListPeersResponse)(nil),                 // 18: sisyphus.node.v1.ListPeersResponse
	(*Peer)(nil),                              // 19: sisyphus.node.v1.Peer
	(*ListWorkersRequest)(nil),                // 20: sisyphus.node.v1.ListWorkersRequest
	(*ListWorkersResponse)(nil),               // 21: sisyphus.node.v1.ListWorkersResponse
	(*Worker)(nil),                            // 22: sisyphus.node.v1.Worker
	(*Job)(nil),                               // 23: sisyphus.node.v1.Job
	(*JobTask)(nil),                           // 24: sisyphus.node.v1.JobTask
	(*SubmitJobRequest)(nil),                  // 25: sisyphus.node.v1.SubmitJobRequest
	(*SubmitJobResponse)(nil),                 // 26: sisyphus.node.v1.SubmitJobResponse
	(*CancelJobRequest)(nil),                  // 27: sisyphus.node.v1.CancelJobRequest
	(*CancelJobResponse)(nil),                 // 28: sisyphus.node.v1.CancelJobResponse
	(*WatchJobEventsRequest)(nil),             // 29: sisyphus.node.v1.WatchJobEventsRequest
	(*JobEvent)(nil),                          // 30: sisyphus.node.v1.JobEvent
	(*GetJobRequest)(nil),                     // 31: sisyphus.node.v1.GetJobRequest
	(*GetJobResponse)(nil),                    // 32: sisyphus.node.v1.GetJobResponse
	(*ListJobsRequest)(nil),                   // 33: sisyphus.node.v1.ListJobsRequest
	(*WatchJobsRequest)(nil),                  // 34: sisyphus.node.v1.WatchJobsRequest
	(*ListJobsResponse)(nil),                  // 35: sisyphus.node.v1.ListJobsResponse
}
var file_sisyphus_node_v1_node_proto_depIdxs = []int32{
	17, // 0: sisyphus.node.v1.GetBootstrapPeersResponse.peers:type_name -> sisyphus.node.v1.BootstrapPeer
	17, // 1: sisyphus.node.v1.SetBootstrapPeersRequest.peers:type_name -> sisyphus.node.v1.BootstrapPeer
	17, // 2: sisyphus.node.v1.SetBootstrapPeersResponse.peers:type_name -> sisyphus.node.v1.BootstrapPeer
	19, // 3: sisyphus.node.v1.ListPeersResponse.peers:type_name -> sisyphus.node.v1.Peer
	0,  // 4: sisyphus.node.v1.Peer.connection_state:type_name -> sisyphus.node.v1.PeerConnectionState
	22, // 5: sisyphus.node.v1.ListWorkersResponse.workers:type_name -> sisyphus.node.v1.Worker
	2,  // 6: sisyphus.node.v1.Job.mode:type_name -> sisyphus.node.v1.JobMode
	1,  // 7: sisyphus.node.v1.Job.state:type_name -> sisyphus.node.v1.JobState
	24, // 8: sisyphus.node.v1.Job.tasks:type_name -> sisyphus.node.v1.JobTask
	1,  // 9: sisyphus.node.v1.JobTask.state:type_name -> sisyphus.node.v1.JobState
	2,  // 10: sisyphus.node.v1.SubmitJobRequest.mode:type_name -> sisyphus.node.v1.JobMode
	23, // 11: sisyphus.node.v1.SubmitJobResponse.job:type_name -> sisyphus.node.v1.Job
	23, // 12: sisyphus.node.v1.CancelJobResponse.job:type_name -> sisyphus.node.v1.Job
	23, // 13: sisyphus.node.v1.GetJobResponse.job:type_name -> sisyphus.node.v1.Job
	23, // 14: sisyphus.node.v1.ListJobsResponse.jobs:type_name -> sisyphus.node.v1.Job
	3,  // 15: sisyphus.node.v1.NodeService.GetNodeInfo:input_type -> sisyphus.node.v1.GetNodeInfoRequest
	5,  // 16: sisyphus.node.v1.NodeService.ListPeers:input_type -> sisyphus.node.v1.ListPeersRequest
	6,  // 17: sisyphus.node.v1.NodeService.WatchPeers:input_type -> sisyphus.node.v1.WatchPeersRequest
	7,  // 18: sisyphus.node.v1.NodeService.GetBootstrapPeers:input_type -> sisyphus.node.v1.GetBootstrapPeersRequest
	9,  // 19: sisyphus.node.v1.NodeService.SetBootstrapPeers:input_type -> sisyphus.node.v1.SetBootstrapPeersRequest
	11, // 20: sisyphus.node.v1.NodeService.ConnectPeer:input_type -> sisyphus.node.v1.ConnectPeerRequest
	13, // 21: sisyphus.node.v1.NodeService.SetPeerComputeTrust:input_type -> sisyphus.node.v1.SetPeerComputeTrustRequest
	15, // 22: sisyphus.node.v1.NodeService.SetPeerComputePermissions:input_type -> sisyphus.node.v1.SetPeerComputePermissionsRequest
	20, // 23: sisyphus.node.v1.NodeService.ListWorkers:input_type -> sisyphus.node.v1.ListWorkersRequest
	25, // 24: sisyphus.node.v1.NodeService.SubmitJob:input_type -> sisyphus.node.v1.SubmitJobRequest
	31, // 25: sisyphus.node.v1.NodeService.GetJob:input_type -> sisyphus.node.v1.GetJobRequest
	33, // 26: sisyphus.node.v1.NodeService.ListJobs:input_type -> sisyphus.node.v1.ListJobsRequest
	34, // 27: sisyphus.node.v1.NodeService.WatchJobs:input_type -> sisyphus.node.v1.WatchJobsRequest
	27, // 28: sisyphus.node.v1.NodeService.CancelJob:input_type -> sisyphus.node.v1.CancelJobRequest
	29, // 29: sisyphus.node.v1.NodeService.WatchJobEvents:input_type -> sisyphus.node.v1.WatchJobEventsRequest
	4,  // 30: sisyphus.node.v1.NodeService.GetNodeInfo:output_type -> sisyphus.node.v1.GetNodeInfoResponse
	18, // 31: sisyphus.node.v1.NodeService.ListPeers:output_type -> sisyphus.node.v1.ListPeersResponse
	18, // 32: sisyphus.node.v1.NodeService.WatchPeers:output_type -> sisyphus.node.v1.ListPeersResponse
	8,  // 33: sisyphus.node.v1.NodeService.GetBootstrapPeers:output_type -> sisyphus.node.v1.GetBootstrapPeersResponse
	10, // 34: sisyphus.node.v1.NodeService.SetBootstrapPeers:output_type -> sisyphus.node.v1.SetBootstrapPeersResponse
	12, // 35: sisyphus.node.v1.NodeService.ConnectPeer:output_type -> sisyphus.node.v1.ConnectPeerResponse
	14, // 36: sisyphus.node.v1.NodeService.SetPeerComputeTrust:output_type -> sisyphus.node.v1.SetPeerComputeTrustResponse
	16, // 37: sisyphus.node.v1.NodeService.SetPeerComputePermissions:output_type -> sisyphus.node.v1.SetPeerComputePermissionsResponse
	21, // 38: sisyphus.node.v1.NodeService.ListWorkers:output_type -> sisyphus.node.v1.ListWorkersResponse
	26, // 39: sisyphus.node.v1.NodeService.SubmitJob:output_type -> sisyphus.node.v1.SubmitJobResponse
	32, // 40: sisyphus.node.v1.NodeService.GetJob:output_type -> sisyphus.node.v1.GetJobResponse
	35, // 41: sisyphus.node.v1.NodeService.ListJobs:output_type -> sisyphus.node.v1.ListJobsResponse
	35, // 42: sisyphus.node.v1.NodeService.WatchJobs:output_type -> sisyphus.node.v1.ListJobsResponse
	28, // 43: sisyphus.node.v1.NodeService.CancelJob:output_type -> sisyphus.node.v1.CancelJobResponse
	30, // 44: sisyphus.node.v1.NodeService.WatchJobEvents:output_type -> sisyphus.node.v1.JobEvent
	30, // [30:45] is the sub-list for method output_type
	15, // [15:30] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_sisyphus_node_v1_node_proto_init() }
func file_sisyphus_node_v1_node_proto_init() {
	if File_sisyphus_node_v1_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sisyphus_node_v1_node_proto_rawDesc), len(file_sisyphus_node_v1_node_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sisyphus_node_v1_node_proto_goTypes,
		DependencyIndexes: file_sisyphus_node_v1_node_proto_depIdxs,
		EnumInfos:         file_sisyphus_node_v1_node_proto_enumTypes,
		MessageInfos:      file_sisyphus_node_v1_node_proto_msgTypes,
	}.Build()
	File_sisyphus_node_v1_node_proto = out.File
	file_sisyphus_node_v1_node_proto_goTypes = nil
	file_sisyphus_node_v1_node_proto_depIdxs = nil
}
