// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: sisyphus/node/v1/node.proto

package nodev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PeerConnectionState int32

const (
	PeerConnectionState_PEER_CONNECTION_STATE_UNSPECIFIED  PeerConnectionState = 0
	PeerConnectionState_PEER_CONNECTION_STATE_DISCONNECTED PeerConnectionState = 1
	PeerConnectionState_PEER_CONNECTION_STATE_CONNECTED    PeerConnectionState = 2
)

// Enum value maps for PeerConnectionState.
var (
	PeerConnectionState_name = map[int32]string{
		0: "PEER_CONNECTION_STATE_UNSPECIFIED",
		1: "PEER_CONNECTION_STATE_DISCONNECTED",
		2: "PEER_CONNECTION_STATE_CONNECTED",
	}
	PeerConnectionState_value = map[string]int32{
		"PEER_CONNECTION_STATE_UNSPECIFIED":  0,
		"PEER_CONNECTION_STATE_DISCONNECTED": 1,
		"PEER_CONNECTION_STATE_CONNECTED":    2,
	}
)

func (x PeerConnectionState) Enum() *PeerConnectionState {
	p := new(PeerConnectionState)
	*p = x
	return p
}

func (x PeerConnectionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PeerConnectionState) Descriptor() protoreflect.EnumDescriptor {
	return file_sisyphus_node_v1_node_proto_enumTypes[0].Descriptor()
}

func (PeerConnectionState) Type() protoreflect.EnumType {
	return &file_sisyphus_node_v1_node_proto_enumTypes[0]
}

func (x PeerConnectionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PeerConnectionState.Descriptor instead.
func (PeerConnectionState) EnumDescriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{0}
}

type GetNodeInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeInfoRequest) Reset() {
	*x = GetNodeInfoRequest{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeInfoRequest) ProtoMessage() {}

func (x *GetNodeInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeInfoRequest.ProtoReflect.Descriptor instead.
func (*GetNodeInfoRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{0}
}

type GetNodeInfoResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PeerId          string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	DaemonVersion   string                 `protobuf:"bytes,2,opt,name=daemon_version,json=daemonVersion,proto3" json:"daemon_version,omitempty"`
	ListenAddresses []string               `protobuf:"bytes,3,rep,name=listen_addresses,json=listenAddresses,proto3" json:"listen_addresses,omitempty"`
	CountryCode     string                 `protobuf:"bytes,4,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetNodeInfoResponse) Reset() {
	*x = GetNodeInfoResponse{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeInfoResponse) ProtoMessage() {}

func (x *GetNodeInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeInfoResponse.ProtoReflect.Descriptor instead.
func (*GetNodeInfoResponse) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{1}
}

func (x *GetNodeInfoResponse) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *GetNodeInfoResponse) GetDaemonVersion() string {
	if x != nil {
		return x.DaemonVersion
	}
	return ""
}

func (x *GetNodeInfoResponse) GetListenAddresses() []string {
	if x != nil {
		return x.ListenAddresses
	}
	return nil
}

func (x *GetNodeInfoResponse) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

type ListPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPeersRequest) Reset() {
	*x = ListPeersRequest{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeersRequest) ProtoMessage() {}

func (x *ListPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeersRequest.ProtoReflect.Descriptor instead.
func (*ListPeersRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{2}
}

type WatchPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchPeersRequest) Reset() {
	*x = WatchPeersRequest{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchPeersRequest) ProtoMessage() {}

func (x *WatchPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchPeersRequest.ProtoReflect.Descriptor instead.
func (*WatchPeersRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{3}
}

type GetBootstrapPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBootstrapPeersRequest) Reset() {
	*x = GetBootstrapPeersRequest{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBootstrapPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBootstrapPeersRequest) ProtoMessage() {}

func (x *GetBootstrapPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBootstrapPeersRequest.ProtoReflect.Descriptor instead.
func (*GetBootstrapPeersRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{4}
}

type GetBootstrapPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*BootstrapPeer       `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBootstrapPeersResponse) Reset() {
	*x = GetBootstrapPeersResponse{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBootstrapPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBootstrapPeersResponse) ProtoMessage() {}

func (x *GetBootstrapPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBootstrapPeersResponse.ProtoReflect.Descriptor instead.
func (*GetBootstrapPeersResponse) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{5}
}

func (x *GetBootstrapPeersResponse) GetPeers() []*BootstrapPeer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type SetBootstrapPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*BootstrapPeer       `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBootstrapPeersRequest) Reset() {
	*x = SetBootstrapPeersRequest{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBootstrapPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBootstrapPeersRequest) ProtoMessage() {}

func (x *SetBootstrapPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBootstrapPeersRequest.ProtoReflect.Descriptor instead.
func (*SetBootstrapPeersRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{6}
}

func (x *SetBootstrapPeersRequest) GetPeers() []*BootstrapPeer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type SetBootstrapPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*BootstrapPeer       `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBootstrapPeersResponse) Reset() {
	*x = SetBootstrapPeersResponse{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBootstrapPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBootstrapPeersResponse) ProtoMessage() {}

func (x *SetBootstrapPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBootstrapPeersResponse.ProtoReflect.Descriptor instead.
func (*SetBootstrapPeersResponse) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{7}
}

func (x *SetBootstrapPeersResponse) GetPeers() []*BootstrapPeer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type ConnectPeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectPeerRequest) Reset() {
	*x = ConnectPeerRequest{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectPeerRequest) ProtoMessage() {}

func (x *ConnectPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectPeerRequest.ProtoReflect.Descriptor instead.
func (*ConnectPeerRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{8}
}

func (x *ConnectPeerRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type ConnectPeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectPeerResponse) Reset() {
	*x = ConnectPeerResponse{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectPeerResponse) ProtoMessage() {}

func (x *ConnectPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectPeerResponse.ProtoReflect.Descriptor instead.
func (*ConnectPeerResponse) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{9}
}

func (x *ConnectPeerResponse) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

type SetPeerComputeTrustRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Trusted       bool                   `protobuf:"varint,2,opt,name=trusted,proto3" json:"trusted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPeerComputeTrustRequest) Reset() {
	*x = SetPeerComputeTrustRequest{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPeerComputeTrustRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPeerComputeTrustRequest) ProtoMessage() {}

func (x *SetPeerComputeTrustRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPeerComputeTrustRequest.ProtoReflect.Descriptor instead.
func (*SetPeerComputeTrustRequest) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{10}
}

func (x *SetPeerComputeTrustRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *SetPeerComputeTrustRequest) GetTrusted() bool {
	if x != nil {
		return x.Trusted
	}
	return false
}

type SetPeerComputeTrustResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trusted       bool                   `protobuf:"varint,1,opt,name=trusted,proto3" json:"trusted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPeerComputeTrustResponse) Reset() {
	*x = SetPeerComputeTrustResponse{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPeerComputeTrustResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPeerComputeTrustResponse) ProtoMessage() {}

func (x *SetPeerComputeTrustResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPeerComputeTrustResponse.ProtoReflect.Descriptor instead.
func (*SetPeerComputeTrustResponse) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{11}
}

func (x *SetPeerComputeTrustResponse) GetTrusted() bool {
	if x != nil {
		return x.Trusted
	}
	return false
}

type BootstrapPeer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapPeer) Reset() {
	*x = BootstrapPeer{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapPeer) ProtoMessage() {}

func (x *BootstrapPeer) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapPeer.ProtoReflect.Descriptor instead.
func (*BootstrapPeer) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{12}
}

func (x *BootstrapPeer) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *BootstrapPeer) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type ListPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*Peer                `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	Revision      uint64                 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPeersResponse) Reset() {
	*x = ListPeersResponse{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeersResponse) ProtoMessage() {}

func (x *ListPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeersResponse.ProtoReflect.Descriptor instead.
func (*ListPeersResponse) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{13}
}

func (x *ListPeersResponse) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *ListPeersResponse) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type Peer struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PeerId            string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	ConnectionState   PeerConnectionState    `protobuf:"varint,2,opt,name=connection_state,json=connectionState,proto3,enum=sisyphus.node.v1.PeerConnectionState" json:"connection_state,omitempty"`
	KnownAddresses    []string               `protobuf:"bytes,3,rep,name=known_addresses,json=knownAddresses,proto3" json:"known_addresses,omitempty"`
	TrustedForCompute bool                   `protobuf:"varint,4,opt,name=trusted_for_compute,json=trustedForCompute,proto3" json:"trusted_for_compute,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_sisyphus_node_v1_node_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_sisyphus_node_v1_node_proto_rawDescGZIP(), []int{14}
}

func (x *Peer) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *Peer) GetConnectionState() PeerConnectionState {
	if x != nil {
		return x.ConnectionState
	}
	return PeerConnectionState_PEER_CONNECTION_STATE_UNSPECIFIED
}

func (x *Peer) GetKnownAddresses() []string {
	if x != nil {
		return x.KnownAddresses
	}
	return nil
}

func (x *Peer) GetTrustedForCompute() bool {
	if x != nil {
		return x.TrustedForCompute
	}
	return false
}

var File_sisyphus_node_v1_node_proto protoreflect.FileDescriptor

const file_sisyphus_node_v1_node_proto_rawDesc = "" +
	"\n" +
	"\x1bsisyphus/node/v1/node.proto\x12\x10sisyphus.node.v1\"\x14\n" +
	"\x12GetNodeInfoRequest\"\xa3\x01\n" +
	"\x13GetNodeInfoResponse\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12%\n" +
	"\x0edaemon_version\x18\x02 \x01(\tR\rdaemonVersion\x12)\n" +
	"\x10listen_addresses\x18\x03 \x03(\tR\x0flistenAddresses\x12!\n" +
	"\fcountry_code\x18\x04 \x01(\tR\vcountryCode\"\x12\n" +
	"\x10ListPeersRequest\"\x13\n" +
	"\x11WatchPeersRequest\"\x1a\n" +
	"\x18GetBootstrapPeersRequest\"R\n" +
	"\x19GetBootstrapPeersResponse\x125\n" +
	"\x05peers\x18\x01 \x03(\v2\x1f.sisyphus.node.v1.BootstrapPeerR\x05peers\"Q\n" +
	"\x18SetBootstrapPeersRequest\x125\n" +
	"\x05peers\x18\x01 \x03(\v2\x1f.sisyphus.node.v1.BootstrapPeerR\x05peers\"R\n" +
	"\x19SetBootstrapPeersResponse\x125\n" +
	"\x05peers\x18\x01 \x03(\v2\x1f.sisyphus.node.v1.BootstrapPeerR\x05peers\".\n" +
	"\x12ConnectPeerRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\".\n" +
	"\x13ConnectPeerResponse\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\"O\n" +
	"\x1aSetPeerComputeTrustRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x18\n" +
	"\atrusted\x18\x02 \x01(\bR\atrusted\"7\n" +
	"\x1bSetPeerComputeTrustResponse\x12\x18\n" +
	"\atrusted\x18\x01 \x01(\bR\atrusted\"B\n" +
	"\rBootstrapPeer\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"]\n" +
	"\x11ListPeersResponse\x12,\n" +
	"\x05peers\x18\x01 \x03(\v2\x16.sisyphus.node.v1.PeerR\x05peers\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision\"\xca\x01\n" +
	"\x04Peer\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12P\n" +
	"\x10connection_state\x18\x02 \x01(\x0e2%.sisyphus.node.v1.PeerConnectionStateR\x0fconnectionState\x12'\n" +
	"\x0fknown_addresses\x18\x03 \x03(\tR\x0eknownAddresses\x12.\n" +
	"\x13trusted_for_compute\x18\x04 \x01(\bR\x11trustedForCompute*\x89\x01\n" +
	"\x13PeerConnectionState\x12%\n" +
	"!PEER_CONNECTION_STATE_UNSPECIFIED\x10\x00\x12&\n" +
	"\"PEER_CONNECTION_STATE_DISCONNECTED\x10\x01\x12#\n" +
	"\x1fPEER_CONNECTION_STATE_CONNECTED\x10\x022\xc5\x05\n" +
	"\vNodeService\x12Z\n" +
	"\vGetNodeInfo\x12$.sisyphus.node.v1.GetNodeInfoRequest\x1a%.sisyphus.node.v1.GetNodeInfoResponse\x12T\n" +
	"\tListPeers\x12\".sisyphus.node.v1.ListPeersRequest\x1a#.sisyphus.node.v1.ListPeersResponse\x12X\n" +
	"\n" +
	"WatchPeers\x12#.sisyphus.node.v1.WatchPeersRequest\x1a#.sisyphus.node.v1.ListPeersResponse0\x01\x12l\n" +
	"\x11GetBootstrapPeers\x12*.sisyphus.node.v1.GetBootstrapPeersRequest\x1a+.sisyphus.node.v1.GetBootstrapPeersResponse\x12l\n" +
	"\x11SetBootstrapPeers\x12*.sisyphus.node.v1.SetBootstrapPeersRequest\x1a+.sisyphus.node.v1.SetBootstrapPeersResponse\x12Z\n" +
	"\vConnectPeer\x12$.sisyphus.node.v1.ConnectPeerRequest\x1a%.sisyphus.node.v1.ConnectPeerResponse\x12r\n" +
	"\x13SetPeerComputeTrust\x12,.sisyphus.node.v1.SetPeerComputeTrustRequest\x1a-.sisyphus.node.v1.SetPeerComputeTrustResponseBFZDgithub.com/excho0/Sisyphus/packages/protocol/sisyphus/node/v1;nodev1b\x06proto3"

var (
	file_sisyphus_node_v1_node_proto_rawDescOnce sync.Once
	file_sisyphus_node_v1_node_proto_rawDescData []byte
)

func file_sisyphus_node_v1_node_proto_rawDescGZIP() []byte {
	file_sisyphus_node_v1_node_proto_rawDescOnce.Do(func() {
		file_sisyphus_node_v1_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sisyphus_node_v1_node_proto_rawDesc), len(file_sisyphus_node_v1_node_proto_rawDesc)))
	})
	return file_sisyphus_node_v1_node_proto_rawDescData
}

var file_sisyphus_node_v1_node_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sisyphus_node_v1_node_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_sisyphus_node_v1_node_proto_goTypes = []any{
	(PeerConnectionState)(0),            // 0: sisyphus.node.v1.PeerConnectionState
	(*GetNodeInfoRequest)(nil),          // 1: sisyphus.node.v1.GetNodeInfoRequest
	(*GetNodeInfoResponse)(nil),         // 2: sisyphus.node.v1.GetNodeInfoResponse
	(*ListPeersRequest)(nil),            // 3: sisyphus.node.v1.ListPeersRequest
	(*WatchPeersRequest)(nil),           // 4: sisyphus.node.v1.WatchPeersRequest
	(*GetBootstrapPeersRequest)(nil),    // 5: sisyphus.node.v1.GetBootstrapPeersRequest
	(*GetBootstrapPeersResponse)(nil),   // 6: sisyphus.node.v1.GetBootstrapPeersResponse
	(*SetBootstrapPeersRequest)(nil),    // 7: sisyphus.node.v1.SetBootstrapPeersRequest
	(*SetBootstrapPeersResponse)(nil),   // 8: sisyphus.node.v1.SetBootstrapPeersResponse
	(*ConnectPeerRequest)(nil),          // 9: sisyphus.node.v1.ConnectPeerRequest
	(*ConnectPeerResponse)(nil),         // 10: sisyphus.node.v1.ConnectPeerResponse
	(*SetPeerComputeTrustRequest)(nil),  // 11: sisyphus.node.v1.SetPeerComputeTrustRequest
	(*SetPeerComputeTrustResponse)(nil), // 12: sisyphus.node.v1.SetPeerComputeTrustResponse
	(*BootstrapPeer)(nil),               // 13: sisyphus.node.v1.BootstrapPeer
	(*ListPeersResponse)(nil),           // 14: sisyphus.node.v1.ListPeersResponse
	(*Peer)(nil),                        // 15: sisyphus.node.v1.Peer
}
var file_sisyphus_node_v1_node_proto_depIdxs = []int32{
	13, // 0: sisyphus.node.v1.GetBootstrapPeersResponse.peers:type_name -> sisyphus.node.v1.BootstrapPeer
	13, // 1: sisyphus.node.v1.SetBootstrapPeersRequest.peers:type_name -> sisyphus.node.v1.BootstrapPeer
	13, // 2: sisyphus.node.v1.SetBootstrapPeersResponse.peers:type_name -> sisyphus.node.v1.BootstrapPeer
	15, // 3: sisyphus.node.v1.ListPeersResponse.peers:type_name -> sisyphus.node.v1.Peer
	0,  // 4: sisyphus.node.v1.Peer.connection_state:type_name -> sisyphus.node.v1.PeerConnectionState
	1,  // 5: sisyphus.node.v1.NodeService.GetNodeInfo:input_type -> sisyphus.node.v1.GetNodeInfoRequest
	3,  // 6: sisyphus.node.v1.NodeService.ListPeers:input_type -> sisyphus.node.v1.ListPeersRequest
	4,  // 7: sisyphus.node.v1.NodeService.WatchPeers:input_type -> sisyphus.node.v1.WatchPeersRequest
	5,  // 8: sisyphus.node.v1.NodeService.GetBootstrapPeers:input_type -> sisyphus.node.v1.GetBootstrapPeersRequest
	7,  // 9: sisyphus.node.v1.NodeService.SetBootstrapPeers:input_type -> sisyphus.node.v1.SetBootstrapPeersRequest
	9,  // 10: sisyphus.node.v1.NodeService.ConnectPeer:input_type -> sisyphus.node.v1.ConnectPeerRequest
	11, // 11: sisyphus.node.v1.NodeService.SetPeerComputeTrust:input_type -> sisyphus.node.v1.SetPeerComputeTrustRequest
	2,  // 12: sisyphus.node.v1.NodeService.GetNodeInfo:output_type -> sisyphus.node.v1.GetNodeInfoResponse
	14, // 13: sisyphus.node.v1.NodeService.ListPeers:output_type -> sisyphus.node.v1.ListPeersResponse
	14, // 14: sisyphus.node.v1.NodeService.WatchPeers:output_type -> sisyphus.node.v1.ListPeersResponse
	6,  // 15: sisyphus.node.v1.NodeService.GetBootstrapPeers:output_type -> sisyphus.node.v1.GetBootstrapPeersResponse
	8,  // 16: sisyphus.node.v1.NodeService.SetBootstrapPeers:output_type -> sisyphus.node.v1.SetBootstrapPeersResponse
	10, // 17: sisyphus.node.v1.NodeService.ConnectPeer:output_type -> sisyphus.node.v1.ConnectPeerResponse
	12, // 18: sisyphus.node.v1.NodeService.SetPeerComputeTrust:output_type -> sisyphus.node.v1.SetPeerComputeTrustResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_sisyphus_node_v1_node_proto_init() }
func file_sisyphus_node_v1_node_proto_init() {
	if File_sisyphus_node_v1_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sisyphus_node_v1_node_proto_rawDesc), len(file_sisyphus_node_v1_node_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sisyphus_node_v1_node_proto_goTypes,
		DependencyIndexes: file_sisyphus_node_v1_node_proto_depIdxs,
		EnumInfos:         file_sisyphus_node_v1_node_proto_enumTypes,
		MessageInfos:      file_sisyphus_node_v1_node_proto_msgTypes,
	}.Build()
	File_sisyphus_node_v1_node_proto = out.File
	file_sisyphus_node_v1_node_proto_goTypes = nil
	file_sisyphus_node_v1_node_proto_depIdxs = nil
}
