// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: sisyphus/node/v1/node.proto

package nodev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeService_GetNodeInfo_FullMethodName               = "/sisyphus.node.v1.NodeService/GetNodeInfo"
	NodeService_ListPeers_FullMethodName                 = "/sisyphus.node.v1.NodeService/ListPeers"
	NodeService_WatchPeers_FullMethodName                = "/sisyphus.node.v1.NodeService/WatchPeers"
	NodeService_GetBootstrapPeers_FullMethodName         = "/sisyphus.node.v1.NodeService/GetBootstrapPeers"
	NodeService_SetBootstrapPeers_FullMethodName         = "/sisyphus.node.v1.NodeService/SetBootstrapPeers"
	NodeService_ConnectPeer_FullMethodName               = "/sisyphus.node.v1.NodeService/ConnectPeer"
	NodeService_SetPeerComputeTrust_FullMethodName       = "/sisyphus.node.v1.NodeService/SetPeerComputeTrust"
	NodeService_SetPeerComputePermissions_FullMethodName = "/sisyphus.node.v1.NodeService/SetPeerComputePermissions"
	NodeService_ListWorkers_FullMethodName               = "/sisyphus.node.v1.NodeService/ListWorkers"
	NodeService_SubmitJob_FullMethodName                 = "/sisyphus.node.v1.NodeService/SubmitJob"
	NodeService_GetJob_FullMethodName                    = "/sisyphus.node.v1.NodeService/GetJob"
	NodeService_ListJobs_FullMethodName                  = "/sisyphus.node.v1.NodeService/ListJobs"
	NodeService_WatchJobs_FullMethodName                 = "/sisyphus.node.v1.NodeService/WatchJobs"
	NodeService_CancelJob_FullMethodName                 = "/sisyphus.node.v1.NodeService/CancelJob"
	NodeService_WatchJobEvents_FullMethodName            = "/sisyphus.node.v1.NodeService/WatchJobEvents"
)

// NodeServiceClient is the client API for NodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeServiceClient interface {
	GetNodeInfo(ctx context.Context, in *GetNodeInfoRequest, opts ...grpc.CallOption) (*GetNodeInfoResponse, error)
	ListPeers(ctx context.Context, in *ListPeersRequest, opts ...grpc.CallOption) (*ListPeersResponse, error)
	WatchPeers(ctx context.Context, in *WatchPeersRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListPeersResponse], error)
	GetBootstrapPeers(ctx context.Context, in *GetBootstrapPeersRequest, opts ...grpc.CallOption) (*GetBootstrapPeersResponse, error)
	SetBootstrapPeers(ctx context.Context, in *SetBootstrapPeersRequest, opts ...grpc.CallOption) (*SetBootstrapPeersResponse, error)
	ConnectPeer(ctx context.Context, in *ConnectPeerRequest, opts ...grpc.CallOption) (*ConnectPeerResponse, error)
	// SetPeerComputeTrust sets both sides of trust in a peer at once: whether
	// this node gives it work and whether this node takes work from it.
	SetPeerComputeTrust(ctx context.Context, in *SetPeerComputeTrustRequest, opts ...grpc.CallOption) (*SetPeerComputeTrustResponse, error)
	// SetPeerComputePermissions sets the two sides separately.
	SetPeerComputePermissions(ctx context.Context, in *SetPeerComputePermissionsRequest, opts ...grpc.CallOption) (*SetPeerComputePermissionsResponse, error)
	// ListWorkers lists the nodes connected to this one as its workers.
	ListWorkers(ctx context.Context, in *ListWorkersRequest, opts ...grpc.CallOption) (*ListWorkersResponse, error)
	// SubmitJob gives the pool a job and returns it as it stands at once.
	SubmitJob(ctx context.Context, in *SubmitJobRequest, opts ...grpc.CallOption) (*SubmitJobResponse, error)
	GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error)
	// ListJobs lists the jobs this node has on record, newest first.
	ListJobs(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error)
	// WatchJobs sends that list at once and again, in full, whenever any job
	// changes, with a revision that counts up from one.
	WatchJobs(ctx context.Context, in *WatchJobsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListJobsResponse], error)
	// CancelJob stops a job that has not finished.
	CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*CancelJobResponse, error)
	// WatchJobEvents sends what has happened to a job, from the event after
	// the one named, and goes on as more happens until the job has finished:
	// the steps of its life and the lines its tasks log.
	WatchJobEvents(ctx context.Context, in *WatchJobEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobEvent], error)
}

type nodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeServiceClient(cc grpc.ClientConnInterface) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) GetNodeInfo(ctx context.Context, in *GetNodeInfoRequest, opts ...grpc.CallOption) (*GetNodeInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeInfoResponse)
	err := c.cc.Invoke(ctx, NodeService_GetNodeInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) ListPeers(ctx context.Context, in *ListPeersRequest, opts ...grpc.CallOption) (*ListPeersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPeersResponse)
	err := c.cc.Invoke(ctx, NodeService_ListPeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) WatchPeers(ctx context.Context, in *WatchPeersRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListPeersResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[0], NodeService_WatchPeers_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchPeersRequest, ListPeersResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_WatchPeersClient = grpc.ServerStreamingClient[ListPeersResponse]

func (c *nodeServiceClient) GetBootstrapPeers(ctx context.Context, in *GetBootstrapPeersRequest, opts ...grpc.CallOption) (*GetBootstrapPeersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBootstrapPeersResponse)
	err := c.cc.Invoke(ctx, NodeService_GetBootstrapPeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) SetBootstrapPeers(ctx context.Context, in *SetBootstrapPeersRequest, opts ...grpc.CallOption) (*SetBootstrapPeersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetBootstrapPeersResponse)
	err := c.cc.Invoke(ctx, NodeService_SetBootstrapPeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) ConnectPeer(ctx context.Context, in *ConnectPeerRequest, opts ...grpc.CallOption) (*ConnectPeerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectPeerResponse)
	err := c.cc.Invoke(ctx, NodeService_ConnectPeer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) SetPeerComputeTrust(ctx context.Context, in *SetPeerComputeTrustRequest, opts ...grpc.CallOption) (*SetPeerComputeTrustResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPeerComputeTrustResponse)
	err := c.cc.Invoke(ctx, NodeService_SetPeerComputeTrust_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) SetPeerComputePermissions(ctx context.Context, in *SetPeerComputePermissionsRequest, opts ...grpc.CallOption) (*SetPeerComputePermissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPeerComputePermissionsResponse)
	err := c.cc.Invoke(ctx, NodeService_SetPeerComputePermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) ListWorkers(ctx context.Context, in *ListWorkersRequest, opts ...grpc.CallOption) (*ListWorkersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkersResponse)
	err := c.cc.Invoke(ctx, NodeService_ListWorkers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) SubmitJob(ctx context.Context, in *SubmitJobRequest, opts ...grpc.CallOption) (*SubmitJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitJobResponse)
	err := c.cc.Invoke(ctx, NodeService_SubmitJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobResponse)
	err := c.cc.Invoke(ctx, NodeService_GetJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) ListJobs(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListJobsResponse)
	err := c.cc.Invoke(ctx, NodeService_ListJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) WatchJobs(ctx context.Context, in *WatchJobsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListJobsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[1], NodeService_WatchJobs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchJobsRequest, ListJobsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_WatchJobsClient = grpc.ServerStreamingClient[ListJobsResponse]

func (c *nodeServiceClient) CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*CancelJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelJobResponse)
	err := c.cc.Invoke(ctx, NodeService_CancelJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) WatchJobEvents(ctx context.Context, in *WatchJobEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[2], NodeService_WatchJobEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchJobEventsRequest, JobEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_WatchJobEventsClient = grpc.ServerStreamingClient[JobEvent]

// NodeServiceServer is the server API for NodeService service.
// All implementations must embed UnimplementedNodeServiceServer
// for forward compatibility.
type NodeServiceServer interface {
	GetNodeInfo(context.Context, *GetNodeInfoRequest) (*GetNodeInfoResponse, error)
	ListPeers(context.Context, *ListPeersRequest) (*ListPeersResponse, error)
	WatchPeers(*WatchPeersRequest, grpc.ServerStreamingServer[ListPeersResponse]) error
	GetBootstrapPeers(context.Context, *GetBootstrapPeersRequest) (*GetBootstrapPeersResponse, error)
	SetBootstrapPeers(context.Context, *SetBootstrapPeersRequest) (*SetBootstrapPeersResponse, error)
	ConnectPeer(context.Context, *ConnectPeerRequest) (*ConnectPeerResponse, error)
	// SetPeerComputeTrust sets both sides of trust in a peer at once: whether
	// this node gives it work and whether this node takes work from it.
	SetPeerComputeTrust(context.Context, *SetPeerComputeTrustRequest) (*SetPeerComputeTrustResponse, error)
	// SetPeerComputePermissions sets the two sides separately.
	SetPeerComputePermissions(context.Context, *SetPeerComputePermissionsRequest) (*SetPeerComputePermissionsResponse, error)
	// ListWorkers lists the nodes connected to this one as its workers.
	ListWorkers(context.Context, *ListWorkersRequest) (*ListWorkersResponse, error)
	// SubmitJob gives the pool a job and returns it as it stands at once.
	SubmitJob(context.Context, *SubmitJobRequest) (*SubmitJobResponse, error)
	GetJob(context.Context, *GetJobRequest) (*GetJobResponse, error)
	// ListJobs lists the jobs this node has on record, newest first.
	ListJobs(context.Context, *ListJobsRequest) (*ListJobsResponse, error)
	// WatchJobs sends that list at once and again, in full, whenever any job
	// changes, with a revision that counts up from one.
	WatchJobs(*WatchJobsRequest, grpc.ServerStreamingServer[ListJobsResponse]) error
	// CancelJob stops a job that has not finished.
	CancelJob(context.Context, *CancelJobRequest) (*CancelJobResponse, error)
	// WatchJobEvents sends what has happened to a job, from the event after
	// the one named, and goes on as more happens until the job has finished:
	// the steps of its life and the lines its tasks log.
	WatchJobEvents(*WatchJobEventsRequest, grpc.ServerStreamingServer[JobEvent]) error
	mustEmbedUnimplementedNodeServiceServer()
}

// UnimplementedNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeServiceServer struct{}

func (UnimplementedNodeServiceServer) GetNodeInfo(context.Context, *GetNodeInfoRequest) (*GetNodeInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodeInfo not implemented")
}
func (UnimplementedNodeServiceServer) ListPeers(context.Context, *ListPeersRequest) (*ListPeersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPeers not implemented")
}
func (UnimplementedNodeServiceServer) WatchPeers(*WatchPeersRequest, grpc.ServerStreamingServer[ListPeersResponse]) error {
	return status.Error(codes.Unimplemented, "method WatchPeers not implemented")
}
func (UnimplementedNodeServiceServer) GetBootstrapPeers(context.Context, *GetBootstrapPeersRequest) (*GetBootstrapPeersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBootstrapPeers not implemented")
}
func (UnimplementedNodeServiceServer) SetBootstrapPeers(context.Context, *SetBootstrapPeersRequest) (*SetBootstrapPeersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetBootstrapPeers not implemented")
}
func (UnimplementedNodeServiceServer) ConnectPeer(context.Context, *ConnectPeerRequest) (*ConnectPeerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConnectPeer not implemented")
}
func (UnimplementedNodeServiceServer) SetPeerComputeTrust(context.Context, *SetPeerComputeTrustRequest) (*SetPeerComputeTrustResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPeerComputeTrust not implemented")
}
func (UnimplementedNodeServiceServer) SetPeerComputePermissions(context.Context, *SetPeerComputePermissionsRequest) (*SetPeerComputePermissionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPeerComputePermissions not implemented")
}
func (UnimplementedNodeServiceServer) ListWorkers(context.Context, *ListWorkersRequest) (*ListWorkersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWorkers not implemented")
}
func (UnimplementedNodeServiceServer) SubmitJob(context.Context, *SubmitJobRequest) (*SubmitJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitJob not implemented")
}
func (UnimplementedNodeServiceServer) GetJob(context.Context, *GetJobRequest) (*GetJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJob not implemented")
}
func (UnimplementedNodeServiceServer) ListJobs(context.Context, *ListJobsRequest) (*ListJobsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListJobs not implemented")
}
func (UnimplementedNodeServiceServer) WatchJobs(*WatchJobsRequest, grpc.ServerStreamingServer[ListJobsResponse]) error {
	return status.Error(codes.Unimplemented, "method WatchJobs not implemented")
}
func (UnimplementedNodeServiceServer) CancelJob(context.Context, *CancelJobRequest) (*CancelJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelJob not implemented")
}
func (UnimplementedNodeServiceServer) WatchJobEvents(*WatchJobEventsRequest, grpc.ServerStreamingServer[JobEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchJobEvents not implemented")
}
func (UnimplementedNodeServiceServer) mustEmbedUnimplementedNodeServiceServer() {}
func (UnimplementedNodeServiceServer) testEmbeddedByValue()                     {}

// UnsafeNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServiceServer will
// result in compilation errors.
type UnsafeNodeServiceServer interface {
	mustEmbedUnimplementedNodeServiceServer()
}

func RegisterNodeServiceServer(s grpc.ServiceRegistrar, srv NodeServiceServer) {
	// If the following call panics, it indicates UnimplementedNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeService_ServiceDesc, srv)
}

func _NodeService_GetNodeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetNodeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetNodeInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetNodeInfo(ctx, req.(*GetNodeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_ListPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPeersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ListPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_ListPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ListPeers(ctx, req.(*ListPeersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_WatchPeers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchPeersRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeServiceServer).WatchPeers(m, &grpc.GenericServerStream[WatchPeersRequest, ListPeersResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_WatchPeersServer = grpc.ServerStreamingServer[ListPeersResponse]

func _NodeService_GetBootstrapPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBootstrapPeersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetBootstrapPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetBootstrapPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetBootstrapPeers(ctx, req.(*GetBootstrapPeersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_SetBootstrapPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetBootstrapPeersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).SetBootstrapPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_SetBootstrapPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).SetBootstrapPeers(ctx, req.(*SetBootstrapPeersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_ConnectPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ConnectPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_ConnectPeer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ConnectPeer(ctx, req.(*ConnectPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_SetPeerComputeTrust_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPeerComputeTrustRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).SetPeerComputeTrust(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_SetPeerComputeTrust_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).SetPeerComputeTrust(ctx, req.(*SetPeerComputeTrustRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_SetPeerComputePermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPeerComputePermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).SetPeerComputePermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_SetPeerComputePermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).SetPeerComputePermissions(ctx, req.(*SetPeerComputePermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_ListWorkers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ListWorkers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_ListWorkers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ListWorkers(ctx, req.(*ListWorkersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_SubmitJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).SubmitJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_SubmitJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).SubmitJob(ctx, req.(*SubmitJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetJob(ctx, req.(*GetJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_ListJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ListJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_ListJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ListJobs(ctx, req.(*ListJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_WatchJobs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchJobsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeServiceServer).WatchJobs(m, &grpc.GenericServerStream[WatchJobsRequest, ListJobsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_WatchJobsServer = grpc.ServerStreamingServer[ListJobsResponse]

func _NodeService_CancelJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).CancelJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_CancelJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).CancelJob(ctx, req.(*CancelJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_WatchJobEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchJobEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeServiceServer).WatchJobEvents(m, &grpc.GenericServerStream[WatchJobEventsRequest, JobEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_WatchJobEventsServer = grpc.ServerStreamingServer[JobEvent]

// NodeService_ServiceDesc is the grpc.ServiceDesc for NodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sisyphus.node.v1.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNodeInfo",
			Handler:    _NodeService_GetNodeInfo_Handler,
		},
		{
			MethodName: "ListPeers",
			Handler:    _NodeService_ListPeers_Handler,
		},
		{
			MethodName: "GetBootstrapPeers",
			Handler:    _NodeService_GetBootstrapPeers_Handler,
		},
		{
			MethodName: "SetBootstrapPeers",
			Handler:    _NodeService_SetBootstrapPeers_Handler,
		},
		{
			MethodName: "ConnectPeer",
			Handler:    _NodeService_ConnectPeer_Handler,
		},
		{
			MethodName: "SetPeerComputeTrust",
			Handler:    _NodeService_SetPeerComputeTrust_Handler,
		},
		{
			MethodName: "SetPeerComputePermissions",
			Handler:    _NodeService_SetPeerComputePermissions_Handler,
		},
		{
			MethodName: "ListWorkers",
			Handler:    _NodeService_ListWorkers_Handler,
		},
		{
			MethodName: "SubmitJob",
			Handler:    _NodeService_SubmitJob_Handler,
		},
		{
			MethodName: "GetJob",
			Handler:    _NodeService_GetJob_Handler,
		},
		{
			MethodName: "ListJobs",
			Handler:    _NodeService_ListJobs_Handler,
		},
		{
			MethodName: "CancelJob",
			Handler:    _NodeService_CancelJob_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchPeers",
			Handler:       _NodeService_WatchPeers_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchJobs",
			Handler:       _NodeService_WatchJobs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchJobEvents",
			Handler:       _NodeService_WatchJobEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sisyphus/node/v1/node.proto",
}
